import {useTeamAccess} from './team-data';
import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, Copy, FileText, Film, Image, Plus, RefreshCw, Sparkles, WandSparkles, X } from 'lucide-react';
import { makePost, platformMeta } from './model';
import type { Platform, Post } from './model';
import { useWorkspace } from './store';
import { readWorkspace, saveWorkspace } from './runtime';
import { Modal, PlatformIcon, Select } from './ui';
import SocialPreview from './SocialPreview';
import { blobToDataURL, goalOptions } from './media-generation';
import type { VideoScript } from './media-generation';
import './controller.css';
import './controller-v3.css';
import { learnEdit, preferenceSummary, recordLearning, getLearning } from './learning';
import { applyBrandProtection, verifiedFactsForContent, getBrain } from './brain-data';
import ContentHealth from './ContentHealth';
import { getGrowth } from './growth-data';
import { AssetPicker } from './AssetLibrary';
import CreativeGenerator from './CreativeGenerator';
import {requestAI} from './ai-api';

interface Variant { label: string; angle: string; text: string }
const platforms: Platform[] = ['telegram', 'instagram', 'vk', 'youtube', 'threads', 'dzen', 'max', 'tiktok'];
const initialGoal = 'registrations';
const goalLabel = (goal: string) => goalOptions.find(option => option.value === goal)?.label ?? 'Информирование';

function adaptText(text: string, platform: Platform) {
  if (platform === 'telegram') return text;
  const clean = text.replace(/\*\*([^*]+)\*\*/g, '$1').replace(/\[([^\]]+)\]\(([^)]+)\)/g, '$1 ($2)');
  if (platform === 'instagram') return clean.replace(/\n\n0([1-3])\./g, '\n\n$1.');
  if (platform === 'youtube') return clean.replace(/в комментариях\./g, 'в комментариях к видео.');
  if (platform === 'threads' && clean.length > 500) {const paragraphs=clean.split('\n\n');const last=paragraphs.at(-1)?.slice(0,170)??'';return `${clean.slice(0,Math.max(0,497-last.length)).trimEnd()}…\n\n${last}`;}
  return clean;
}
function platformBodies(text: string, selected: Platform[]) {return Object.fromEntries(selected.map(platform => [platform, adaptText(text, platform)]));}
interface Idea {title:string;description:string;format:string;number:string}

export default function Controller() {
  const canCreate=useTeamAccess().can('createPosts');
  const {brand,posts,addPost,navigate,notify,setContentFilter,section,setSection}=useWorkspace();
  const [topic,setTopic]=useState(''),[tone,setTone]=useState(preferenceSummary().favoriteTone??brand.tone),[goal,setGoal]=useState(()=>readWorkspace<{goal?:string}>('publishing-preferences-v1',{}).goal??initialGoal);
  const [variants,setVariants]=useState<Variant[]>([]),[activeVariant,setActiveVariant]=useState(0),[text,setText]=useState('');
  const [selectedPlatforms,setSelectedPlatforms]=useState<Platform[]>(()=>readWorkspace<{platforms?:Platform[]}>('publishing-preferences-v1',{}).platforms??['telegram','instagram']),[previewPlatform,setPreviewPlatform]=useState<Platform>(selectedPlatforms[0]??'telegram'),[rightTab,setRightTab]=useState<'channels'|'preview'>('channels');
  const [abTest,setAbTest]=useState(false),[revision,setRevision]=useState(0),[pendingIdea,setPendingIdea]=useState(''),[saved,setSaved]=useState(false);
  const [generator,setGenerator]=useState<'image'|'video'|null>(null),[attachment,setAttachment]=useState<Post['media']>(),[scriptAttachment,setScriptAttachment]=useState<VideoScript>();
  const [libraryOpen,setLibraryOpen]=useState(false);
  const originalText=useRef('');
  const [ideas,setIdeas]=useState<Idea[]>(()=>readWorkspace<Idea[]>('ai-ideas-v1',[]));
  const [generating,setGenerating]=useState(false),[ideasBusy,setIdeasBusy]=useState(false),[generationError,setGenerationError]=useState('');
  const requestRef=useRef<AbortController|null>(null);
  useEffect(()=>()=>requestRef.current?.abort(),[]);
  const context=()=>({brand,verifiedFacts:verifiedFactsForContent(),brandRules:getBrain().rules,preferences:preferenceSummary(),events:getGrowth().events.slice(0,8),marketObservations:getGrowth().observations.slice(0,8),pastPosts:posts.slice(0,12).map(post=>({title:post.title,body:post.body.slice(0,900),status:post.status})),performance:Object.values(getLearning().performance).slice(0,10)});
  const tones=Array.from(new Set([brand.tone,'Дружелюбный','Экспертный','Деловой','Лаконичный','Смелый']));
  const markChanged=()=>setSaved(false);
  async function generateIdeas(){if(!canCreate||ideasBusy||generating)return;const abort=new AbortController();requestRef.current=abort;setIdeasBusy(true);setGenerationError('');try{const result=await requestAI<{ideas:Omit<Idea,'number'>[]}>({task:'ideas',format:'json',context:context(),prompt:`Предложи 6 разных актуальных идей публикаций для компании. Цель: ${goalLabel(goal)}. Не копируй конкурентов, используй данные компании и свободные темы. Не выдавай свежие новости за проверенные. Избегай тем из предыдущих публикаций. Верни JSON {"ideas":[{"title":"тема до 120 символов","description":"суть","format":"Пост или Карусель или История"}]}.`},abort.signal);if(!Array.isArray(result.data?.ideas)||!result.data.ideas.length)throw new Error('Не удалось получить идеи. Повторите запрос.');const next=result.data.ideas.slice(0,6).map((idea,index)=>{if(typeof idea.title!=='string'||!idea.title.trim())throw new Error('Не удалось прочитать идеи');return {title:idea.title.slice(0,180),description:String(idea.description||'').slice(0,500),format:String(idea.format||'Пост').slice(0,40),number:String(index+1).padStart(2,'0')};});setIdeas(next);saveWorkspace('ai-ideas-v1',next);}catch(error){if(!abort.signal.aborted)setGenerationError(error instanceof Error?error.message:'Не удалось создать идеи');}finally{if(!abort.signal.aborted)setIdeasBusy(false);}}
  async function generateText(){if(!canCreate||!topic.trim()||generating||ideasBusy)return;const abort=new AbortController();requestRef.current=abort;setGenerating(true);setGenerationError('');try{const result=await requestAI<{variants:Variant[]}>({task:'text',format:'json',context:context(),prompt:`Создай 3 содержательных разных варианта публикации. Тема: ${topic}. Цель: ${goalLabel(goal)}. Тон: ${tone}. Площадки: ${selectedPlatforms.map(p=>platformMeta[p].name).join(', ')}. Вариант генерации: ${revision+1}. Используй конкретику компании и уместный CTA под цель, не делай продукт компании похожим на контент-платформу, если это другой бизнес. Не повторяй вводные фразы. Верни JSON {"variants":[{"label":"ракурс","angle":"структура","text":"полный готовый текст"}]}.`},abort.signal);if(!Array.isArray(result.data?.variants)||!result.data.variants.length)throw new Error('Не удалось получить варианты. Повторите запрос.');const next=result.data.variants.slice(0,3).map(v=>{if(typeof v.text!=='string'||!v.text.trim())throw new Error('Сервис вернул пустой вариант');return {label:String(v.label||'Вариант'),angle:String(v.angle||''),text:applyBrandProtection(v.text,topic).body};});originalText.current=next[0].text;recordLearning({type:'generation',label:topic,goal,tone});setVariants(next);setText(next[0].text);setActiveVariant(0);setRevision(v=>v+1);markChanged();}catch(error){if(!abort.signal.aborted)setGenerationError(error instanceof Error?error.message:'Не удалось создать текст');}finally{if(!abort.signal.aborted)setGenerating(false);}}
  function selectPlatform(platform:Platform){const next=selectedPlatforms.includes(platform)?selectedPlatforms.filter(p=>p!==platform):[...selectedPlatforms,platform];setSelectedPlatforms(next);if(!next.includes(previewPlatform))setPreviewPlatform(next[0]??platform);markChanged();}
  function openGenerator(kind:'image'|'video') {if(canCreate)setGenerator(kind);}
  function saveDrafts(){if(!canCreate)return;if(!topic.trim()||!text.trim()||!selectedPlatforms.length)return;learnEdit(originalText.current,text,goal,tone);recordLearning({type:'selection',label:topic,goal,tone,selected:activeVariant,rejected:Math.max(0,variants.length-1)});const base:Partial<Post>={platforms:selectedPlatforms,goal,media:attachment,videoScript:scriptAttachment,format:attachment?.kind==='video'?'Видео':attachment?'Изображение':'Пост'};if(abTest&&variants.length>1){const split=Math.ceil(selectedPlatforms.length/2),first=selectedPlatforms.slice(0,split),last=selectedPlatforms.slice(split);const second=last.length?last:first;const secondText=variants[(activeVariant+1)%variants.length].text;addPost(makePost(`${topic} · A`,{...base,body:text,platformBodies:platformBodies(text,first),platforms:first,abTest:true}));addPost(makePost(`${topic} · B`,{...base,body:secondText,platformBodies:platformBodies(secondText,second),platforms:second,abTest:true}));notify('Варианты A и B сохранены');}else{addPost(makePost(topic,{...base,body:text,platformBodies:platformBodies(text,selectedPlatforms)}));notify('Черновик сохранён');}setSaved(true);}
  const goDrafts=()=>{setContentFilter('draft');navigate('content');};
  const currentPreview=adaptText(text,previewPlatform);
  return <div className="controller-page controller-v3 controller-v4"><div className="page-heading"><h1 className="page-title">Студия</h1>{section==='ideas'&&<div className="idea-heading-actions"><Select aria-label="Цель идей" value={goal} onChange={setGoal} disabled={!canCreate||ideasBusy||generating} options={goalOptions}/><button className="btn btn-primary" disabled={!canCreate||ideasBusy||generating} onClick={()=>void generateIdeas()}><RefreshCw size={15}/>{ideasBusy?'Подбираем идеи…':'Новые идеи'}</button></div>}</div>
    {generationError&&<p className="generation-error" role="alert">{generationError}</p>}
    {section==='ideas'?<div className="idea-mosaic">{!ideas.length&&<button className="idea-tile idea-tile-0 idea-start" disabled={!canCreate||ideasBusy} onClick={()=>void generateIdeas()}><div className="idea-tile-top"><Sparkles size={22}/><ArrowUpRight size={20}/></div><div className="idea-tile-art" aria-hidden="true"><i/><i/><i/><span>↗</span></div><div className="idea-tile-bottom"><h2>{ideasBusy?'Ищем новые ракурсы':'Начнём с хорошей идеи'}</h2><span className="idea-tile-action">{ideasBusy?'Генерация…':'Получить идеи'}<ArrowRight size={16}/></span></div></button>}{ideas.map((idea,index)=><button key={`${idea.title}-${index}`} className={`idea-tile idea-tile-${index}`} onClick={()=>setPendingIdea(idea.title)}><div className="idea-tile-top"><span>{idea.format}</span><ArrowUpRight size={20}/></div><div className="idea-tile-art" aria-hidden="true">{index===0?<><i/><i/><i/><span>↗</span></>:index===1?<span>?</span>:index===2?<><b>01</b><b>02</b><b>03</b></>:index===3?<span>→</span>:index===4?<><i/><i/><i/></>:<span>↗</span>}</div><div className="idea-tile-bottom"><span className="idea-tile-number">{idea.number} / {goalLabel(goal)}</span><h2>{idea.title}</h2><span className="idea-tile-action">Создать черновик<ArrowRight size={16}/></span></div></button>)}</div>
    :<div className="creation-layout"><div className="creation-main"><section className="panel creation-topic"><div className="creation-section-title"><h2>Тема публикации</h2><Sparkles size={17}/></div><textarea aria-label="Тема публикации" disabled={generating} className="creation-topic-input" value={topic} maxLength={180} rows={2} onChange={e=>{setTopic(e.target.value);markChanged();}} placeholder="О чём расскажем?"/><div className="creation-brief-options"><div><span>Цель</span><Select aria-label="Цель публикации" value={goal} onChange={value=>{setGoal(value);markChanged();}} options={goalOptions}/></div><div><span>Тон</span><Select aria-label="Тон публикации" value={tone} onChange={value=>{setTone(value);markChanged();}} options={tones.map(value=>({value,label:value}))}/></div></div></section>
      <section className="panel creation-text"><div className="creation-section-title"><h2>Текст</h2><button className="btn btn-ghost" disabled={!canCreate||!topic.trim()||generating||ideasBusy} onClick={()=>void generateText()}><WandSparkles size={15}/>{generating?'Создаём текст…':variants.length?'Перегенерировать':'Сгенерировать'}</button></div>{variants.length>0&&<div className="creation-variants" role="group" aria-label="Варианты текста">{variants.map((variant,index)=><button key={index} aria-pressed={activeVariant===index} className={activeVariant===index?'active':''} onClick={()=>{setActiveVariant(index);setText(variant.text);originalText.current=variant.text;markChanged();}}>Вариант {index+1}</button>)}</div>}<textarea aria-label="Текст публикации" disabled={generating} value={text} onChange={e=>{setText(e.target.value);setVariants(values=>values.map((v,i)=>i===activeVariant?{...v,text:e.target.value}:v));markChanged();}} placeholder="Напишите текст или сгенерируйте первый вариант" className="creation-body"/><div className="creation-text-footer"><span>{text.length.toLocaleString('ru-RU')} символов</span><button className="icon-button" disabled={!text} aria-label="Копировать текст" onClick={()=>void navigator.clipboard.writeText(text).then(()=>notify('Текст скопирован'),()=>notify('Не удалось скопировать'))}><Copy size={14}/></button></div></section>
      <ContentHealth title={topic} body={text} media={attachment} goal={goal} onChange={value=>{setText(value);markChanged();}}/><section className="panel creation-media"><div className="creation-section-title"><h2>Креативы</h2>{attachment&&<button className="icon-button" aria-label="Удалить вложение" onClick={()=>{setAttachment(undefined);setScriptAttachment(undefined);markChanged();}}><X size={15}/></button>}</div><div className="creation-media-options">{([{kind:'image',label:'Изображение',icon:Image},{kind:'video',label:'Видео',icon:Film}] as const).map(({kind,label,icon:Icon})=><button key={kind} role="checkbox" aria-checked={attachment?.kind===kind} aria-label={`Добавить ${label.toLowerCase()}`} className={attachment?.kind===kind?'selected':''} onClick={()=>{if(attachment?.kind===kind){setAttachment(undefined);setScriptAttachment(undefined);markChanged();}else openGenerator(kind);}}><span className="media-check">{attachment?.kind===kind&&<Check size={12}/>}</span><Icon size={19}/><span>{label}</span><Plus size={15}/></button>)}</div><div className="creation-library-choice"><span>или</span><button className="text-button" onClick={()=>setLibraryOpen(true)}>Выбрать из медиатеки<ArrowUpRight size={15}/></button></div>{attachment&&<button className="creation-attached" onClick={()=>openGenerator(attachment.kind)}>{attachment.kind==='image'?<img src={attachment.url} alt="Вложенный визуал"/>:<Film size={27}/>}<span><strong>{attachment.kind==='image'?'Визуал к публикации':'Видео к публикации'}</strong><small>{attachment.format.toUpperCase()}</small></span><ArrowUpRight size={17}/></button>}</section></div>
      <aside className="creation-side"><section className="panel creation-publishing"><div className="creation-side-tabs" role="group" aria-label="Настройка публикации"><button className={rightTab==='channels'?'active':''} aria-pressed={rightTab==='channels'} onClick={()=>setRightTab('channels')}>Площадки</button><button className={rightTab==='preview'?'active':''} aria-pressed={rightTab==='preview'} onClick={()=>setRightTab('preview')}>Предпросмотр</button></div>{rightTab==='channels'?<><div className="creation-channels">{platforms.map(platform=><button className={selectedPlatforms.includes(platform)?'selected':''} key={platform} aria-pressed={selectedPlatforms.includes(platform)} onClick={()=>selectPlatform(platform)}><PlatformIcon platform={platform} size={31}/><span>{platformMeta[platform].name}</span><span className="media-check">{selectedPlatforms.includes(platform)&&<Check size={12}/>}</span></button>)}</div><div className="creation-ab"><span>A/B-тест</span><button role="switch" aria-checked={abTest} aria-label="Подготовить A/B-тест" className={`controller-switch ${abTest?'on':''}`} onClick={()=>{setAbTest(!abTest);markChanged();}}><span/></button></div></>:<div className="creation-preview"><Select aria-label="Площадка предпросмотра" value={previewPlatform} onChange={value=>setPreviewPlatform(value as Platform)} options={platforms.map(value=>({value,label:platformMeta[value].name}))}/><SocialPreview platform={previewPlatform} body={currentPreview} title={topic} visual={attachment} brandName={brand.name}/></div>}<div className="creation-save"><button className="btn btn-primary" disabled={!canCreate||saved||!topic.trim()||!text.trim()||!selectedPlatforms.length||(abTest&&variants.length<2)} onClick={saveDrafts}>{saved?<Check size={16}/>:<FileText size={16}/>} {saved?'Сохранено':abTest?'Сохранить A и B':'Сохранить черновик'}</button>{saved&&<button className="text-button" onClick={goDrafts}>Открыть черновики<ArrowRight size={14}/></button>}</div></section></aside></div>}
    {libraryOpen&&<AssetPicker onClose={()=>setLibraryOpen(false)} onSelect={async(asset,blob)=>{try{const url=await blobToDataURL(blob);setAttachment({kind:asset.kind==='video'?'video':'image',url,format:asset.name.split('.').at(-1)||asset.mime});setScriptAttachment(undefined);setLibraryOpen(false);markChanged();}catch{notify('Не удалось добавить материал');}}}/>}
    {pendingIdea&&<Modal title="Создать черновик?" onClose={()=>setPendingIdea('')}><div className="idea-confirm"><span className="idea-confirm-mark"><Sparkles size={23}/></span><p>Тема:</p><h3>«{pendingIdea}»</h3><div><button className="btn btn-ghost" onClick={()=>setPendingIdea('')}>Отмена</button><button className="btn btn-primary" onClick={()=>{setTopic(pendingIdea);setText('');setVariants([]);setAttachment(undefined);setScriptAttachment(undefined);setSaved(false);setPendingIdea('');setSection('create');}}>Создать<ArrowRight size={15}/></button></div></div></Modal>}
    {generator&&<CreativeGenerator kind={generator} topic={topic} postText={text} onClose={()=>setGenerator(null)} onAdd={(media,script)=>{setAttachment(media);setScriptAttachment(script);markChanged();}}/>}
  </div>;
}
