import {aiHeaders} from './ai-api';
import { useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowRight, Check, Film, ImagePlus, LoaderCircle, Plus, RefreshCw, SlidersHorizontal, Sparkles, X } from 'lucide-react';
import { Modal } from './ui';
import type { Post } from './model';
import type { VideoScript } from './media-generation';
import { blobToDataURL, downloadFile } from './media-generation';
import { saveAsset, verifiedBrandContext } from './brain-data';
import { isLabrika } from './runtime';
import { recordUsage } from './billing-data';
import './creative-generator.css';

type Scene={id:string;heading:string;description:string;duration:number;image?:string};
type Job={id:string;token?:string;kind:'image'|'video';status:'running'|'review'|'complete'|'error';stage:string;scenes:Scene[];result?:string;title?:string;caption?:string;duration?:number;aspect?:string;error?:string};
type Reference={name:string;data:string};
const stages=[['script','Сценарий'],['visuals','Визуальные сцены'],['animation','Анимация'],['montage','Монтаж'],['ready','Готово']];
async function request(path:string,method='GET',data?:unknown,token?:string,signal?:AbortSignal):Promise<Job>{const response=await fetch(`/api/creative/${path}`,{method,headers:{...aiHeaders(),...(token?{'X-Creative-Token':token}:{})},...(data?{body:JSON.stringify(data)}:{}),signal});const value=await response.json();if(!response.ok)throw Object.assign(new Error(value.error||'Не удалось связаться с сервисом'),{status:response.status});return value;}
export default function CreativeGenerator({kind,topic,postText,onClose,onAdd}:{kind:'image'|'video';topic:string;postText:string;onClose:()=>void;onAdd:(media:NonNullable<Post['media']>,script?:VideoScript)=>void}){
 const [prompt,setPrompt]=useState(kind==='video'&&topic?`Показать «${topic}» через последовательную историю: знакомство, ключевая мысль, результат.${postText.trim()?` Основа: ${postText.replace(/\s+/g,' ').slice(0,350)}`:''}`:''),[references,setReferences]=useState<Reference[]>([]),[duration,setDuration]=useState(30),[aspect,setAspect]=useState('9:16'),[mode,setMode]=useState('automatic');
 const [job,setJob]=useState<Job|null>(null),[scenes,setScenes]=useState<Scene[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reading,setReading]=useState(false),[editing,setEditing]=useState(false);
 const active=useRef<{id:string;token:string}|null>(null),abort=useRef<AbortController|null>(null),fileInput=useRef<HTMLInputElement>(null),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;abort.current?.abort();if(active.current)void request(`jobs/${active.current.id}`,'DELETE',undefined,active.current.token).catch(()=>{});};},[]);
 useEffect(()=>{if(job?.status!=='running'||!active.current)return;const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const current=active.current;if(!current)return;const next=await request(`jobs/${current.id}`,'GET',undefined,current.token,controller.signal);if(controller.signal.aborted)return;setJob(next);setScenes(next.scenes);if(next.status==='running')timer=setTimeout(poll,1200);else if(next.status==='error')setError(next.error||'Не удалось завершить генерацию');}catch(e){if(!controller.signal.aborted){setError(e instanceof Error?e.message:'Нет соединения');if((e as {status?:number}).status===404)setJob(current=>current?{...current,status:'error'}:current);else timer=setTimeout(poll,4000);}}};timer=setTimeout(poll,700);return()=>{clearTimeout(timer);controller.abort();};},[job?.id,job?.status]);
 async function addReferences(files:FileList|null){if(!files)return;setError('');const values=Array.from(files);if(fileInput.current)fileInput.current.value='';if(values.length+references.length>10){setError('Можно прикрепить до 10 референсов');return;}if(values.some(file=>!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024)){setError('Выберите PNG, JPEG или WebP до 5 МБ');return;}setReading(true);try{const next=await Promise.all(values.map(async file=>({name:file.name,data:await blobToDataURL(file)})));if(next.reduce((n,r)=>n+r.data.length,0)+references.reduce((n,r)=>n+r.data.length,0)>20*1024*1024)throw new Error('Общий размер референсов — до 15 МБ');if(mounted.current)setReferences(r=>[...r,...next]);}catch(e){setError(e instanceof Error?e.message:'Не удалось прочитать изображения');}finally{if(mounted.current)setReading(false);if(fileInput.current)fileInput.current.value='';}}
 async function start(){if(busy||!prompt.trim())return;setBusy(true);setError('');setEditing(false);abort.current=new AbortController();try{if(active.current){await request(`jobs/${active.current.id}`,'DELETE',undefined,active.current.token);active.current=null;}setJob(null);const next=await request('jobs','POST',{kind,prompt,references,duration,aspect,mode,topic,postText,brandContext:verifiedBrandContext()},undefined,abort.current.signal);active.current={id:next.id,token:next.token!};setJob(next);setScenes(next.scenes);}catch(e){if(!abort.current.signal.aborted)setError(e instanceof Error?e.message:'Не удалось начать генерацию');}finally{if(mounted.current)setBusy(false);}}
 async function update(action:'continue'|'scene',scene?:Scene){const current=active.current;if(!current||busy)return;setBusy(true);setError('');try{const next=await request(`jobs/${current.id}/${action}`,'POST',action==='scene'?{id:scene?.id,description:scene?.description}:{scenes},current.token);setEditing(false);setJob(next);}catch(e){setError(e instanceof Error?e.message:'Не удалось обновить видео');}finally{if(mounted.current)setBusy(false);}}
 async function add(){if(!job?.result||busy)return;setBusy(true);setError('');try{const blob=await(await fetch(job.result)).blob();const format=blob.type.split('/')[1]|| (kind==='image'?'png':'mp4');await saveAsset(new File([blob],`${(topic||job.title||'Креатив').slice(0,70)}.${format}`,{type:blob.type}));if(isLabrika)recordUsage(kind==='image'?'images':'videoSeconds',kind==='image'?1:(job.duration??duration));onAdd({kind,url:job.result,format},kind==='video'?{title:job.title||topic,caption:job.caption||'',scenes:job.scenes.map(s=>({heading:s.heading,text:s.description,duration:s.duration}))}:undefined);onClose();}catch(e){setError(e instanceof Error?e.message:'Не удалось добавить файл');}finally{if(mounted.current)setBusy(false);}}
 const running=job?.status==='running',ready=job?.status==='complete',review=job?.status==='review',disabled=busy||running||reading;
 const sceneList=<div className="creative-scenes">{scenes.map((scene,index)=>{const start=scenes.slice(0,index).reduce((sum,s)=>sum+s.duration,0);return <article className="creative-scene" key={scene.id}>{scene.image&&<img src={scene.image} alt={`Кадр сцены ${index+1}`}/>}<div><div className="creative-scene-top"><strong>Сцена {index+1}</strong><span>{start}–{start+scene.duration} сек</span></div>{review||editing?<textarea aria-label={`Описание сцены ${index+1}`} maxLength={3000} value={scene.description} rows={3} disabled={disabled} onChange={e=>setScenes(current=>current.map(s=>s.id===scene.id?{...s,description:e.target.value}:s))}/>:<p>{scene.description}</p>}{editing&&<button className="text-button" disabled={disabled||!scene.description.trim()} onClick={()=>void update('scene',scene)}><RefreshCw size={14}/>Перегенерировать сцену</button>}</div></article>;})}</div>;
 return <Modal title={kind==='image'?'Генератор визуала':'Генератор видео'} onClose={onClose} wide><div className={`creative-studio creative-${kind}`}>
  <div className="creative-brief"><label className="field">{kind==='image'?'Что должно быть на изображении?':'Что должно быть в видео?'}<textarea aria-label={kind==='image'?'Промпт изображения':'Что должно быть в видео?'} value={prompt} onChange={e=>setPrompt(e.target.value)} disabled={disabled||review} placeholder={kind==='image'?'Опишите сюжет, настроение и детали':'Опишите идею ролика'} rows={kind==='image'?6:4} maxLength={6000}/></label>
   <div className="creative-reference-title"><span>Референсы</span><span>{references.length}/10</span></div><input ref={fileInput} type="file" multiple accept="image/png,image/jpeg,image/webp" hidden aria-label="Прикрепить референсы" onChange={e=>void addReferences(e.target.files)}/><div className="creative-references">{references.map((reference,index)=><div key={`${index}-${reference.name}`} className="creative-reference"><img src={reference.data} alt={reference.name}/><button className="icon-button" aria-label={`Удалить референс ${index+1}`} disabled={disabled||review} onClick={()=>setReferences(r=>r.filter((_,i)=>i!==index))}><X size={12}/></button></div>)}{references.length<10&&<button className="creative-upload" aria-label="Добавить референсы" disabled={disabled||review} onClick={()=>fileInput.current?.click()}>{reading?<LoaderCircle className="spin" size={22}/>:<Plus size={22}/>}<span>{references.length?'Добавить':'Изображения'}</span></button>}</div>
   {kind==='video'&&<><div className="creative-option"><span>Длительность</span><div className="creative-segments" role="group" aria-label="Длительность видео">{[15,30,45,60].map(value=><button key={value} disabled={disabled||review} aria-pressed={duration===value} onClick={()=>setDuration(value)}>{value} сек</button>)}</div></div><div className="creative-option"><span>Формат</span><div className="creative-segments" role="group" aria-label="Формат видео">{['9:16','1:1','16:9'].map(value=><button key={value} disabled={disabled||review} aria-pressed={aspect===value} onClick={()=>setAspect(value)}>{value}</button>)}</div></div><div className="creative-option"><span>Режим</span><div className="creative-segments creative-modes" role="group" aria-label="Режим генерации">{[['automatic','Автоматически'],['review','С проверкой']].map(([value,label])=><button key={value} disabled={disabled||review} aria-pressed={mode===value} onClick={()=>setMode(value)}>{label}</button>)}</div></div></>}
   {error&&<p role="alert" className="creative-error">{error}</p>}
   {!ready&&!review&&!running&&<button className="btn btn-primary creative-submit" disabled={disabled||!prompt.trim()} onClick={()=>void start()}>{busy?<LoaderCircle className="spin" size={16}/>:<Sparkles size={16}/>}Создать {kind==='image'?'изображение':'видео'}</button>}
   {review&&<button className="btn btn-primary creative-submit" disabled={disabled||scenes.some(s=>!s.description.trim())} onClick={()=>void update('continue')}>Утвердить и создать<ArrowRight size={16}/></button>}
   {ready&&<div className="creative-result-actions"><button className="btn btn-primary" disabled={busy} onClick={()=>void add()}><Check size={16}/>Добавить к посту</button><button className="btn" onClick={async()=>{try{const blob=await(await fetch(job.result!)).blob();downloadFile(blob,`creative.${blob.type.split('/')[1]}`);}catch{setError('Не удалось скачать файл');}}}><ArrowDownToLine size={15}/>Скачать</button><button className="text-button" onClick={()=>void start()} disabled={disabled}><RefreshCw size={14}/>Создать другой вариант</button>{kind==='video'&&<button className="text-button" onClick={()=>setEditing(v=>!v)}><SlidersHorizontal size={14}/>{editing?'Вернуться к видео':'Изменить видео'}</button>}</div>}
  </div>
  <div className="creative-output">{kind==='video'&&job&&<ol className="creative-progress" aria-label="Этапы генерации">{stages.map(([key,label],index)=><li key={key} className={job.stage===key?'current':stages.findIndex(([id])=>id===job.stage)>index?'done':''} aria-current={job.stage===key?'step':undefined}><span>{stages.findIndex(([id])=>id===job.stage)>index?<Check size={12}/>:index+1}</span>{label}</li>)}</ol>}
   {ready&&!editing?<div className="creative-result">{kind==='image'?<img src={job.result} alt="Сгенерированное изображение"/>:<video src={job.result} controls playsInline style={{aspectRatio:(job.aspect??aspect).replace(':','/')}}/>}{kind==='video'&&<div className="creative-video-caption"><strong>{job.title}</strong>{job.caption&&<p>{job.caption}</p>}</div>}</div>:review||editing?sceneList:running?<div className="creative-work"><div className="creative-orbit"><LoaderCircle className="spin" size={32}/></div><h3>{kind==='image'?'Создаём изображение':stages.find(([id])=>id===job.stage)?.[1]}</h3>{scenes.length>0&&sceneList}</div>:<div className="creative-empty"><div className="creative-empty-art">{kind==='image'?<ImagePlus size={40} strokeWidth={1}/>:<Film size={40} strokeWidth={1}/>}</div><span>{kind==='image'?'Место для вашей идеи':'Ваша идея в движении'}</span></div>}
  </div>
 </div></Modal>;
}
