import {useState} from 'react';
import {Check} from 'lucide-react';
import {Modal} from './ui';
import {saveSubscriptionPlan} from './billing-data';
import type {SubscriptionPlan,PlanLimits} from './billing-data';
import './plan-editor.css';
const limits:{key:keyof PlanLimits;label:string}[]=[{key:'brands',label:'Бренды'},{key:'profiles',label:'Социальные профили'},{key:'posts',label:'Публикации в месяц'},{key:'images',label:'Изображения в месяц'},{key:'videoSeconds',label:'Видео, секунд в месяц'},{key:'seats',label:'Участники'}];
export default function PlanEditor({plan,onClose,onSaved}:{plan:SubscriptionPlan;onClose:()=>void;onSaved:()=>void}){
 const [name,setName]=useState(plan.name),[description,setDescription]=useState(plan.description),[price,setPrice]=useState(String(plan.price)),[features,setFeatures]=useState(plan.features.join('\n')),[highlighted,setHighlighted]=useState(!!plan.highlighted),[error,setError]=useState('');
 const [values,setValues]=useState(()=>Object.fromEntries(limits.map(({key})=>[key,plan.limits[key]===null?'':String(plan.limits[key])])) as Record<keyof PlanLimits,string>);
 function save(event:React.FormEvent){event.preventDefault();try{if(!price.trim())throw new Error('Укажите цену');saveSubscriptionPlan({...plan,name,description,price:Number(price),features:features.split('\n'),highlighted,limits:Object.fromEntries(limits.map(({key})=>[key,values[key].trim()===''?null:Number(values[key])])) as unknown as PlanLimits});onSaved();}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить тариф');}}
 return <Modal title={`Тариф ${plan.name}`} onClose={onClose} wide><form className="plan-editor" onSubmit={save}><div className="plan-editor-main"><label className="field">Название<input required maxLength={40} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">Цена в месяц, ₽<input required inputMode="numeric" type="number" min={0} max={100000000} step={1} value={price} onChange={e=>setPrice(e.target.value)}/></label><label className="field plan-editor-wide">Описание<textarea aria-label="Описание" required maxLength={1000} rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="field plan-editor-wide">Возможности · по одной на строку<textarea aria-label="Возможности · по одной на строку" rows={6} value={features} onChange={e=>setFeatures(e.target.value)}/></label><label className="plan-editor-highlight"><input type="checkbox" checked={highlighted} onChange={e=>setHighlighted(e.target.checked)}/>Рекомендуемый тариф</label></div><div className="plan-editor-limits"><h3>Лимиты</h3><p>Пустое поле — индивидуальный объём</p>{limits.map(({key,label})=><label className="field" key={key}>{label}<input inputMode="numeric" type="number" min={0} step={1} max={100000000} value={values[key]} placeholder="Индивидуально" onChange={e=>setValues(previous=>({...previous,[key]:e.target.value}))}/></label>)}</div><div className="plan-editor-footer">{error&&<p role="alert">{error}</p>}<button type="button" className="btn btn-ghost" onClick={onClose}>Отмена</button><button className="btn btn-primary" type="submit"><Check size={15}/>Сохранить тариф</button></div></form></Modal>;
}
