import {useEffect,useRef,useState} from 'react';
import {Check,ImagePlus,Trash2} from 'lucide-react';
import {useWorkspace} from './store';
import {useTeamAccess} from './team-data';
import {Avatar} from './ui';
import './profile-details.css';
async function avatarFromFile(file:File):Promise<string>{
 if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Выберите изображение JPG, PNG или WebP');
 if(file.size>5*1024*1024)throw new Error('Размер изображения — до 5 МБ');
 const url=URL.createObjectURL(file);
 try{const image=new Image();image.src=url;await image.decode();if(!image.naturalWidth||!image.naturalHeight)throw new Error();const edge=Math.min(image.naturalWidth,image.naturalHeight);const canvas=document.createElement('canvas');canvas.width=canvas.height=320;const context=canvas.getContext('2d');if(!context)throw new Error();context.drawImage(image,(image.naturalWidth-edge)/2,(image.naturalHeight-edge)/2,edge,edge,0,0,320,320);return canvas.toDataURL('image/webp',.88);}catch{throw new Error('Не удалось открыть изображение');}finally{URL.revokeObjectURL(url);}
}
export default function Profile(){
 const {profile,setProfile,notify}=useWorkspace();const {isOwner}=useTeamAccess();const [draft,setDraft]=useState(profile),[error,setError]=useState(''),[uploading,setUploading]=useState(false);const fileInput=useRef<HTMLInputElement>(null);
 useEffect(()=>setDraft(profile),[profile]);
 const save=()=>{setError('');try{setProfile(isOwner?{...draft,name:draft.name.trim(),surname:draft.surname?.trim()??'',phone:draft.phone?.trim()??'',email:draft.email.trim()}:{...profile,avatar:draft.avatar});notify('Профиль сохранён');}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить профиль');}};
 return <><div className="page-heading"><h1 className="page-title">Профиль</h1></div><form className="panel profile-form profile-details" onSubmit={event=>{event.preventDefault();save();}}><div className="profile-details-heading"><div className="profile-picture"><Avatar name={[draft.name,draft.surname].filter(Boolean).join(' ')} src={draft.avatar} size={80}/><button type="button" className="profile-picture-edit" aria-label="Добавить фото профиля" disabled={uploading} onClick={()=>fileInput.current?.click()}><ImagePlus size={17}/></button><input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp" aria-label="Фото профиля" hidden onChange={async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;setError('');setUploading(true);try{const avatar=await avatarFromFile(file);setDraft(current=>({...current,avatar}));}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить фото');}finally{setUploading(false);}}}/></div><div><strong>{[draft.name,draft.surname].filter(Boolean).join(' ')||'Профиль'}</strong><span>{isOwner?'Руководитель':profile.role}</span></div>{draft.avatar&&<button type="button" className="icon-button profile-picture-remove" aria-label="Удалить фото профиля" onClick={()=>setDraft({...draft,avatar:''})}><Trash2 size={16}/></button>}</div><div className="profile-details-fields"><label className="field">Имя<input autoComplete="given-name" required readOnly={!isOwner} value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})}/></label><label className="field">Фамилия<input autoComplete="family-name" readOnly={!isOwner} value={draft.surname??''} onChange={event=>setDraft({...draft,surname:event.target.value})}/></label><label className="field">Телефон<input type="tel" autoComplete="tel" readOnly={!isOwner} value={draft.phone??''} onChange={event=>setDraft({...draft,phone:event.target.value})} placeholder="+7"/></label><label className="field">Почта<input type="email" autoComplete="email" readOnly={!isOwner} value={draft.email} onChange={event=>setDraft({...draft,email:event.target.value})} placeholder="name@company.ru"/></label></div>{error&&<div className="form-error" role="alert">{error}</div>}<button className="btn btn-primary" type="submit" disabled={uploading}><Check size={16}/>Сохранить</button></form></>;
}
