import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Check,ImagePlus,LoaderCircle,Send,X} from 'lucide-react';
import type {Platform,Post} from './model';
import {platformMeta} from './model';
import {Modal,PlatformIcon,Select} from './ui';
import {useWorkspace} from './store';
import {useTeamAccess} from './team-data';
import {protectBrand} from './brain-data';
import {getPolicy} from './admin-data';
import {blobToDataURL} from './media-generation';
import SocialPreview from './SocialPreview';
import {listConnections,publishSocial,socialRequest,isPublished} from './social-api';
import type {SocialConnection,SocialPublication,SocialDelivery,ProcessingPublication,TikTokCreator} from './social-api';
import './social-connections.css';
import TikTokControls,{emptyTikTokSettings,videoDuration,privacyLabels} from './TikTokControls';
const plain=(text:string)=>text.replace(/\*\*([^*]+)\*\*/g,'$1').replace(/\[([^\]]+)\]\(([^)]+)\)/g,'$1 ($2)');
export default function PublishDialog({post,editable=false,onClose}:{post:Post;editable?:boolean;onClose:()=>void}){
 const {can}=useTeamAccess();const canPublish=can('schedulePosts')&&(!editable||can('manageSocial'));
 const {brand,navigate,recordPublication,notify,closeEditor,posts,addPost}=useWorkspace();const [connections,setConnections]=useState<SocialConnection[]>([]),[platform,setPlatform]=useState<Platform>(post.platforms[0]||'telegram'),[body,setBody]=useState(plain(post.body)),[media,setMedia]=useState(post.media),[publicMedia,setPublicMedia]=useState(''),[publicKind,setPublicKind]=useState<'image'|'video'>(post.media?.kind||'image'),[visibility,setVisibility]=useState('private');
 const pendingDraftSaved=useRef(false);
 const [creator,setCreator]=useState<TikTokCreator|null>(null),[tiktok,setTiktok]=useState(emptyTikTokSettings),[processing,setProcessing]=useState<ProcessingPublication|null>(null),[checking,setChecking]=useState(false);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipts,setReceipts]=useState<Partial<Record<Platform,SocialPublication>>>(post.deliveries||{}),[done,setDone]=useState<SocialPublication|null>(null);const input=useRef<HTMLInputElement>(null),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;let active=true;void Promise.all([listConnections(),socialRequest<{publications:SocialDelivery[]}>(`/publications?postId=${encodeURIComponent(post.id)}`)]).then(([items,history])=>{if(!active)return;setConnections(items);setReceipts(previous=>({...previous,...Object.fromEntries(history.publications.filter(isPublished).map(p=>[p.platform,p]))}));const queued=history.publications.find(p=>p.status==='processing');if(queued&&!isPublished(queued)){setProcessing(queued);setPlatform(queued.platform);}const first=items.find(c=>c.status==='connected'&&post.platforms.includes(c.platform))||items.find(c=>c.status==='connected');if(!queued&&first&&!items.some(c=>c.platform===platform&&c.status==='connected'))setPlatform(first.platform);},e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;mounted.current=false;};},[post.id]);
 const connection=connections.find(c=>c.platform===platform&&c.status==='connected');const already=receipts[platform];const text=editable||platform==='tiktok'?body:post.platformBodies?.[platform]??plain(post.body);const needsURL=connection?.capabilities.requiresPublicMedia&&(!!media||!connection.capabilities.text||!!publicMedia);
 const sentMedia=needsURL?publicMedia.trim()?{kind:publicKind,url:publicMedia.trim(),format:publicKind==='image'?'jpg':'mp4'}:undefined:media;

 useEffect(()=>{if(platform!=='tiktok'||!connection)return;let active=true;setCreator(null);setTiktok(emptyTikTokSettings());void socialRequest<{creator:TikTokCreator}>('/connections/tiktok/creator-info','POST',{}).then(({creator})=>{if(active)setCreator(creator);},e=>{if(active)setError(e.message);});return()=>{active=false;};},[platform,connection?.accountId]);
 useEffect(()=>{if(platform!=='tiktok'||media?.kind!=='video')return;let active=true;setTiktok(previous=>({...previous,durationSec:0,consent:false}));void videoDuration(media.url).then(durationSec=>{if(active)setTiktok(previous=>({...previous,durationSec}));},e=>{if(active)setError(e.message);});return()=>{active=false;};},[platform,media?.url,creator?.username]);
 function acceptResult(result:SocialDelivery){
  if(!isPublished(result)){if(result.status==='failed'||result.status==='unknown'){setError(result.error||'Проверьте статус видео в TikTok');setProcessing(null);}else{setProcessing(result);setError('');if(!pendingDraftSaved.current&&!posts.some(item=>item.id===post.id)){pendingDraftSaved.current=true;const snapshot=result.snapshot;const file=snapshot?.media||sentMedia;addPost({...post,title:snapshot?.title||post.title,body:snapshot?.body??text,status:'draft',platforms:['tiktok'],media:file?{...file,format:file.format||'mp4'}:undefined});}}return;}
  const snapshot=result.snapshot;const publishedBody=snapshot?.body??text;const sourceMedia=snapshot?snapshot.media:sentMedia;const publishedMedia=sourceMedia?{...sourceMedia,format:sourceMedia.format||(/^data:([^;]+)/.exec(sourceMedia.url)?.[1].split('/')[1])||(sourceMedia.kind==='video'?'mp4':'jpg')}:undefined;
  recordPublication({...post,...snapshot,body:publishedBody,media:publishedMedia,platformBodies:{[result.platform]:publishedBody}},result);
  setReceipts(previous=>({...previous,[result.platform]:result}));setDone(result);setProcessing(null);setError('');notify(`Опубликовано: ${platformMeta[result.platform].name}`);
 }
 async function checkTikTok(){if(checking)return;setChecking(true);try{const {publication}=await socialRequest<{publication:SocialDelivery}>(`/publications/tiktok/${encodeURIComponent(post.id)}/check`,'POST',{});if(mounted.current)acceptResult(publication);}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'Не удалось проверить статус');}finally{if(mounted.current)setChecking(false);}}
 useEffect(()=>{if(platform!=='tiktok'||!processing)return;let active=true;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const {publication}=await socialRequest<{publication:SocialDelivery}>(`/publications/tiktok/${encodeURIComponent(post.id)}/check`,'POST',{});if(!active)return;acceptResult(publication);if(!isPublished(publication)&&publication.status==='processing')timer=setTimeout(poll,5000);}catch(e){if(active){setError(e instanceof Error?e.message:'Не удалось проверить статус');timer=setTimeout(poll,10000);}}};timer=setTimeout(poll,2500);return()=>{active=false;clearTimeout(timer);};},[processing?.publishId,platform]);
 async function attach(files:FileList|null){const file=files?.[0];if(!file)return;setError('');if(!['image/jpeg','image/png','image/webp','video/mp4','video/webm'].includes(file.type)||file.size>50*1024*1024){setError('Выберите изображение или видео до 50 МБ');return;}try{const url=await blobToDataURL(file);if(mounted.current){const kind=file.type.startsWith('image/')?'image':'video';setMedia({kind,url,format:file.type.split('/')[1]});setPublicKind(kind);}}catch{setError('Не удалось прочитать файл');}finally{if(input.current)input.current.value='';}}
 async function publish(){if(!canPublish){setError('Недостаточно прав для публикации');return;}if(!connection||busy||already||processing)return;setError('');if(!post.title.trim()){setError('Добавьте название публикации');return;}if(needsURL&&!publicMedia.trim()){setError('Добавьте публичную HTTPS-ссылку на медиафайл');return;}if(!text.trim()&&!sentMedia){setError('Добавьте текст или медиафайл');return;}if(!connection.capabilities.text&&!sentMedia){setError(`${platformMeta[platform].name} требует ${['youtube','tiktok'].includes(platform)?'видео':'изображение или видео'}`);return;}if(sentMedia&&!connection.capabilities[sentMedia.kind]){setError('Подключение не поддерживает этот тип файла');return;}const protection=protectBrand(text,post.title);if(!protection.allowed||protection.issues.some(i=>i.code==='unsourced-number')){setError(protection.issues[0]?.message||'Проверьте факты и правила бренда');return;}const policy=getPolicy();if(policy.requireMedia&&!sentMedia){setError('Добавьте медиа согласно правилам компании');return;}if(policy.requireApproval&&!editable&&!['approved','scheduled'].includes(post.status)){setError('Сначала согласуйте публикацию');return;}
 if(platform==='tiktok'){
  if(!creator){setError('Дождитесь настроек автора TikTok');return;}
  if(!creator.privacyLevels.includes(tiktok.privacyLevel)){setError('Выберите видимость видео');return;}
  if(!tiktok.durationSec||tiktok.durationSec>creator.maxVideoDurationSec){setError(`Выберите видео длительностью до ${creator.maxVideoDurationSec} секунд`);return;}
  if(tiktok.commercialContent&&!tiktok.brandOrganic&&!tiktok.brandedContent){setError('Укажите, чей бренд продвигается');return;}
  if(tiktok.brandedContent&&tiktok.privacyLevel==='SELF_ONLY'){setError('Платное партнёрство требует другой видимости');return;}
  if(!tiktok.consent){setError('Подтвердите передачу видео в TikTok');return;}
 }
 setBusy(true);try{const result=await publishSocial({postId:post.id,platform,title:post.title,body:text,media:sentMedia,...(platform==='youtube'?{visibility}:{}),...(platform==='tiktok'?{tiktok}:{})});acceptResult(result);}catch(e){setError(e instanceof Error?e.message:'Не удалось опубликовать');}finally{if(mounted.current)setBusy(false);}}
 const result=done||already;const previewSnapshot=processing?.snapshot||result?.snapshot;
 return <Modal title={editable?'Проверить постинг':'Опубликовать'} onClose={()=>{if(!busy)onClose();}} wide><div className="social-publish-grid"><div className="social-publish-fields">
  <label className="field">Площадка<Select aria-label="Площадка отправки" disabled={!canPublish||busy||!!done||!!processing} value={platform} onChange={value=>{setPlatform(value as Platform);setError('');setPublicMedia('');}} options={(connections.filter(c=>c.status==='connected').length?connections.filter(c=>c.status==='connected').map(c=>({value:c.platform,label:platformMeta[c.platform].name})):[{value:platform,label:platformMeta[platform].name}])}/></label>
  {connection&&<div className="social-publish-destination"><PlatformIcon platform={platform} size={32}/><div><strong>{platform==='tiktok'&&creator?creator.nickname:connection.accountName}</strong><span>{platform==='tiktok'&&creator?`@${creator.username}`:connection.accountHandle||connection.accountId}</span></div></div>}
  {loading?<div className="social-publish-loading"><LoaderCircle className="spin" size={20}/></div>:!connection?<div className="social-publish-missing"><p>Подключите площадку в настройках</p><button className="btn" onClick={()=>{onClose();closeEditor();navigate('settings','social');}}>Открыть настройки<ArrowUpRight size={14}/></button></div>:<>
  {!result&&!processing&&<>{(editable||platform==='tiktok')&&<label className="field">Текст публикации<textarea aria-label="Текст для проверки постинга" value={body} disabled={busy} onChange={e=>{setBody(e.target.value);setTiktok(previous=>({...previous,consent:false}));}} rows={5}/></label>}
  {(needsURL||connection.capabilities.requiresPublicMedia)&&<><label className="field">{platform==='threads'&&!media?'Медиафайл · необязательно':'Публичная ссылка на медиафайл'}<input aria-label="Публичная ссылка на медиафайл" type="url" value={publicMedia} disabled={busy} placeholder="https://site.ru/image.jpg" onChange={e=>setPublicMedia(e.target.value)}/></label>{(!!publicMedia||needsURL)&&<Select aria-label="Тип медиа по ссылке" value={publicKind} disabled={busy} onChange={value=>setPublicKind(value as 'image'|'video')} options={[{value:'image',label:'Изображение'},{value:'video',label:'Видео'}]}/>}<span className="social-help-copy">{platformMeta[platform].name} загружает файл по ссылке. Адрес localhost не подойдёт.</span></>}
  {!connection.capabilities.requiresPublicMedia&&(connection.capabilities.image||connection.capabilities.video)&&<><input hidden ref={input} type="file" accept={`${connection.capabilities.image?'image/png,image/jpeg,image/webp,':''}${connection.capabilities.video?'video/mp4,video/webm':''}`} aria-label="Файл для публикации" onChange={e=>void attach(e.target.files)}/><div className="social-publish-media"><button className="btn" disabled={busy} onClick={()=>input.current?.click()}><ImagePlus size={16}/>{media?'Заменить файл':'Добавить файл'}</button>{media&&<button className="icon-button" disabled={busy} aria-label="Убрать файл из отправки" onClick={()=>setMedia(undefined)}><X size={15}/></button>}</div></>}
  {platform==='youtube'&&<label className="field">Доступ к видео<Select aria-label="Доступ к видео" value={visibility} disabled={busy} onChange={setVisibility} options={[{value:'private',label:'Приватное'},{value:'unlisted',label:'По ссылке'},{value:'public',label:'Публичное'}]}/></label>}
  {platform==='tiktok'&&(creator?<TikTokControls creator={creator} value={tiktok} onChange={setTiktok} disabled={busy}/>:<span className="social-help-copy">Получаем настройки автора…</span>)}
  <button className="btn btn-primary social-publish-submit" disabled={!canPublish||busy||(platform==='tiktok'&&(!creator||!tiktok.privacyLevel||!tiktok.consent||(tiktok.commercialContent&&!tiktok.brandOrganic&&!tiktok.brandedContent)||(tiktok.brandedContent&&tiktok.privacyLevel==='SELF_ONLY')))} onClick={()=>void publish()}>{busy?<LoaderCircle className="spin" size={15}/>:<Send size={15}/>} {busy?'Отправляем…':'Опубликовать'}</button></>}
  {processing&&<div className="social-publish-success"><span><LoaderCircle className="spin" size={25}/></span><h3>TikTok обрабатывает видео</h3><p>Можно закрыть окно. Статус отправки сохранён.</p><button className="btn" disabled={checking} onClick={()=>void checkTikTok()}>{checking?'Проверяем…':'Проверить статус'}</button><button className="btn btn-primary" onClick={onClose}>Закрыть</button></div>}
  {result&&<div className="social-publish-success"><span><Check size={25}/></span><h3>{done?'Публикация отправлена':'Уже опубликовано'}</h3>{result.visibility&&<p>{privacyLabels[result.visibility]|| (result.visibility==='private'?'Приватное видео':result.visibility==='unlisted'?'Доступ по ссылке':'Публичное видео')}</p>}{result.url&&<a className="btn" href={result.url} target="_blank" rel="noreferrer">Открыть публикацию<ArrowUpRight size={16}/></a>}<button className="btn btn-primary" onClick={onClose}>Готово</button></div>}
  </>}
  {error&&<p className="social-form-error" role="alert">{error}</p>}
 </div><div className="social-publish-preview"><SocialPreview platform={platform} body={previewSnapshot?.body??text} title={previewSnapshot?.title??post.title} visual={previewSnapshot?previewSnapshot.media:sentMedia||media} brandName={brand.name}/></div></div></Modal>;
}
