import {useState} from 'react';
import {Check,Mail,LockKeyhole,LoaderCircle} from 'lucide-react';
import {Select} from './ui';
type Config={host:string;port:number;secure:boolean;user:string;password?:string;from:string;fromName:string;configured:boolean};
export default function SmtpSettings(){
 const [key,setKey]=useState(''),[unlocked,setUnlocked]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[draft,setDraft]=useState<Config>({host:'',port:465,secure:true,user:'',password:'',from:'',fromName:'LABRICA',configured:false});
 async function request(path='',method='GET',body?:unknown){const response=await fetch(`/api/auth/smtp${path}`,{method,headers:{'Content-Type':'application/json','X-Approval-Key':key},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw Error(data.error||'Не удалось сохранить');return data;}
 async function run(action:()=>Promise<void>){setBusy(true);setMessage('');try{await action();}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
 return <section className="la-panel la-config-fields smtp-settings"><div className="la-panel-heading"><h2><Mail size={19}/> Почта и коды подтверждения</h2><span className="la-status">{draft.configured?'Настроено':'Не подключено'}</span></div>{!unlocked?<form onSubmit={e=>{e.preventDefault();run(async()=>{setDraft(await request());setUnlocked(true);});}}><label className="field">Ключ управления<input required type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)}/></label><button className="btn btn-primary" disabled={busy}><LockKeyhole size={15}/>Открыть настройки SMTP</button></form>:<form onSubmit={e=>{e.preventDefault();run(async()=>{setDraft(await request('','PUT',draft));setMessage('Настройки сохранены');});}}><div className="smtp-grid"><label className="field">SMTP-сервер<input required value={draft.host} onChange={e=>setDraft({...draft,host:e.target.value})} placeholder="smtp.company.ru"/></label><label className="field">Порт<input required type="number" min={1} max={65535} value={draft.port} onChange={e=>setDraft({...draft,port:Number(e.target.value)})}/></label><label className="field">Защита соединения<Select aria-label="Защита SMTP" value={draft.secure?'tls':'starttls'} onChange={value=>setDraft({...draft,secure:value==='tls',port:value==='tls'?465:587})} options={[{value:'tls',label:'TLS'},{value:'starttls',label:'STARTTLS'}]}/></label><label className="field">Логин<input required autoComplete="off" value={draft.user} onChange={e=>setDraft({...draft,user:e.target.value})}/></label><label className="field">Пароль приложения<input type="password" autoComplete="new-password" required={!draft.configured} value={draft.password||''} onChange={e=>setDraft({...draft,password:e.target.value})} placeholder={draft.configured?'Сохранён на сервере':''}/></label><label className="field">Почта отправителя<input required type="email" value={draft.from} onChange={e=>setDraft({...draft,from:e.target.value})}/></label><label className="field">Имя отправителя<input required value={draft.fromName} onChange={e=>setDraft({...draft,fromName:e.target.value})}/></label></div><div className="smtp-actions"><button className="btn btn-primary" disabled={busy}>{busy?<LoaderCircle size={15} className="spin"/>:<Check size={15}/>}Сохранить</button><button type="button" className="btn btn-ghost" disabled={busy||!draft.configured} onClick={()=>run(async()=>{await request('/check','POST',{});setMessage('Соединение и авторизация проверены');})}>Проверить подключение</button></div></form>}{message&&<p role="status" className="smtp-message">{message}</p>}</section>;
}
