import {Select} from './ui';
import type {TikTokCreator,TikTokSettings} from './social-api';
export const emptyTikTokSettings=():TikTokSettings=>({privacyLevel:'',allowComment:false,allowDuet:false,allowStitch:false,commercialContent:false,brandOrganic:false,brandedContent:false,isAigc:false,consent:false,durationSec:0});
export const privacyLabels:Record<string,string>={PUBLIC_TO_EVERYONE:'Все',MUTUAL_FOLLOW_FRIENDS:'Друзья',FOLLOWER_OF_CREATOR:'Подписчики',SELF_ONLY:'Только я'};
export default function TikTokControls({creator,value,onChange,disabled}:{creator:TikTokCreator;value:TikTokSettings;onChange:(value:TikTokSettings)=>void;disabled:boolean}){
 const patch=(next:Partial<TikTokSettings>)=>onChange({...value,...next,consent:false});
 return <div className="tiktok-publish-options"><label className="field">Кто может смотреть<Select aria-label="Видимость TikTok" disabled={disabled} value={value.privacyLevel} onChange={privacyLevel=>patch({privacyLevel})} options={[{value:'',label:'Выберите видимость'},...creator.privacyLevels.map(option=>({value:option,label:privacyLabels[option]||option}))]}/></label><div className="tiktok-interactions">{([{key:'allowComment',label:'Комментарии',blocked:creator.commentDisabled},{key:'allowDuet',label:'Дуэты',blocked:creator.duetDisabled},{key:'allowStitch',label:'Сшивание',blocked:creator.stitchDisabled}] as const).map(item=><label key={item.key}><input type="checkbox" checked={value[item.key]&&!item.blocked} disabled={disabled||item.blocked} onChange={e=>patch({[item.key]:e.target.checked})}/>{item.label}</label>)}</div><label><input type="checkbox" checked={value.isAigc} disabled={disabled} onChange={e=>patch({isAigc:e.target.checked})}/>Создано с помощью ИИ</label><label><input type="checkbox" checked={value.commercialContent} disabled={disabled} onChange={e=>patch({commercialContent:e.target.checked,brandOrganic:false,brandedContent:false})}/>Рекламный контент</label>{value.commercialContent&&<div className="tiktok-commercial-options"><label><input type="checkbox" checked={value.brandOrganic} disabled={disabled} onChange={e=>patch({brandOrganic:e.target.checked})}/>Мой бренд</label><label><input type="checkbox" checked={value.brandedContent} disabled={disabled} onChange={e=>patch({brandedContent:e.target.checked})}/>Платное партнёрство</label>{(value.brandOrganic||value.brandedContent)&&<p className="social-help-copy">Будет отметка «{value.brandedContent?'Платное партнёрство':'Рекламный контент'}»</p>}{value.brandedContent&&value.privacyLevel==='SELF_ONLY'&&<p className="social-help-copy">Платное партнёрство нельзя публиковать с видимостью «Только я»</p>}</div>}<p className="social-help-copy">Видео до {creator.maxVideoDurationSec} сек{value.durationSec>0?` · выбрано ${Math.ceil(value.durationSec)} сек`:''}</p><label className="tiktok-consent"><input type="checkbox" checked={value.consent} disabled={disabled} onChange={e=>onChange({...value,consent:e.target.checked})}/><span>Разрешаю отправить это видео в TikTok и принимаю <a href="https://www.tiktok.com/legal/page/global/music-usage-confirmation/en" target="_blank" rel="noreferrer">условия использования музыки</a>{value.brandedContent&&<> и <a href="https://www.tiktok.com/legal/page/global/bc-policy/en" target="_blank" rel="noreferrer">правила брендированного контента</a></>}</span></label></div>;
}

export function videoDuration(url:string):Promise<number>{return new Promise((resolve,reject)=>{const video=document.createElement('video');const timer=window.setTimeout(()=>finish(new Error('Не удалось прочитать длительность видео')),15000);const finish=(result:number|Error)=>{clearTimeout(timer);video.onloadedmetadata=null;video.onerror=null;video.removeAttribute('src');video.load();result instanceof Error?reject(result):resolve(result);};video.preload='metadata';video.onloadedmetadata=()=>finish(Number.isFinite(video.duration)&&video.duration>0?video.duration:new Error('Не удалось прочитать длительность видео'));video.onerror=()=>finish(new Error('Не удалось открыть видео. Выберите файл MP4 или WebM.'));video.src=url;});}
