import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,readFile,rm,stat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createAuthHandler} from './auth-service.mjs';
const codeFrom=message=>{const match=message.text.match(/подтверждения:\s*(\d{3})\s*(\d{3})/);assert.ok(match);return match[1]+match[2];};
async function fixture(t){
 const directory=await mkdtemp(join(tmpdir(),'labrica-auth-test-'));let time=Date.now(),mail=[],reject=false;
 const handler=createAuthHandler({directory,issuerKey:'test-private-key',now:()=>time,transportFactory:options=>({verify:async()=>{assert.equal(options.requireTLS,!options.secure);if(reject)throw Error('private-password');return true;},sendMail:async message=>{if(reject)throw Error('private-password');mail.push(message);return{accepted:[message.to]};}})});
 const server=createServer(handler);await new Promise(done=>server.listen(0,'127.0.0.1',done));t.after(async()=>{server.closeAllConnections();await new Promise(done=>server.close(done));await rm(directory,{recursive:true,force:true});});
 const call=async(path,body,admin=false,headers={})=>{const response=await fetch(`http://127.0.0.1:${server.address().port}/api/auth/${path}`,{method:body===undefined?'GET':path==='smtp'?'PUT':'POST',headers:{'Content-Type':'application/json',...(admin?{'X-Approval-Key':'test-private-key'}:{}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});return{status:response.status,data:await response.json()};};
 const config={host:'smtp.example.test',port:587,secure:false,user:'mailer',password:'private-password',from:'hello@example.test',fromName:'LABRICA'};
 return{call,config,directory,mail,handler,advance:ms=>{time+=ms;},reject:()=>{reject=true;}};
}
test('SMTP admin auth, encryption, redaction and no connection claim before check',async t=>{const f=await fixture(t);assert.equal(f.handler.adminStatus().smtp.configured,false);assert.equal((await f.call('smtp')).status,401);assert.equal((await f.call('smtp',f.config)).status,401);assert.equal((await f.call('smtp',f.config,true,{Origin:'https://evil.test'})).status,403);const saved=await f.call('smtp',f.config,true);assert.equal(saved.status,200);assert.equal(saved.data.password,undefined);assert.equal((await readFile(join(f.directory,'smtp.json'),'utf8')).includes(f.config.password),false);assert.equal((await stat(join(f.directory,'smtp.json'))).mode&0o777,0o600);assert.equal((await f.call('smtp',{...f.config,password:''},true)).data.configured,true);assert.equal((await f.call('smtp/check',{},true)).data.connected,true);assert.equal(f.handler.adminStatus().smtp.status,'connected');});
test('registration does not report email sent before SMTP exists or accepts recipient',async t=>{const f=await fixture(t);assert.equal((await f.call('email/start',{email:'person@example.test'})).status,503);await f.call('smtp',f.config,true);f.reject();const failure=await f.call('email/start',{email:'person@example.test'});assert.equal(failure.status,502);assert.equal(JSON.stringify(failure).includes('private-password'),false);assert.equal(f.mail.length,0);assert.equal(f.handler.adminStatus().verificationEmails.failed,1);});
test('code validation, email-bound proof and one-time consumption',async t=>{const f=await fixture(t);await f.call('smtp',f.config,true);const start=await f.call('email/start',{email:'Person@example.test'});assert.equal(start.status,200);assert.equal(start.data.code,undefined);assert.equal(f.handler.adminStatus().verificationEmails.sent,1);const code=codeFrom(f.mail[0]);assert.equal((await f.call('email/verify',{challengeId:start.data.challengeId,code:'bad'})).status,400);const verified=await f.call('email/verify',{challengeId:start.data.challengeId,code});assert.equal(verified.status,200);assert.equal((await f.call('email/consume',{email:'other@example.test',proof:verified.data.proof})).status,400);assert.equal((await f.call('email/consume',{email:'person@example.test',proof:verified.data.proof})).data.verified,true);assert.equal((await f.call('email/consume',{email:'person@example.test',proof:verified.data.proof})).status,400);assert.equal((await f.call('email/verify',{challengeId:start.data.challengeId,code})).status,400);});
test('code expires, attempts are limited, resend invalidates previous code and rate is limited',async t=>{const f=await fixture(t);await f.call('smtp',f.config,true);const a=await f.call('email/start',{email:'a@example.test'});assert.equal((await f.call('email/start',{email:'a@example.test'})).status,429);const oldCode=codeFrom(f.mail[0]);f.advance(61000);const b=await f.call('email/start',{email:'a@example.test'});assert.equal((await f.call('email/verify',{challengeId:a.data.challengeId,code:oldCode})).status,400);for(let i=0;i<5;i++)assert.equal((await f.call('email/verify',{challengeId:b.data.challengeId,code:'bad'})).status,400);const newCode=codeFrom(f.mail[1]);assert.equal((await f.call('email/verify',{challengeId:b.data.challengeId,code:newCode})).status,400);const c=await f.call('email/start',{email:'c@example.test'});f.advance(600001);assert.equal((await f.call('email/verify',{challengeId:c.data.challengeId,code:codeFrom(f.mail[2])})).status,400);});
