const Glyph=({name}:{name:string})=><svg className="icon" aria-hidden="true"><use href={`#${name}`}/></svg>;
const Lines=()=> <div className="mock-lines"><i/><i/><i/></div>;
const Socials=()=> <div className="mock-socials"><span className="mock-telegram">↗</span><span className="mock-vk">vk</span><span className="mock-ok">ок</span></div>;
const Chart=()=> <svg className="mock-chart" viewBox="0 0 280 125"><path className="mock-chart-grid" d="M0 25H280M0 65H280M0 105H280"/><path className="mock-chart-area" d="M4 111C35 109 27 71 65 80S93 48 126 62 167 31 192 44 236 15 276 10V125H4Z"/><path className="mock-chart-line" d="M4 111C35 109 27 71 65 80S93 48 126 62 167 31 192 44 236 15 276 10"/><circle cx="276" cy="10" r="4"/></svg>;
const Creative=()=> <div className="mock-creative"><i/><i/><i/><span><Glyph name="sparkles"/></span></div>;

/** Decorative product illustrations; deliberately not live controls or account data. */
export default function PlatformMockup({step,detail=false}:{step:number;detail?:boolean}){
 let content;
 if(step===0)content=detail?<div className="mock-space"><div className="mock-space-symbol"><Glyph name="layers"/></div><h4>Ваше пространство</h4><p>Всё начинается с команды</p><div className="mock-avatars"><span>А</span><span>М</span><span>К</span><span>+</span></div><div className="mock-success"><Glyph name="check"/></div></div>:<><div className="mock-tabs"><b>Регистрация</b><span>Войти</span></div><h4>Начнём с вашего<br/>пространства</h4><div className="mock-field"><small>Ваше имя</small><i/></div><div className="mock-field"><small>Электронная почта</small><i/></div><div className="mock-action">Создать аккаунт<Glyph name="arrow"/></div></>;
 else if(step===1)content=detail?<div className="mock-brain"><svg viewBox="0 0 280 210"><path d="M140 105V35H55M140 105V35H235M140 105V177H65M140 105V177H230"/></svg><span className="mock-node node-a">Аудитория</span><span className="mock-node node-b">Продукт</span><span className="mock-node node-c">Ценности</span><span className="mock-node node-d">Тон общения</span><div className="mock-brain-core"><Glyph name="layers"/><b>Ваш бренд</b></div></div>:<><div className="mock-section-label"><Glyph name="layers"/>Brand Brain</div><h4>Знания о вашем бренде</h4>{['О компании','Аудитория','Тон общения'].map((label,i)=><div className="mock-brand-field" key={label}><span className="mock-field-dot">{String(i+1).padStart(2,'0')}</span><div><small>{label}</small><Lines/></div><Glyph name="check"/></div>)}</>;
 else if(step===2)content=detail?<div className="mock-network"><div className="mock-network-core"><img src={`${import.meta.env.BASE_URL}brand/labrica-symbol.svg`} alt=""/></div><svg viewBox="0 0 280 110"><path d="M140 0V35M50 90V50Q50 35 65 35H215Q230 35 230 50V90M140 35V90"/></svg><Socials/><p>Один контент — ваши площадки</p></div>:<><div className="mock-section-label"><Glyph name="plus"/>Социальные сети</div><h4>Будьте там,<br/>где ваша аудитория</h4>{['Telegram','ВКонтакте','Одноклассники'].map((name,i)=><div className="mock-social-row" key={name}><span className={['mock-telegram','mock-vk','mock-ok'][i]}>{['↗','vk','ок'][i]}</span><b>{name}</b><Glyph name="check"/></div>)}</>;
 else if(step===3)content=detail?<div className="mock-post"><div className="mock-post-author"><span/><b>Ваш бренд</b><small>•••</small></div><Creative/><Lines/><div className="mock-post-bottom"><span>♡</span><span>↗</span><span>⋯</span></div></div>:<><div className="mock-section-label"><Glyph name="pen"/>Студия</div><h4>Новая публикация</h4><div className="mock-tabs"><b>Текст</b><span>Изображение</span><span>Видео</span></div><div className="mock-editor"><Lines/><Lines/><span className="mock-caret"/></div><div className="mock-action"><Glyph name="sparkles"/>Создать с AI</div></>;
 else if(step===4)content=detail?<div className="mock-schedule"><span className="mock-clock"><Glyph name="calendar"/></span><h4>Запланировать</h4><Socials/><div className="mock-date"><span>27 сентября</span><b>12:30</b></div><div className="mock-action">В контент-план<Glyph name="arrow"/></div></div>:<><div className="mock-section-label"><Glyph name="calendar"/>Контент-план</div><div className="mock-month"><h4>Сентябрь</h4><span>‹ &nbsp; ›</span></div><div className="mock-calendar">{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(day=><small key={day}>{day}</small>)}{Array.from({length:21},(_,i)=><span className={i===19?'selected':''} key={i}>{i+8}{[2,5,8,12,15,19].includes(i)&&<i/>}</span>)}</div></>;
 else content=detail?<div className="mock-insights"><div><span><Glyph name="analytics"/>Охваты</span><Chart/></div><div><span><Glyph name="people"/>Взаимодействия</span><Chart/></div></div>:<><div className="mock-section-label"><Glyph name="analytics"/>Аналитика</div><h4>Видеть результат</h4><div className="mock-tabs"><b>Охваты</b><span>Взаимодействия</span></div><Chart/><div className="mock-chart-labels"><span>Пн</span><span>Ср</span><span>Пт</span><span>Вс</span></div></>;
 return <div className={`platform-mockup mock-step-${step}${detail?' mock-detail':''}`}>{content}</div>;
}
