import { productName } from './runtime';
import { useMemo, useState } from 'react';
import { ArrowDown, ArrowDownToLine, ArrowRight, ArrowUp, ArrowUpRight, BarChart3, Clock3, Info, Search, Sparkles } from 'lucide-react';
import { formatNumber, platformMeta, shortNumber, TODAY } from './model';
import type { Platform, Post } from './model';
import { useWorkspace } from './store';
import { PlatformIcon, Select } from './ui';
import './planning.css';
import './planning-v3.css';

type Total = {views: number; clicks: number; registrations: number; reactions: number; comments: number; shares: number};
type Ratios = {ctr: number | null; cvr: number | null; er: number | null; perThousand: number | null; perPost: number | null};
type SortKey = 'views' | 'clicks' | 'registrations' | 'ctr' | 'cvr' | 'er' | 'perThousand';
type GroupBy = 'format' | 'topic' | 'channel';
type Group = {name: string; platform?: Platform; posts: Post[]; total: Total; rates: Ratios};
type ComparisonMetric = 'perPost' | 'perThousand' | 'ctr' | 'cvr';
const platforms = Object.keys(platformMeta) as Platform[];
const sum = (posts: Post[]): Total => posts.reduce((result, post) => ({views: result.views + post.views, clicks: result.clicks + post.clicks, registrations: result.registrations + post.registrations, reactions: result.reactions + post.reactions, comments: result.comments + post.comments, shares: result.shares + post.shares}), {views: 0, clicks: 0, registrations: 0, reactions: 0, comments: 0, shares: 0});
const ratio = (value: number, total: number, multiplier = 100): number | null => total > 0 ? value / total * multiplier : null;
const number = (value: number | null, digits = 1) => value === null ? '—' : value.toLocaleString('ru-RU', {maximumFractionDigits: digits});
const percent = (value: number | null) => value === null ? '—' : `${number(value, 2)}%`;
const rates = (total: Total, count: number): Ratios => ({ctr: ratio(total.clicks, total.views), cvr: ratio(total.registrations, total.clicks), er: ratio(total.reactions + total.comments + total.shares, total.views), perThousand: ratio(total.registrations, total.views, 1000), perPost: count ? total.registrations / count : null});
const dateForOffset = (offset: number) => {const date = new Date(`${TODAY}T12:00:00`); date.setDate(date.getDate() + offset); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;};
const metricLabels: Record<ComparisonMetric, string> = {perPost: 'Регистраций на пост', perThousand: 'Регистраций на 1 000 просмотров', ctr: 'CTR', cvr: 'Конверсия в регистрацию'};
const metricValue = (value: number | null, metric: ComparisonMetric) => metric === 'ctr' || metric === 'cvr' ? percent(value) : number(value);
const weekdays = ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'];
const weekdayNames = ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'];
const weekdayOf = (post: Post) => (new Date(`${post.date}T12:00:00`).getDay() + 6) % 7;
const hourOf = (post: Post) => Number(post.time.split(':')[0]);
function groupsFor(posts: Post[], group: GroupBy): Group[] {
  const groups = new Map<string, {name: string; platform?: Platform; posts: Post[]}>();
  posts.forEach(post => {
    const singlePlatform = post.platforms.length === 1 ? post.platforms[0] : undefined;
    const key = group === 'channel' ? singlePlatform || 'combined' : post[group];
    if (!groups.has(key)) groups.set(key, {name: group === 'channel' ? singlePlatform ? platformMeta[singlePlatform].name : 'Кросспосты · общий результат' : key, platform: group === 'channel' ? singlePlatform : undefined, posts: []});
    groups.get(key)!.posts.push(post);
  });
  return [...groups.values()].map(group => {const total = sum(group.posts); return {...group, total, rates: rates(total, group.posts.length)};});
}

export default function Analytics() {
  const {posts, openEditor, notify, section} = useWorkspace();
  const [period, setPeriod] = useState('30');
  const [platform, setPlatform] = useState<Platform | 'all'>('all');
  const start = dateForOffset(-Number(period) + 1);
  const inPeriod = useMemo(() => posts.filter(post => post.status === 'published' && post.date >= start && post.date <= TODAY), [posts, start]);
  const filtered = useMemo(() => inPeriod.filter(post => platform === 'all' || post.platforms.length === 1 && post.platforms[0] === platform), [inPeriod, platform]);
  const total = sum(filtered);
  const rate = rates(total, filtered.length);
  const tab = section === 'audience' || section === 'timing' ? section : 'effectiveness';
  function exportCSV() {
    const rows = [['Дата', 'Время', 'Публикация', 'Площадка', 'Тема', 'Формат', 'Просмотры', 'Переходы', 'Регистрации', 'Реакции', 'Комментарии', 'Репосты', 'CTR %', 'Конверсия в регистрацию %', 'ER %', 'Регистраций на 1000 просмотров'], ...filtered.map(post => {const rate = rates(post, 1); return [post.date, post.time, post.title, post.platforms.map(channel => platformMeta[channel].name).join(', '), post.topic, post.format, post.views, post.clicks, post.registrations, post.reactions, post.comments, post.shares, rate.ctr?.toFixed(3) || '', rate.cvr?.toFixed(3) || '', rate.er?.toFixed(3) || '', rate.perThousand?.toFixed(3) || ''];})];
    const csv = '\uFEFF' + rows.map(row => row.map(value => `"${String(value).replace(/^[=+@-]/, "'$&").replaceAll('"', '""')}"`).join(';')).join('\r\n');
    const url = URL.createObjectURL(new Blob([csv], {type: 'text/csv;charset=utf-8;'}));
    const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${productName.toLowerCase()}-analytics-${start}-${TODAY}.csv`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
    notify('Отчёт с показателями публикаций скачан');
  }
  return <div className="planning-page report-page">
    <div className="page-heading"><h1 className="page-title">Аналитика</h1><button className="btn btn-ghost report-export" onClick={exportCSV}><ArrowDownToLine size={16} />Экспорт</button></div>
    <div className="report-filter-bar"><span className="report-period-label">{new Date(`${start}T12:00:00`).toLocaleDateString('ru-RU', {day: 'numeric', month: 'short'})} — {new Date(`${TODAY}T12:00:00`).toLocaleDateString('ru-RU', {day: 'numeric', month: 'short'})}<i />{filtered.length} публикаций</span><div><Select aria-label="Период аналитики" value={period} onChange={setPeriod} options={[{value: '7', label: '7 дней'}, {value: '14', label: '14 дней'}, {value: '30', label: '30 дней'}, {value: '90', label: '90 дней'}]} /><Select aria-label="Площадка аналитики" value={platform} onChange={value => setPlatform(value as Platform | 'all')} options={[{value: 'all', label: 'Все площадки'}, ...platforms.map(channel => ({value: channel, label: platformMeta[channel].name}))]} /></div></div>
    {platform !== 'all' && inPeriod.some(post => post.platforms.length > 1 && post.platforms.includes(platform)) && <div className="report-data-note"><Info size={15} />Общие показатели кросспостов не распределены по площадкам и исключены из этого фильтра.</div>}
    {!filtered.length ? <section className="report-card report-empty"><BarChart3 size={35} /><h2>Пока нет данных</h2><p>За выбранный период на этой площадке нет публикаций.</p><button className="btn btn-primary" onClick={() => {setPeriod('30'); setPlatform('all');}}>Сбросить фильтры</button></section> : tab === 'effectiveness' ? <><Comparisons posts={filtered} rate={rate} /><PerformanceTable posts={filtered} openEditor={openEditor} /></> : tab === 'audience' ? <FunnelReport posts={filtered} total={total} rate={rate} openEditor={openEditor} /> : <TimingReport posts={filtered} openEditor={openEditor} />}
    {!!filtered.length && <details className="report-definitions"><summary><Info size={14} />Как считаются показатели</summary><div><p><strong>CTR</strong> — переходы / просмотры. <strong>CVR</strong> — регистрации / переходы. <strong>ER</strong> — реакции, комментарии и репосты / просмотры.</p><p>Регистрации на 1 000 просмотров позволяют сравнивать материалы с разным охватом. Показатели группы рассчитываются по сумме событий; среднее на пост — по числу публикаций. Время — Стамбул, UTC+3.</p><p>Общие результаты поста на нескольких площадках учитываются один раз. Малые выборки не позволяют установить устойчивую закономерность.</p></div></details>}
  </div>;
}

function Comparisons({posts, rate}: {posts: Post[]; rate: Ratios}) {
  const [by, setBy] = useState<GroupBy>('format');
  const [metric, setMetric] = useState<ComparisonMetric>('perPost');
  const groups = groupsFor(posts, by).sort((a, b) => (b.rates[metric] ?? -1) - (a.rates[metric] ?? -1));
  const maximum = Math.max(...groups.map(group => group.rates[metric] || 0), 1);
  const best = groups[0];
  return <section className="report-card report-comparison-card"><div className="report-card-heading"><h2>Что приносит результат</h2><div className="report-segmented" role="group" aria-label="Сравнить результаты"><button className={by === 'format' ? 'active' : ''} aria-pressed={by === 'format'} onClick={() => setBy('format')}>Форматы</button><button className={by === 'topic' ? 'active' : ''} aria-pressed={by === 'topic'} onClick={() => setBy('topic')}>Темы</button><button className={by === 'channel' ? 'active' : ''} aria-pressed={by === 'channel'} onClick={() => setBy('channel')}>Площадки</button></div></div><div className="report-comparison-body"><div className="report-benchmark"><span>Эффективность контента</span><strong>{number(rate.perThousand, 2)}</strong><p>регистраций на 1 000 просмотров</p><div><span>CTR <strong>{percent(rate.ctr)}</strong></span><span>CVR <strong>{percent(rate.cvr)}</strong></span></div></div><div className="report-group-chart"><div className="report-group-chart-head"><Select aria-label="Показатель сравнения" value={metric} onChange={value => setMetric(value as ComparisonMetric)} options={Object.entries(metricLabels).map(([value, label]) => ({value, label}))} /><span>Публикаций</span></div>{groups.map((group, index) => <div className="report-group-row" key={group.name}><div className="report-group-label">{group.platform && <PlatformIcon platform={group.platform} size={23} />}<strong>{group.name}</strong><span title={group.posts.length < 3 ? 'Малая выборка: меньше 3 публикаций' : `${group.posts.length} публикаций в сравнении`}>{group.posts.length}<i className={group.posts.length < 3 ? 'small-sample' : ''} /></span></div><div className="report-group-bar-row"><div className="report-group-track"><span className={index === 0 ? 'leading' : ''} style={{width: `${(group.rates[metric] || 0) / maximum * 100}%`}} /></div><strong>{metricValue(group.rates[metric], metric)}</strong></div></div>)}</div></div><div className="report-observation"><Sparkles size={16} /><span>{best ? <><strong>{best.name}</strong> — {metricValue(best.rates[metric], metric)} {metric === 'perPost' ? 'регистраций на публикацию' : metric === 'perThousand' ? 'регистраций на 1 000 просмотров' : metric === 'ctr' ? 'CTR' : 'конверсия в регистрацию'} в этой выборке. Основание: {best.posts.length} публикаций.</> : 'Недостаточно данных для сравнения.'}</span></div></section>;
}

function PerformanceTable({posts, openEditor}: {posts: Post[]; openEditor: (post: Post) => void}) {
  const [sort, setSort] = useState<SortKey>('perThousand');
  const [direction, setDirection] = useState<'asc' | 'desc'>('desc');
  const [query, setQuery] = useState('');
  const rows = posts.filter(post => post.title.toLowerCase().includes(query.toLowerCase())).map(post => ({post, rate: rates(post, 1)})).sort((a, b) => {const av = sort === 'views' || sort === 'clicks' || sort === 'registrations' ? a.post[sort] : a.rate[sort]; const bv = sort === 'views' || sort === 'clicks' || sort === 'registrations' ? b.post[sort] : b.rate[sort]; return ((av ?? -1) - (bv ?? -1)) * (direction === 'asc' ? 1 : -1);});
  const columns: {key: SortKey; title: string; description: string}[] = [{key: 'views', title: 'Просмотры', description: 'Количество просмотров публикации'}, {key: 'ctr', title: 'CTR', description: 'Переходы / просмотры × 100%'}, {key: 'cvr', title: 'CVR', description: 'Регистрации / переходы × 100%'}, {key: 'er', title: 'ER', description: 'Реакции + комментарии + репосты / просмотры × 100%'}, {key: 'perThousand', title: 'На 1 000', description: 'Регистрации на 1 000 просмотров'}, {key: 'registrations', title: 'Регистрации', description: 'Количество регистраций'}];
  return <section className="report-card report-performance"><div className="report-card-heading"><h2>Эффективность публикаций <span className="report-count">{rows.length}</span></h2><label className="report-search"><Search size={15} /><input aria-label="Найти публикацию в аналитике" value={query} onChange={event => setQuery(event.target.value)} placeholder="Найти публикацию" /></label></div><div className="report-table-scroll"><table className="report-table"><thead><tr><th>Публикация</th>{columns.map(column => <th key={column.key} aria-sort={sort === column.key ? direction === 'asc' ? 'ascending' : 'descending' : 'none'}><button title={column.description} onClick={() => {if (sort === column.key) setDirection(direction === 'asc' ? 'desc' : 'asc'); else {setSort(column.key); setDirection('desc');}}}>{column.title}{sort === column.key ? direction === 'desc' ? <ArrowDown size={12} /> : <ArrowUp size={12} /> : <span className="report-sort-placeholder" />}</button></th>)}</tr></thead><tbody>{rows.map(({post, rate}) => <tr key={post.id}><td><button className="report-post-link" onClick={() => openEditor(post)}><PlatformIcon platform={post.platforms[0]} size={31} /><span><strong>{post.title}</strong><small>{post.format} · {new Date(`${post.date}T12:00:00`).toLocaleDateString('ru-RU', {day: 'numeric', month: 'short'})}{post.platforms.length > 1 ? ` · ${post.platforms.length} площадки` : ''}</small></span><ArrowUpRight size={14} /></button></td><td>{shortNumber(post.views)}</td><td>{percent(rate.ctr)}</td><td>{percent(rate.cvr)}</td><td>{percent(rate.er)}</td><td><span className={sort === 'perThousand' ? 'report-highlight-number' : ''}>{number(rate.perThousand, 2)}</span></td><td><strong>{formatNumber(post.registrations)}</strong></td></tr>)}</tbody></table></div>{!rows.length && <p className="report-no-results">Публикаций с таким названием нет</p>}</section>;
}

function FunnelReport({posts, total, rate, openEditor}: {posts: Post[]; total: Total; rate: Ratios; openEditor: (post: Post) => void}) {
  const groups = groupsFor(posts, 'channel').sort((a, b) => (b.rates.perThousand || 0) - (a.rates.perThousand || 0));
  const noClick = Math.max(total.views - total.clicks, 0);
  const noRegistration = Math.max(total.clicks - total.registrations, 0);
  const opportunities = posts.filter(post => post.views >= total.views / posts.length / 2 && (ratio(post.clicks, post.views) || 0) < (rate.ctr || 0)).sort((a, b) => b.views - a.views).slice(0, 3);
  return <>
    <section className="report-card report-funnel-card"><div className="report-card-heading"><h2>От просмотра до регистрации</h2><span className="report-quiet">{posts.length} публикаций</span></div><div className="report-funnel-flow"><div className="report-funnel-stage stage-dark"><span>Просмотры</span><strong>{formatNumber(total.views)}</strong><small>100% начала воронки</small></div><div className="report-flow-link"><strong>{percent(rate.ctr)}</strong><ArrowRight size={22} /></div><div className="report-funnel-stage stage-blue"><span>Переходы</span><strong>{formatNumber(total.clicks)}</strong><small>{percent(rate.ctr)} от просмотров</small></div><div className="report-flow-link"><strong>{percent(rate.cvr)}</strong><ArrowRight size={22} /></div><div className="report-funnel-stage stage-lime"><span>Регистрации</span><strong>{formatNumber(total.registrations)}</strong><small>{percent(ratio(total.registrations, total.views))} от просмотров</small></div></div><div className="report-dropouts"><div><span>Просмотры без перехода</span><strong>{formatNumber(noClick)}<small>{percent(ratio(noClick, total.views))}</small></strong></div><div><span>Переходы без регистрации</span><strong>{formatNumber(noRegistration)}<small>{percent(ratio(noRegistration, total.clicks))}</small></strong></div><p><Info size={16} />{noRegistration ? 'Проверьте, совпадает ли обещание поста с содержанием целевой страницы. Эти данные показывают потери между событиями, но не их причину.' : 'Сравнивайте каждый шаг отдельно: высокий охват сам по себе не означает новых регистраций.'}</p></div></section>
    <section className="report-card"><div className="report-card-heading"><h2>Конверсия по площадкам</h2><span className="report-quiet">Взвешенные показатели</span></div><div className="report-table-scroll"><table className="report-table report-channel-funnel"><thead><tr><th>Площадка</th><th>Постов</th><th>Просмотры</th><th>CTR</th><th>Переходы</th><th>CVR</th><th>Регистрации</th></tr></thead><tbody>{groups.map(group => <tr key={group.name}><td><span className="report-channel-name">{group.platform && <PlatformIcon platform={group.platform} size={29} />}<strong>{group.name}</strong></span></td><td>{group.posts.length}</td><td>{shortNumber(group.total.views)}</td><td>{percent(group.rates.ctr)}</td><td>{formatNumber(group.total.clicks)}</td><td>{percent(group.rates.cvr)}</td><td><span className="report-highlight-number">{formatNumber(group.total.registrations)}</span></td></tr>)}</tbody></table></div></section>
    {!!opportunities.length && <section className="report-card report-opportunities"><div className="report-card-heading"><h2>Есть охват — стоит проверить переходы</h2><span className="report-quiet">CTR ниже среднего {percent(rate.ctr)}</span></div>{opportunities.map(post => <button className="report-opportunity" key={post.id} onClick={() => openEditor(post)}><PlatformIcon platform={post.platforms[0]} size={30} /><span><strong>{post.title}</strong><small>{formatNumber(post.views)} просмотров</small></span><span className="report-opportunity-ctr">{percent(ratio(post.clicks, post.views))}<small>CTR</small></span><ArrowUpRight size={17} /></button>)}</section>}
  </>;
}

function TimingReport({posts, openEditor}: {posts: Post[]; openEditor: (post: Post) => void}) {
  const [metric, setMetric] = useState<ComparisonMetric>('perPost');
  const [selected, setSelected] = useState<{day: number; hour: number} | null>(null);
  const hourGroups = [0, 4, 8, 12, 16, 20];
  const cells = weekdays.flatMap((_, day) => hourGroups.map(hour => {const samples = posts.filter(post => weekdayOf(post) === day && hourOf(post) >= hour && hourOf(post) < hour + 4); return {day, hour, posts: samples, rate: rates(sum(samples), samples.length)};}));
  const maximum = Math.max(...cells.map(cell => cell.rate[metric] || 0), 1);
  const filled = cells.filter(cell => cell.posts.length);
  const hoursCovered = new Set(posts.map(post => Math.floor(hourOf(post) / 4))).size;
  const days = weekdayNames.map((name, day) => {const samples = posts.filter(post => weekdayOf(post) === day); return {name, day, count: samples.length, rate: rates(sum(samples), samples.length)};}).sort((a, b) => (b.rate[metric] ?? -1) - (a.rate[metric] ?? -1));
  const selectedCell = selected ? cells.find(cell => cell.day === selected.day && cell.hour === selected.hour) : undefined;
  const strongest = [...filled].sort((a, b) => (b.rate[metric] || 0) - (a.rate[metric] || 0))[0];
  const hourLabel = (hour: number) => `${String(hour).padStart(2, '0')}:00–${String(hour + 3).padStart(2, '0')}:59`;
  return <>
    <section className="report-card report-time-card"><div className="report-card-heading"><h2>Результат по времени выхода</h2><Select aria-label="Показатель времени выхода" value={metric} onChange={value => setMetric(value as ComparisonMetric)} options={[{value: 'perPost', label: 'Регистраций на пост'}, {value: 'perThousand', label: 'На 1 000 просмотров'}, {value: 'ctr', label: 'CTR'}]} /></div><div className="report-heatmap-scroll"><div className="report-heatmap"><span className="report-heatmap-corner">UTC+3</span>{hourGroups.map(hour => <span className="report-hour-label" key={hour}>{String(hour).padStart(2, '0')}–{String(hour + 3).padStart(2, '0')}</span>)}{weekdays.map((day, dayIndex) => <div className="report-heatmap-row" key={day}><span className="report-day-label">{day}</span>{cells.filter(cell => cell.day === dayIndex).map(cell => {const intensity = (cell.rate[metric] || 0) / maximum; return <button key={cell.hour} className={`report-heat-cell${cell.posts.length ? ' has-samples' : ''}${selected?.day === cell.day && selected.hour === cell.hour ? ' selected' : ''}`} style={cell.posts.length ? {background: `rgba(54, 124, 250, ${.12 + intensity * .88})`, color: intensity > .45 ? 'white' : '#263b60'} : undefined} aria-label={`${weekdayNames[cell.day]}, ${hourLabel(cell.hour)}: ${cell.posts.length} публикаций${cell.posts.length ? `, ${metricValue(cell.rate[metric], metric)}` : ''}`} onClick={() => setSelected({day: cell.day, hour: cell.hour})}><strong>{cell.posts.length ? metricValue(cell.rate[metric], metric) : '—'}</strong>{cell.posts.length > 0 && <small>n = {cell.posts.length}</small>}</button>;})}</div>)}</div></div><div className="report-heatmap-legend"><span>Число в ячейке — {metricLabels[metric].toLowerCase()}</span><div><span>Меньше</span><i /><span>Больше</span></div></div>{hoursCovered < 2 && <div className="report-data-note report-timing-warning"><Info size={16} /><span>Публикации выходили в одном временном интервале. Данных для сравнения разных часов пока нет.</span></div>}{hoursCovered >= 2 && filled.some(cell => cell.posts.length < 3) && <div className="report-data-note report-timing-warning"><Info size={16} /><span>В части интервалов меньше 3 публикаций. Используйте результат как гипотезу для проверки.</span></div>}</section>
    {selectedCell && <section className="report-card report-time-details"><div className="report-card-heading"><h2>{weekdayNames[selectedCell.day]} · {hourLabel(selectedCell.hour)}</h2><button className="report-clear-selection" onClick={() => setSelected(null)}>Скрыть</button></div>{selectedCell.posts.length ? <><div className="report-time-selection-summary"><strong>{metricValue(selectedCell.rate[metric], metric)}</strong><span>{metricLabels[metric].toLowerCase()} · {selectedCell.posts.length} публикаций</span></div>{selectedCell.posts.map(post => <button className="report-time-post" key={post.id} onClick={() => openEditor(post)}><PlatformIcon platform={post.platforms[0]} size={27} /><span>{post.title}</span><small>{new Date(`${post.date}T12:00:00`).toLocaleDateString('ru-RU', {day: 'numeric', month: 'short'})} · {post.time}</small><strong>{formatNumber(post.registrations)}</strong><ArrowUpRight size={15} /></button>)}</> : <p className="report-no-results">В это время публикаций не было. Нулевой результат не означает, что интервал неэффективен.</p>}</section>}
    <div className="report-timing-bottom"><section className="report-card"><div className="report-card-heading"><h2>По дням недели</h2><span className="report-quiet">{metric === 'perPost' ? 'Регистраций / пост' : metric === 'perThousand' ? 'На 1 000 просмотров' : 'CTR'}</span></div>{days.map(day => <div className="report-weekday-row" key={day.day}><span>{day.name}</span><small>{day.count} постов</small><div><i style={{width: `${(day.rate[metric] || 0) / Math.max(...days.map(item => item.rate[metric] || 0), 1) * 100}%`}} /></div><strong>{metricValue(day.rate[metric], metric)}</strong></div>)}</section><section className="report-card report-timing-insight"><span className="report-insight-icon"><Clock3 size={23} /></span><h2>{hoursCovered < 2 ? 'Проверьте другой интервал' : 'Лучший интервал в выборке'}</h2>{hoursCovered < 2 ? <p>Сравните несколько сопоставимых постов в другом интервале.</p> : strongest && <><strong className="report-best-time">{weekdays[strongest.day]} · {hourLabel(strongest.hour)}</strong><p>{metricValue(strongest.rate[metric], metric)} — {metricLabels[metric].toLowerCase()}. В основе {strongest.posts.length} публикаций; это наблюдение, а не подтверждённое лучшее время.</p></>}<div className="report-sample-summary"><span>Публикаций<strong>{posts.length}</strong></span><span>Интервалов<strong>{hoursCovered} / 6</strong></span></div></section></div>
  </>;
}
