import { useEffect, useRef, useState } from 'react';
import { Download, File, FileText, Film, Image, Loader2, Plus, Search, Trash2, Type, Upload, X } from 'lucide-react';
import { Modal, Select } from './ui';
import { useWorkspace } from './store';
import { workspaceKey } from './runtime';
import { assetKindLabels, deleteAsset, extractLocalText, formatBytes, getAssetBlob, getBrain, listAssets, saveAsset } from './brain-data';
import type { AssetKind, LibraryAsset } from './brain-data';
import './asset-library.css';

function AssetIcon({kind, size = 24}: {kind: AssetKind; size?: number}) {const Icon = kind === 'image' || kind === 'logo' ? Image : kind === 'video' ? Film : kind === 'font' ? Type : kind === 'document' ? FileText : File;return <Icon size={size}/>;}
function useAssets() {
  const [assets, setAssets] = useState<LibraryAsset[]>([]);const [loading, setLoading] = useState(true);const [error, setError] = useState('');
  useEffect(() => {let active = true;const refresh = async () => {try {const next = await listAssets();if (active) {setAssets(next);setError('');}} catch (failure) {if (active) setError(failure instanceof Error ? failure.message : 'Не удалось открыть библиотеку.');}finally {if (active) setLoading(false);}};void refresh();const update = (event: Event) => {const scope = (event as CustomEvent<{workspace?: string}>).detail?.workspace;if (!scope || scope === workspaceKey('assets')) void refresh();};window.addEventListener('asset-library-change', update);return () => {active = false;window.removeEventListener('asset-library-change', update);};}, []);
  return {assets, loading, error};
}
function useAssetImages(assets: LibraryAsset[]) {
  const [urls, setUrls] = useState<Record<string, string>>({});
  const ids = assets.filter(asset => asset.kind === 'image' || asset.kind === 'logo').map(asset => asset.id).join('|');
  useEffect(() => {let cancelled = false;const created: string[] = [];const values: Record<string, string> = {};void Promise.all(ids.split('|').filter(Boolean).map(async id => {try {const blob = await getAssetBlob(id);if (!blob || cancelled) return;const url = URL.createObjectURL(blob);created.push(url);values[id] = url;} catch {/* Keep the file icon if a thumbnail is unavailable. */}})).then(() => {if (!cancelled) setUrls(values);});return () => {cancelled = true;created.forEach(url => URL.revokeObjectURL(url));};}, [ids]);
  return urls;
}
function AssetCard({asset, url, onClick, selected = false}: {asset: LibraryAsset; url?: string; onClick: () => void; selected?: boolean}) {return <button className={`asset-card asset-kind-${asset.kind} ${selected ? 'is-selected' : ''}`} onClick={onClick}><span className="asset-card-preview">{url ? <img src={url} alt=""/> : asset.kind === 'font' ? <span className="asset-font-sample">Aa</span> : <AssetIcon kind={asset.kind} size={33}/>}<span className="asset-kind-badge">{assetKindLabels[asset.kind]}</span></span><span className="asset-card-copy"><strong title={asset.name}>{asset.name}</strong><span>{formatBytes(asset.size)}<span>·</span>{new Date(asset.createdAt).toLocaleDateString('ru-RU', {day: 'numeric', month: 'short'})}</span></span></button>;}

export default function AssetLibrary() {
  const {section, notify} = useWorkspace();
  const {assets, loading, error} = useAssets();const urls = useAssetImages(assets);
  const [search, setSearch] = useState('');const [kind, setKind] = useState('all');const [uploadOpen, setUploadOpen] = useState(false);const [selected, setSelected] = useState<LibraryAsset | null>(null);const [dragging, setDragging] = useState(false);const [dropped, setDropped] = useState<File[]>([]);const dragCounter = useRef(0);
  const sectionKinds: AssetKind[] | null = section === 'images' ? ['image', 'logo'] : section === 'videos' ? ['video'] : section === 'brand' ? ['logo', 'font'] : null;
  const filtered = assets.filter(asset => (!sectionKinds || sectionKinds.includes(asset.kind)) && (kind === 'all' || asset.kind === kind) && asset.name.toLocaleLowerCase('ru-RU').includes(search.toLocaleLowerCase('ru-RU')));
  return <div className={`asset-library-page ${dragging ? 'is-dragging' : ''}`} onDragEnter={event => {if (event.dataTransfer.types.includes('Files')) {event.preventDefault();dragCounter.current += 1;setDragging(true);}}} onDragOver={event => {if (event.dataTransfer.types.includes('Files')) event.preventDefault();}} onDragLeave={event => {event.preventDefault();dragCounter.current -= 1;if (dragCounter.current <= 0) {dragCounter.current = 0;setDragging(false);}}} onDrop={event => {event.preventDefault();dragCounter.current = 0;setDragging(false);const files = Array.from(event.dataTransfer.files);if (files.length) {setDropped(files);setUploadOpen(true);}}}>
    <div className="page-heading"><h1 className="page-title">Библиотека <span className="asset-total">{assets.length}</span></h1><button className="btn btn-primary" onClick={() => {setDropped([]);setUploadOpen(true);}}><Plus size={17}/> Загрузить</button></div>
    <div className="asset-toolbar"><label className="asset-search"><Search size={17}/><input aria-label="Найти файл" placeholder="Найти файл" value={search} onChange={event => setSearch(event.target.value)}/>{search && <button aria-label="Очистить поиск файлов" onClick={() => setSearch('')}><X size={14}/></button>}</label><Select aria-label="Тип файлов" value={kind} onChange={setKind} options={[{value: 'all', label: 'Все типы'}, ...Object.entries(assetKindLabels).map(([value, label]) => ({value, label}))]}/></div>
    {loading ? <div className="asset-empty panel" role="status"><Loader2 className="asset-spin" size={28}/><p>Открываем библиотеку</p></div> : error ? <div className="asset-empty panel" role="alert"><File size={30}/><h2>Библиотека недоступна</h2><p>{error}</p></div> : filtered.length ? <div className="asset-grid">{filtered.map(asset => <AssetCard key={asset.id} asset={asset} url={urls[asset.id]} onClick={() => setSelected(asset)}/>)}</div> : <div className="asset-empty panel"><span className="asset-empty-icon"><Upload size={30}/></span><h2>{assets.length ? 'Файлы не найдены' : 'Всё, из чего складывается ваш бренд'}</h2><p>{assets.length ? 'Измените запрос или тип файла.' : 'Логотипы, фотографии, видео, шрифты и документы.'}</p>{assets.length ? <button className="btn" onClick={() => {setSearch('');setKind('all');}}>Сбросить фильтры</button> : <button className="btn" onClick={() => {setDropped([]);setUploadOpen(true);}}>Загрузить первые файлы</button>}</div>}
    {!!assets.length && <div className="asset-library-footer"><span>{filtered.length} файлов · {formatBytes(filtered.reduce((sum, asset) => sum + asset.size, 0))}</span><span>Можно перетащить файлы сюда</span></div>}
    {dragging && <div className="asset-drop-overlay"><Upload size={38}/><strong>Отпустите файлы, чтобы загрузить</strong></div>}
    {uploadOpen && <UploadAssets files={dropped} onClose={() => {setUploadOpen(false);setDropped([]);}} onDone={count => {setUploadOpen(false);setDropped([]);notify(`Загружено файлов: ${count}`);}}/>}
    {selected && <AssetDetail asset={selected} onClose={() => setSelected(null)} onDeleted={() => {setSelected(null);notify('Файл удалён из библиотеки');}}/>}
  </div>;
}

function UploadAssets({files: initial, onClose, onDone}: {files: File[]; onClose: () => void; onDone: (count: number) => void}) {
  const [files, setFiles] = useState(initial);const [kind, setKind] = useState('auto');const [busy, setBusy] = useState(false);const [completed, setCompleted] = useState(0);const [error, setError] = useState('');const fileRef = useRef<HTMLInputElement>(null);
  const upload = async () => {if (!files.length) return;setBusy(true);setError('');let done = 0;for (const file of files) {try {await saveAsset(file, kind === 'auto' ? undefined : kind as AssetKind);done += 1;setCompleted(done);} catch (failure) {setError(failure instanceof Error ? failure.message : 'Недостаточно места для загрузки.');setFiles(files.slice(done));setBusy(false);return;}}setBusy(false);onDone(done);};
  return <Modal title="Загрузить файлы" onClose={() => {if (!busy) onClose();}}><div className="asset-upload-form"><input ref={fileRef} type="file" multiple className="asset-file-input" onChange={event => {setFiles(Array.from(event.target.files || []));setError('');setCompleted(0);}}/><div className="asset-upload-drop" onDragOver={event => event.preventDefault()} onDrop={event => {event.preventDefault();event.stopPropagation();if (!busy) {setFiles(Array.from(event.dataTransfer.files));setError('');setCompleted(0);}}}><Upload size={30}/><strong>{files.length ? `${files.length} файлов выбрано` : 'Перетащите файлы сюда'}</strong><button className="btn" onClick={() => fileRef.current?.click()} disabled={busy}>{files.length ? 'Выбрать другие' : 'Выбрать файлы'}</button></div><div className="asset-upload-type"><label htmlFor="asset-upload-kind">Категория</label><Select id="asset-upload-kind" value={kind} onChange={setKind} disabled={busy} options={[{value: 'auto', label: 'Определить автоматически'}, ...Object.entries(assetKindLabels).map(([value, label]) => ({value, label}))]}/></div>{!!files.length && <div className="asset-upload-list">{files.map((file, index) => <div key={`${file.name}-${index}`}><File size={15}/><span>{file.name}</span><small>{formatBytes(file.size)}</small></div>)}</div>}{error && <p className="asset-error" role="alert">{error}{completed > 0 && ` Уже сохранено: ${completed}.`}</p>}<div className="asset-upload-actions"><span>{busy ? `Сохранено ${completed} из ${files.length}` : files.length ? formatBytes(files.reduce((sum, file) => sum + file.size, 0)) : ''}</span><button className="btn btn-primary" onClick={() => void upload()} disabled={busy || !files.length}>{busy ? <Loader2 className="asset-spin" size={15}/> : <Upload size={15}/>} {busy ? 'Загружаем' : 'Загрузить'}</button></div></div></Modal>;
}

function AssetDetail({asset, onClose, onDeleted}: {asset: LibraryAsset; onClose: () => void; onDeleted: () => void}) {
  const [blob, setBlob] = useState<Blob | null>(null);const [url, setUrl] = useState('');const [text, setText] = useState('');const [note, setNote] = useState('');const [error, setError] = useState('');const [confirm, setConfirm] = useState(false);const [deleting, setDeleting] = useState(false);const [fontReady, setFontReady] = useState(false);
  const references = getBrain().sources.filter(source => source.assetId === asset.id).length;
  useEffect(() => {let active = true;let objectUrl = '';let face: FontFace | null = null;void (async () => {try {const file = await getAssetBlob(asset.id);if (!active) return;if (!file) {setError('Файл не найден в хранилище.');return;}setBlob(file);objectUrl = URL.createObjectURL(file);setUrl(objectUrl);if (asset.kind === 'document' || asset.kind === 'other') {const result = await extractLocalText(file, asset.name);if (active) {setText(result.text);setNote(result.reason || (result.truncated ? 'Показаны первые 120 000 символов.' : ''));}}if (asset.kind === 'font') {try {face = new FontFace(`library-${asset.id}`, await file.arrayBuffer());await face.load();if (active) {document.fonts.add(face);setFontReady(true);}} catch {if (active) setNote('Этот шрифт не поддерживает предпросмотр в браузере.');}}} catch (failure) {if (active) setError(failure instanceof Error ? failure.message : 'Не удалось открыть файл.');}})();return () => {active = false;if (objectUrl) URL.revokeObjectURL(objectUrl);if (face) document.fonts.delete(face);};}, [asset]);
  const remove = async () => {setDeleting(true);try {await deleteAsset(asset.id);onDeleted();} catch {setError('Не удалось удалить файл. Попробуйте ещё раз.');setDeleting(false);}};
  return <Modal title={asset.name} onClose={onClose} wide={asset.kind === 'image' || asset.kind === 'video' || asset.kind === 'logo'}><div className="asset-detail"><div className="asset-detail-meta"><span>{assetKindLabels[asset.kind]}</span><span>{formatBytes(asset.size)}</span><span>{new Date(asset.createdAt).toLocaleDateString('ru-RU')}</span></div><div className={`asset-detail-preview asset-detail-${asset.kind}`}>{error ? <p className="asset-error" role="alert">{error}</p> : !blob ? <Loader2 className="asset-spin" size={25}/> : asset.kind === 'image' || asset.kind === 'logo' ? <img src={url} alt={asset.name}/> : asset.kind === 'video' ? <video src={url} controls playsInline preload="metadata"/> : asset.kind === 'font' && fontReady ? <div className="asset-font-preview" style={{fontFamily: `"library-${asset.id}"`}}><span>Aa Бб</span><p>Большие идеи начинаются здесь.</p><small>АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЭЮЯ<br/>ABCDEFGHIJKLMNOPQRSTUVWXYZ<br/>0123456789</small></div> : text ? <pre>{text}</pre> : <div className="asset-document-placeholder"><AssetIcon kind={asset.kind} size={43}/><span>{note || 'Файл доступен для скачивания'}</span></div>}</div>{note && text && <p className="asset-detail-note">{note}</p>}{confirm && references > 0 && <p className="asset-detail-note">Файл используется в источниках: {references}. Извлечённый текст останется в базе знаний.</p>}<div className="asset-detail-actions"><div>{confirm ? <><button className="asset-delete-confirm" disabled={deleting} onClick={() => void remove()}>{deleting ? 'Удаляем' : 'Удалить файл'}</button><button className="btn btn-ghost" disabled={deleting} onClick={() => setConfirm(false)}>Отмена</button></> : <button className="asset-delete" onClick={() => setConfirm(true)}><Trash2 size={15}/> Удалить</button>}</div>{url && <a className="btn btn-primary" href={url} download={asset.name}><Download size={15}/> Скачать</a>}</div></div></Modal>;
}

export function AssetPicker({onSelect, onClose}: {onSelect: (asset: LibraryAsset, blob: Blob) => void; onClose: () => void}) {
  const {assets, loading, error} = useAssets();const visual = assets.filter(asset => ['image', 'logo', 'video'].includes(asset.kind));const urls = useAssetImages(visual);const [query, setQuery] = useState('');const [busy, setBusy] = useState('');const [failure, setFailure] = useState('');const fileRef = useRef<HTMLInputElement>(null);
  const choose = async (asset: LibraryAsset) => {setBusy(asset.id);setFailure('');try {const blob = await getAssetBlob(asset.id);if (!blob) throw new Error('Файл не найден.');onSelect(asset, blob);onClose();} catch (reason) {setFailure(reason instanceof Error ? reason.message : 'Не удалось выбрать файл.');}finally {setBusy('');}};
  return <Modal title="Материалы компании" onClose={onClose} wide><div className="asset-picker"><div className="asset-picker-toolbar"><label className="asset-search"><Search size={16}/><input aria-label="Поиск материалов" value={query} onChange={event => setQuery(event.target.value)} placeholder="Найти изображение или видео"/></label><input className="asset-file-input" type="file" accept="image/*,video/*" ref={fileRef} onChange={event => {const file = event.target.files?.[0];if (!file) return;setBusy('upload');void saveAsset(file).then(asset => {onSelect(asset, file);onClose();}, () => {setFailure('Не удалось загрузить материал.');setBusy('');});}}/><button className="btn" disabled={!!busy} onClick={() => fileRef.current?.click()}><Upload size={15}/> Загрузить</button></div>{failure || error ? <p className="asset-error" role="alert">{failure || error}</p> : null}{loading ? <div className="asset-picker-empty"><Loader2 className="asset-spin" size={24}/></div> : visual.length ? <div className="asset-picker-grid">{visual.filter(asset => asset.name.toLowerCase().includes(query.toLowerCase())).map(asset => <AssetCard key={asset.id} asset={asset} url={urls[asset.id]} selected={busy === asset.id} onClick={() => {if (!busy) void choose(asset);}}/>)}</div> : <div className="asset-picker-empty"><Image size={30}/><h3>Добавьте материалы компании</h3><p>Изображения, логотипы и видео будут доступны здесь.</p><button className="btn" onClick={() => fileRef.current?.click()}>Выбрать файл</button></div>}</div></Modal>;
}
