import { useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, CircleCheck, CreditCard, Image, Layers3, LockKeyhole, Sparkles, Users, Video } from 'lucide-react';
import { Modal } from './ui';
import { useWorkspace } from './store';
import { billingDate, currentUsage, getPlan, money, simulateCheckout, useSubscriptionPlans, subscriptionState, useWorkspaceBillingAccount } from './billing-data';
import type { SubscriptionPlan } from './billing-data';
import './billing.css';

function quantity(value:number|null,label:string) {return value===null?`Индивидуально · ${label}`:`${money(value)} ${label}`;}
export function SubscriptionCard({onOpen}:{onOpen?:()=>void}) {
  const account=useWorkspaceBillingAccount();const {navigate}=useWorkspace();const state=subscriptionState(account);const plan=getPlan(account?.subscription?.planId);
  return <button className={`subscription-rail-card ${state==='active'?'has-subscription':''}`} onClick={onOpen??(()=>navigate('billing'))} title={state==='active'?`Подписка ${plan?.name}`:'Выбрать подписку'} aria-label={state==='active'?`Подписка ${plan?.name}. Управление тарифом`:'Выбрать тариф LABRICA'}><span className="subscription-rail-icon"><Sparkles size={17}/></span><span className="rail-label"><strong>{state==='active'?plan?.name:state==='expired'?'Продлить подписку':'Выбрать тариф'}</strong><small>{state==='active'&&account?.subscription?`до ${billingDate(account.subscription.expiresAt)}`:'Больше возможностей'}</small></span><ArrowUpRight size={14} className="subscription-rail-arrow"/></button>;
}
export default function Billing() {
  const subscriptionPlans=useSubscriptionPlans();
  const account=useWorkspaceBillingAccount();const {notify}=useWorkspace();const state=subscriptionState(account);const activePlan=getPlan(account?.subscription?.planId);const usage=currentUsage(account?.id);
  const [selectedId,setSelectedId]=useState<string|null>(null);const selected=subscriptionPlans.find(plan=>plan.id===selectedId)??null;const setSelected=(plan:SubscriptionPlan|null)=>setSelectedId(plan?.id??null);const [checkoutDone,setCheckoutDone]=useState(false);const [checkoutError,setCheckoutError]=useState('');
  function selectPlan(plan:SubscriptionPlan){setSelected(plan);setCheckoutDone(false);setCheckoutError('');}
  function previewCheckout(){if(!selected)return;try{simulateCheckout(selected.id);setCheckoutDone(true);notify('Оформление просмотрено. Деньги не списывались');}catch(error){setCheckoutError(error instanceof Error?error.message:'Не удалось сохранить сценарий');}}
  return <div className="billing-page"><div className="page-heading"><h1 className="page-title">Подписка</h1><span className="billing-period">Оплата за месяц</span></div>
    <section className={`billing-current ${state==='active'?'billing-current-active':''}`}><span className="billing-current-icon"><Layers3 size={24}/></span><div><span className="billing-eyebrow">ВАШ ТАРИФ</span><h2>{state==='active'?activePlan?.name:state==='expired'?'Подписка завершилась':state==='blocked'?'Аккаунт заблокирован':'Выберите свой темп'}</h2><p>{state==='active'&&account?.subscription?`Действует до ${billingDate(account.subscription.expiresAt)}`:state==='expired'?'Выберите тариф, чтобы продолжить работу.':'От первых публикаций до полноценного контент-процесса.'}</p></div>{state==='active'&&<div className="billing-current-source"><CircleCheck size={15}/><span>{account?.subscription?.source==='manual'?'Выдана администратором':'Оплачена'}<small>Без автоматического продления</small></span></div>}</section>
    <div className="billing-plans">{subscriptionPlans.map(plan=><article className={`billing-plan ${plan.highlighted?'billing-plan-featured':''}`} key={plan.id}><div className="billing-plan-name"><span>{plan.name}</span>{plan.highlighted&&<span className="billing-best">Лучший выбор</span>}</div><p className="billing-plan-description">{plan.description}</p><div className="billing-plan-price">{plan.id==='custom'&&<span>от </span>}<strong>{money(plan.price)}</strong><span> ₽</span></div><span className="billing-price-period">в месяц</span><button className={`btn ${plan.highlighted?'btn-primary':'btn-ghost'} billing-plan-button`} onClick={()=>selectPlan(plan)}>{state==='active'&&activePlan?.id===plan.id?'Мой тариф':plan.id==='custom'?'Узнать подробнее':'Выбрать тариф'}<ArrowRight size={15}/></button><div className="billing-plan-limits"><><span><Layers3 size={14}/>{quantity(plan.limits.brands,plan.limits.brands===1?'бренд':'бренда')} · {quantity(plan.limits.profiles,'профилей')}</span><span><Sparkles size={14}/>{quantity(plan.limits.posts,'постов')}</span><span><Image size={14}/>{quantity(plan.limits.images,'изображений')}</span><span><Video size={14}/>{quantity(plan.limits.videoSeconds,'секунд видео')}</span><span><Users size={14}/>{quantity(plan.limits.seats,plan.limits.seats===1?'участник':plan.limits.seats===3?'участника':'участников')}</span></></div><div className="billing-plan-features">{plan.features.map(feature=><span key={feature}><Check size={13}/>{feature}</span>)}</div></article>)}</div>
    {state==='active'&&activePlan&&<section className="panel billing-usage"><div className="billing-section-heading"><h2>Использование</h2><span>{new Date().toLocaleDateString('ru-RU',{month:'long',year:'numeric'})}</span></div><div className="billing-usage-grid">{([{key:'posts',label:'Посты',icon:Sparkles},{key:'images',label:'Изображения',icon:Image},{key:'videoSeconds',label:'Секунды видео',icon:Video}] as const).map(({key,label,icon:Icon})=>{const limit=activePlan.limits[key];const used=usage[key];return <div className="billing-usage-item" key={key}><div><span><Icon size={16}/>{label}</span><strong>{money(used)}<small> / {limit===null?'индивидуально':money(limit)}</small></strong></div><div className="billing-usage-track"><i style={{width:`${limit?Math.min(100,used/limit*100):0}%`}}/></div></div>;})}</div><p className="billing-usage-note">Учитываются операции этого аккаунта за календарный месяц.</p></section>}
    
    {selected&&<Modal title={checkoutDone?'Оформление подписки':selected.id==='custom'?'Индивидуальный тариф':'Оформление подписки'} onClose={()=>setSelected(null)}><div className="billing-checkout">{checkoutDone?<div className="billing-checkout-done"><span><Check size={30}/></span><h2>Оформление просмотрено</h2><p>Вы посмотрели оформление тарифа {selected.name}. Деньги не списывались, подписка не активирована.</p><div className="billing-checkout-summary"><span>Тариф {selected.name}</span><strong>{selected.id==='custom'?'от ':''}{money(selected.price)} ₽ / месяц</strong></div><button className="btn btn-primary" onClick={()=>setSelected(null)}>Вернуться к тарифам<ArrowRight size={15}/></button></div>:<><div className="billing-checkout-plan"><span className="billing-checkout-emblem"><Sparkles size={25}/></span><div><span>LABRICA</span><h2>{selected.name}</h2></div><strong>{selected.id==='custom'?'от ':''}{money(selected.price)} ₽<small>в месяц</small></strong></div>{selected.id==='custom'?<p className="billing-custom-note">Лимиты, инфраструктура и интеграции определяются под вашу команду. </p>:<div className="billing-checkout-limits"><span>{quantity(selected.limits.posts,'постов')}</span><span>{quantity(selected.limits.images,'изображений')}</span><span>{quantity(selected.limits.videoSeconds,'секунд видео')}</span></div>}<div className="billing-checkout-account"><span>Аккаунт</span><strong>{account?.email??'Локальный просмотр'}</strong></div><div className="billing-payment-method"><CreditCard size={23}/><span>Банковская карта<small>Платёжный провайдер не подключён</small></span><LockKeyhole size={15}/></div><div className="billing-checkout-total"><span>{selected.id==='custom'?'Стоимость от':'Итого за месяц'}</span><strong>{money(selected.price)} ₽</strong></div>{checkoutError&&<p className="billing-error" role="alert">{checkoutError}</p>}<button className="btn btn-primary billing-checkout-continue" onClick={previewCheckout}>Посмотреть подтверждение<ArrowRight size={16}/></button></>}</div></Modal>}
  </div>;
}
