import { useRef, useState } from 'react';
import { ArrowUpRight, BookOpen, BrainCircuit, Check, ChevronRight, FileText, Globe2, Layers3, Link2, Loader2, Plus, Search, ShieldCheck, Sparkles, Trash2, Upload, X } from 'lucide-react';
import { useWorkspace } from './store';
import { Modal, Select } from './ui';
import { extractLocalText, getAssetBlob, getBrain, knowledgeLabels, saveAsset, saveBrain, verificationLabels, verifiedBrandContext } from './brain-data';
import type { BrandBrainData, BrainSource, KnowledgeCategory, KnowledgeItem, Verification } from './brain-data';
import './brand-brain.css';

const verifyOptions = [{value: 'unverified', label: 'Не проверено'}, {value: 'verified', label: 'Подтверждено командой'}, {value: 'inferred', label: 'Предположение'}];
function VerificationBadge({value}: {value: Verification}) {return <span className={`brain-verification is-${value}`}>{value === 'verified' ? <Check size={11}/> : <span/>}{verificationLabels[value]}</span>;}
function Toggle({value, onChange, label}: {value: boolean; onChange: (value: boolean) => void; label: string}) {return <button type="button" role="switch" aria-checked={value} aria-label={label} className={`brain-toggle ${value ? 'is-on' : ''}`} onClick={() => onChange(!value)}><span/></button>;}

export default function BrandBrain() {
  const {section, setSection, brand, setBrand, notify} = useWorkspace();
  const [brain, setBrain] = useState<BrandBrainData>(() => {const saved = getBrain();return saved.updatedAt ? saved : {...saved, company: {...saved.company, name: brand.name, audience: brand.audience, tone: brand.tone}, rules: {...saved.rules, voiceRules: brand.rules}};});
  const [dirty, setDirty] = useState(false);
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('all');
  const [knowledgeEdit, setKnowledgeEdit] = useState<KnowledgeItem | 'new' | null>(null);
  const [addSource, setAddSource] = useState(false);
  const [sourceDetail, setSourceDetail] = useState<string | null>(null);
  const [contextOpen, setContextOpen] = useState(false);
  const active = ['overview', 'knowledge', 'rules', 'sources'].includes(section) ? section : 'overview';
  const commit = (next: BrandBrainData, message = 'База бренда сохранена') => {try {const updated = {...next, updatedAt: new Date().toISOString()};saveBrain(updated);setBrain(updated);setDirty(false);if (active === 'overview' || active === 'rules') setBrand({...brand, name: next.company.name.trim() || brand.name, tone: next.company.tone, audience: next.company.audience, rules: next.rules.voiceRules});notify(message);return true;} catch {notify('Не удалось сохранить сведения. Проверьте свободное место браузера.');return false;}};
  const updateCompany = (patch: Partial<BrandBrainData['company']>) => {setBrain(value => ({...value, company: {...value.company, ...patch, verified: patch.verified ?? false}}));setDirty(true);};
  const updateRules = (patch: Partial<BrandBrainData['rules']>) => {setBrain(value => ({...value, rules: {...value.rules, ...patch}}));setDirty(true);};
  const verified = brain.knowledge.filter(item => item.verification === 'verified');
  const filteredKnowledge = brain.knowledge.filter(item => (category === 'all' || item.category === category) && `${item.title} ${item.content}`.toLowerCase().includes(search.toLowerCase()));
  const selectedSource = brain.sources.find(source => source.id === sourceDetail);
  const importKnowledge = (source: BrainSource) => {setSourceDetail(null);setKnowledgeEdit({id: crypto.randomUUID(), category: 'fact', title: source.name, content: (source.text || '').slice(0, 10000), verification: 'unverified', sourceId: source.id, updatedAt: new Date().toISOString()});};
  return <div className="brain-page">
    <div className="page-heading"><h1 className="page-title">Brand Brain</h1><div className="brain-heading-actions">{dirty && <span className="brain-unsaved"><i/>Есть изменения</span>}{active === 'knowledge' ? <button className="btn btn-primary" onClick={() => setKnowledgeEdit('new')}><Plus size={16}/> Добавить знание</button> : active === 'sources' ? <button className="btn btn-primary" onClick={() => setAddSource(true)}><Plus size={16}/> Добавить источник</button> : <button className="btn btn-primary" onClick={() => commit(brain)}><Check size={16}/> Сохранить</button>}</div></div>
    {active === 'overview' && <div className="brain-overview-grid">
      <section className="panel brain-company-card"><div className="brain-card-heading"><h2>Компания</h2><VerificationBadge value={brain.company.verified ? 'verified' : 'unverified'}/></div><div className="brain-form-grid"><label className="field">Название<input value={brain.company.name} onChange={event => updateCompany({name: event.target.value})} placeholder="Название компании"/></label><label className="field">Сайт<input type="url" value={brain.company.website} onChange={event => updateCompany({website: event.target.value})} placeholder="https://company.ru"/></label><label className="field brain-full-width">Чем занимается компания<textarea rows={4} value={brain.company.description} onChange={event => updateCompany({description: event.target.value})} placeholder="Продукт, ценность и отличия — только известные вам факты"/></label><label className="field brain-full-width">Аудитория<textarea rows={3} value={brain.company.audience} onChange={event => updateCompany({audience: event.target.value})} placeholder="Для кого вы создаёте продукт"/></label><div className="field brain-full-width"><label htmlFor="brain-tone">Тон коммуникации</label><Select id="brain-tone" value={brain.company.tone} onChange={value => updateCompany({tone: value})} options={Array.from(new Set([brain.company.tone, 'Дружелюбный', 'Экспертный', 'Деловой', 'Лаконичный', 'Вдохновляющий'])).map(value => ({value, label: value}))}/></div></div><div className="brain-confirm-row"><span><ShieldCheck size={17}/>Сведения проверены командой</span><Toggle value={brain.company.verified} onChange={value => updateCompany({verified: value})} label="Подтвердить сведения о компании"/></div></section>
      <aside className="brain-overview-side"><section className="brain-context-card"><span className="brain-context-icon"><BrainCircuit size={25}/></span><h2>Контекст вашего бренда.</h2><div className="brain-context-numbers"><div><strong>{verified.length}</strong><span>подтверждённых знаний</span></div><div><strong>{brain.sources.length}</strong><span>источников</span></div></div><button onClick={() => setContextOpen(true)}>Посмотреть контекст<ArrowUpRight size={17}/></button></section><section className="panel brain-coverage-card"><h2>База знаний</h2>{Object.entries(knowledgeLabels).map(([key, label]) => <button key={key} onClick={() => {setCategory(key);setSection('knowledge');}}><span>{label}</span><strong>{brain.knowledge.filter(item => item.category === key).length}</strong><ChevronRight size={14}/></button>)}</section><div className="brain-provenance-note"><ShieldCheck size={17}/><p>В контент передаются только сведения, которые вы подтвердили.</p></div></aside>
    </div>}
    {active === 'knowledge' && <><div className="brain-toolbar"><label className="brain-search"><Search size={17}/><input aria-label="Поиск по знаниям" placeholder="Найти в базе знаний" value={search} onChange={event => setSearch(event.target.value)}/>{search && <button aria-label="Очистить поиск" onClick={() => setSearch('')}><X size={13}/></button>}</label><Select aria-label="Категория знаний" value={category} onChange={setCategory} options={[{value: 'all', label: 'Все категории'}, ...Object.entries(knowledgeLabels).map(([value, label]) => ({value, label}))]}/></div>{filteredKnowledge.length ? <div className="brain-knowledge-list">{filteredKnowledge.map(item => <button className="brain-knowledge-row panel" key={item.id} onClick={() => setKnowledgeEdit(item)}><span className="brain-knowledge-symbol"><BookOpen size={18}/></span><span className="brain-knowledge-copy"><small>{knowledgeLabels[item.category]}</small><strong>{item.title}</strong><span>{item.content}</span>{item.sourceId && <em><Link2 size={11}/>{brain.sources.find(source => source.id === item.sourceId)?.name || 'Источник удалён'}</em>}</span><VerificationBadge value={item.verification}/><ChevronRight size={17}/></button>)}</div> : <div className="brain-empty panel"><BookOpen size={32}/><h2>{search || category !== 'all' ? 'Ничего не найдено' : 'Здесь живёт знание о компании'}</h2><p>{search || category !== 'all' ? 'Измените запрос или категорию.' : 'Добавьте продукты, ответы на вопросы и факты.'}</p><button className="btn" onClick={() => search || category !== 'all' ? (setSearch(''), setCategory('all')) : setKnowledgeEdit('new')}>{search || category !== 'all' ? 'Сбросить фильтры' : 'Добавить первое знание'}</button></div>}</>}
    {active === 'rules' && <div className="brain-rules-grid"><section className="panel brain-rules-main"><div className="brain-card-heading"><h2>Голос и формулировки</h2><Sparkles size={18}/></div><div className="brain-rules-fields"><label className="field">Редакционные правила<textarea rows={5} value={brain.rules.voiceRules} onChange={event => updateRules({voiceRules: event.target.value})} placeholder="Как говорим, на что обращаем внимание"/></label><label className="field">Запрещённые слова<textarea rows={3} value={brain.rules.forbiddenWords.join('\n')} onChange={event => updateRules({forbiddenWords: event.target.value.split('\n')})} placeholder="Каждое слово или фраза — с новой строки"/></label><label className="field">Недопустимые обещания<textarea rows={3} value={brain.rules.avoidClaims.join('\n')} onChange={event => updateRules({avoidClaims: event.target.value.split('\n')})} placeholder="Например: гарантированный результат"/></label><label className="field">Обязательные формулировки<textarea rows={3} value={brain.rules.requiredPhrases.join('\n')} onChange={event => updateRules({requiredPhrases: event.target.value.split('\n')})} placeholder="Если нужны — каждая с новой строки"/></label></div></section><aside className="panel brain-protection-card"><span className="brain-protection-icon"><ShieldCheck size={25}/></span><h2>Защита бренда</h2>{[{key: 'requireSourceForNumbers' as const, title: 'Проверять числа и цены', text: 'Сопоставлять с подтверждёнными фактами.'}, {key: 'blockUnverifiedFacts' as const, title: 'Блокировать предположения', text: 'Не выдавать непроверенные сведения за факты.'}, {key: 'blockCompetitorMentions' as const, title: 'Не упоминать конкурентов', text: 'Использовать список из базы знаний.'}].map(rule => <div className="brain-protection-rule" key={rule.key}><div><strong>{rule.title}</strong><p>{rule.text}</p></div><Toggle value={brain.rules[rule.key]} onChange={value => updateRules({[rule.key]: value})} label={rule.title}/></div>)}<div className="brain-rule-footnote">Правила используются при локальной проверке текста.</div></aside></div>}
    {active === 'sources' && <>{brain.sources.length ? <div className="brain-source-grid">{brain.sources.map(source => <button key={source.id} className="panel brain-source-card" onClick={() => setSourceDetail(source.id)}><span className="brain-source-icon">{source.type === 'url' ? <Globe2 size={22}/> : source.type === 'file' ? <FileText size={22}/> : <Layers3 size={22}/>}</span><VerificationBadge value={source.verification}/><h2>{source.name}</h2><p>{source.status === 'configured' ? 'Адрес сохранён. Текст ещё не добавлен.' : source.status === 'unsupported' ? source.reason || 'Файл сохранён, текст не извлечён.' : source.text?.slice(0, 140)}</p><div><span>{source.type === 'url' ? 'Сайт · добавлено вручную' : source.type === 'file' ? 'Документ' : 'Текст'}{source.status === 'ready' && ' · текст доступен'}</span><ArrowUpRight size={16}/></div></button>)}</div> : <div className="brain-empty panel"><Link2 size={32}/><h2>Надёжный контент начинается с источников</h2><p>Сохраните сайт, загрузите документ или добавьте текст.</p><button className="btn" onClick={() => setAddSource(true)}>Добавить источник</button></div>}<div className="brain-source-footnote"><Globe2 size={14}/>Сайты не сканируются автоматически. Файлы и добавленный текст сохраняются в этом браузере.</div></>}
    {knowledgeEdit && <KnowledgeEditor item={knowledgeEdit === 'new' ? null : knowledgeEdit} sources={brain.sources} onClose={() => setKnowledgeEdit(null)} onSave={item => {const next = {...brain, knowledge: [item, ...brain.knowledge.filter(value => value.id !== item.id)]};if (commit(next, 'Знание сохранено')) setKnowledgeEdit(null);}} onDelete={knowledgeEdit !== 'new' && brain.knowledge.some(value => value.id === knowledgeEdit.id) ? () => {if (commit({...brain, knowledge: brain.knowledge.filter(value => value.id !== knowledgeEdit.id)}, 'Знание удалено')) setKnowledgeEdit(null);} : undefined}/>}
    {addSource && <SourceImporter onClose={() => setAddSource(false)} onAdd={source => {const saved = commit({...brain, sources: [source, ...brain.sources]}, 'Источник добавлен');if (saved) setAddSource(false);return saved;}}/>}
    {selectedSource && <SourceDetail source={selectedSource} onClose={() => setSourceDetail(null)} onImport={() => importKnowledge(selectedSource)} onChange={source => commit({...brain, sources: brain.sources.map(value => value.id === source.id ? source : value)}, 'Источник обновлён')} onDelete={() => {const next = {...brain, sources: brain.sources.filter(value => value.id !== selectedSource.id), knowledge: brain.knowledge.map(value => value.sourceId === selectedSource.id ? {...value, sourceId: undefined, verification: 'unverified' as const} : value)};if (commit(next, 'Источник удалён. Связанные знания требуют проверки.')) setSourceDetail(null);}}/>}
    {contextOpen && <Modal title="Контекст бренда" onClose={() => setContextOpen(false)}><div className="brain-context-modal"><span className="brain-modal-caption">Подтверждённые сведения и редакционные правила</span><pre>{verifiedBrandContext(brain) || 'Пока нет подтверждённых сведений.'}</pre></div></Modal>}
  </div>;
}

function KnowledgeEditor({item, sources, onClose, onSave, onDelete}: {item: KnowledgeItem | null; sources: BrainSource[]; onClose: () => void; onSave: (item: KnowledgeItem) => void; onDelete?: () => void}) {
  const [draft, setDraft] = useState<KnowledgeItem>(item || {id: crypto.randomUUID(), category: 'fact', title: '', content: '', verification: 'unverified', updatedAt: new Date().toISOString()});
  const [error, setError] = useState('');
  const [confirmDelete, setConfirmDelete] = useState(false);
  return <Modal title={item ? 'Знание о компании' : 'Новое знание'} onClose={onClose}><div className="brain-edit-form"><div className="brain-form-pair"><div className="field"><label htmlFor="knowledge-category">Категория</label><Select id="knowledge-category" value={draft.category} onChange={value => setDraft({...draft, category: value as KnowledgeCategory})} options={Object.entries(knowledgeLabels).map(([value, label]) => ({value, label}))}/></div><div className="field"><label htmlFor="knowledge-verification">Статус</label><Select id="knowledge-verification" value={draft.verification} onChange={value => setDraft({...draft, verification: value as Verification})} options={verifyOptions}/></div></div><label className="field">Название<input value={draft.title} onChange={event => setDraft({...draft, title: event.target.value})} placeholder="Например: тариф для команды"/></label><label className="field">Содержание<textarea rows={6} value={draft.content} onChange={event => setDraft({...draft, content: event.target.value, verification: 'unverified'})} placeholder="Факт, описание продукта или ответ на вопрос"/></label><div className="field"><label htmlFor="knowledge-source">Источник</label><Select id="knowledge-source" value={draft.sourceId || ''} onChange={value => setDraft({...draft, sourceId: value || undefined})} options={[{value: '', label: 'Добавлено командой'}, ...sources.map(source => ({value: source.id, label: source.name}))]}/></div>{draft.verification === 'verified' && <p className="brain-confirmation-note"><ShieldCheck size={14}/>Вы подтверждаете, что сведения актуальны и их можно использовать в контенте.</p>}{error && <p className="brain-form-error" role="alert">{error}</p>}<div className="brain-modal-actions"><div>{onDelete && (confirmDelete ? <button className="brain-delete-confirm" onClick={onDelete}>Подтвердить удаление</button> : <button className="icon-button" aria-label="Удалить знание" onClick={() => setConfirmDelete(true)}><Trash2 size={16}/></button>)}</div><div><button className="btn btn-ghost" onClick={onClose}>Отмена</button><button className="btn btn-primary" onClick={() => {if (!draft.title.trim() || !draft.content.trim()) {setError('Добавьте название и содержание.');return;}onSave({...draft, title: draft.title.trim(), content: draft.content.trim(), updatedAt: new Date().toISOString()});}}><Check size={15}/> Сохранить</button></div></div></div></Modal>;
}

function SourceImporter({onClose, onAdd}: {onClose: () => void; onAdd: (source: BrainSource) => boolean}) {
  const [type, setType] = useState<'url' | 'text' | 'file'>('url');
  const [name, setName] = useState('');const [url, setUrl] = useState('');const [text, setText] = useState('');const [file, setFile] = useState<File | null>(null);const [busy, setBusy] = useState(false);const [error, setError] = useState('');
  const fileRef = useRef<HTMLInputElement>(null);
  const submit = async () => {setError('');let validUrl = '';if (type === 'url') {try {const parsed = new URL(/^https?:\/\//i.test(url) ? url : `https://${url}`);if (!url.trim() || !['http:', 'https:'].includes(parsed.protocol) || !parsed.hostname.includes('.')) throw new Error();validUrl = parsed.href;} catch {setError('Укажите корректный адрес сайта.');return;}}if (type === 'text' && !text.trim()) {setError('Добавьте текст источника.');return;}if (type === 'file' && !file) {setError('Выберите документ.');return;}setBusy(true);try {let source: BrainSource = {id: crypto.randomUUID(), type, name: name.trim() || (type === 'url' ? new URL(validUrl).hostname : type === 'file' ? file!.name : 'Текстовый источник'), url: validUrl || undefined, text: text.trim().slice(0, 120000), status: text.trim() ? 'ready' : 'configured', verification: 'unverified', createdAt: new Date().toISOString(), truncated: text.length > 120000};if (type === 'file' && file) {const asset = await saveAsset(file, 'document');const extraction = await extractLocalText(file, file.name);source = {...source, assetId: asset.id, ...extraction};}onAdd(source);} catch (failure) {setError(failure instanceof Error ? failure.message : 'Не удалось сохранить источник.');}finally {setBusy(false);}};
  return <Modal title="Новый источник" onClose={() => {if (!busy) onClose();}}><div className="brain-edit-form"><div className="brain-import-types">{[{key: 'url' as const, label: 'Сайт', Icon: Globe2}, {key: 'file' as const, label: 'Документ', Icon: FileText}, {key: 'text' as const, label: 'Текст', Icon: Layers3}].map(({key, label, Icon}) => <button key={key} disabled={busy} className={type === key ? 'is-active' : ''} onClick={() => {setType(key);setError('');}}><Icon size={15}/>{label}</button>)}</div><label className="field">Название<input value={name} onChange={event => setName(event.target.value)} placeholder="Название источника"/></label>{type === 'url' && <label className="field">Адрес сайта<input type="url" value={url} onChange={event => setUrl(event.target.value)} placeholder="https://company.ru/about"/></label>}{type === 'file' ? <><input ref={fileRef} className="brain-file-input" type="file" accept=".txt,.md,.markdown,.json,.csv,.pdf,.doc,.docx,.html,.htm" onChange={event => setFile(event.target.files?.[0] || null)}/><button className="brain-document-upload" onClick={() => fileRef.current?.click()}><Upload size={25}/><strong>{file ? file.name : 'Выберите документ'}</strong><span>Текст, Markdown и JSON читаются локально.<br/>Другие форматы сохраняются как вложение.</span></button></> : <label className="field">{type === 'url' ? 'Текст страницы' : 'Содержание'}<textarea rows={7} value={text} onChange={event => setText(event.target.value)} placeholder={type === 'url' ? 'Вставьте нужный текст с сайта' : 'Вставьте сведения о компании'}/></label>}{type === 'url' && <p className="brain-modal-caption">Адрес сохраняется как источник. Автоматическое сканирование сайта не подключено.</p>}{error && <p className="brain-form-error" role="alert">{error}</p>}<div className="brain-modal-actions"><span className="brain-modal-caption">Новый источник будет непроверенным</span><button className="btn btn-primary" onClick={() => void submit()} disabled={busy}>{busy ? <Loader2 className="brain-spin" size={15}/> : <Plus size={15}/>} {busy ? 'Сохраняем' : 'Добавить'}</button></div></div></Modal>;
}

function SourceDetail({source, onClose, onImport, onChange, onDelete}: {source: BrainSource; onClose: () => void; onImport: () => void; onChange: (source: BrainSource) => void; onDelete: () => void}) {
  const {notify} = useWorkspace();const [confirmDelete, setConfirmDelete] = useState(false);const [manualText, setManualText] = useState('');
  const download = async () => {try {const blob = source.assetId ? await getAssetBlob(source.assetId) : undefined;if (!blob) {notify('Файл удалён из библиотеки. Извлечённый текст сохранён.');return;}const url = URL.createObjectURL(blob);const link = document.createElement('a');link.href = url;link.download = source.name;link.click();setTimeout(() => URL.revokeObjectURL(url), 1000);} catch {notify('Не удалось открыть файл.');}};
  return <Modal title={source.name} onClose={onClose}><div className="brain-edit-form"><div className="brain-source-detail-top"><VerificationBadge value={source.verification}/>{source.url && <a href={source.url} target="_blank" rel="noreferrer">Открыть сайт<ArrowUpRight size={14}/></a>}{source.assetId && <button onClick={() => void download()}>Скачать файл<ArrowUpRight size={14}/></button>}</div><div className="field"><label htmlFor="source-verification">Достоверность источника</label><Select id="source-verification" value={source.verification} onChange={value => onChange({...source, verification: value as Verification})} options={verifyOptions}/></div>{source.text ? <><pre className="brain-source-text">{source.text}</pre>{source.truncated && <p className="brain-modal-caption">Показаны первые 120 000 символов. Полный файл сохранён в библиотеке.</p>}</> : <><p className="brain-modal-caption">{source.reason || 'Текст источника ещё не добавлен.'}</p><label className="field">Текст вручную<textarea rows={6} value={manualText} onChange={event => setManualText(event.target.value)} placeholder="Вставьте текст, который нужно сохранить"/></label><button className="btn" disabled={!manualText.trim()} onClick={() => onChange({...source, text: manualText.trim().slice(0, 120000), status: 'ready', verification: 'unverified', reason: 'Текст добавлен вручную'})}>Сохранить текст</button></>}<div className="brain-modal-actions"><button className={confirmDelete ? 'brain-delete-confirm' : 'icon-button'} aria-label="Удалить источник" onClick={() => confirmDelete ? onDelete() : setConfirmDelete(true)}>{confirmDelete ? 'Удалить источник?' : <Trash2 size={16}/>}</button><button className="btn btn-primary" disabled={!source.text} onClick={onImport}><BookOpen size={15}/> В базу знаний</button></div></div></Modal>;
}
