import { useMemo, useRef, useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, Copy, FileText, Film, Image, Plus, RefreshCw, Sparkles, WandSparkles, X } from 'lucide-react';
import { makePost, platformMeta } from './model';
import type { BrandSettings, Platform, Post } from './model';
import { useWorkspace } from './store';
import { Modal, PlatformIcon, Select } from './ui';
import SocialPreview from './SocialPreview';
import { blobToDataURL, goalCTA, goalOptions } from './media-generation';
import type { VideoScript } from './media-generation';
import './controller.css';
import './controller-v3.css';
import { applyPreferences, learnEdit, preferenceSummary, recordLearning, getLearning } from './learning';
import { applyBrandProtection, verifiedFactsForContent, getBrain } from './brain-data';
import ContentHealth from './ContentHealth';
import { getGrowth } from './growth-data';
import { AssetPicker } from './AssetLibrary';
import CreativeGenerator from './CreativeGenerator';

interface Variant { label: string; angle: string; text: string }
const platforms: Platform[] = ['telegram', 'instagram', 'vk', 'youtube', 'threads', 'dzen'];
const initialGoal = 'registrations';
const shortSubject = (topic: string) => topic.trim().replace(/[.!?]+$/, '');
const goalLabel = (goal: string) => goalOptions.find(option => option.value === goal)?.label ?? 'Информирование';

export function createTextVariants(topic: string, tone: string, brand: BrandSettings, goal: string, revision = 0): Variant[] {
  const subject = shortSubject(topic);
  const openings: Record<string, string> = {'Дружелюбный':'Давайте разберёмся вместе.','Экспертный':'Начнём с наблюдения.','Смелый':'Пора посмотреть на привычное по-другому.','Лаконичный':'Коротко о главном.','Деловой':'Рассмотрим задачу и следующий шаг.','Вдохновляющий':'Один небольшой шаг может стать началом перемен.'};
  const opening = openings[tone] ?? openings['Дружелюбный'];
  const cta = goalCTA(goal, brand.name);
  const bodies: Record<string, [string,string,string]> = {
    reach:[`Легко увлечься цифрами и упустить главное. За темой «${subject.toLocaleLowerCase('ru-RU')}» стоит более простой вопрос: какую пользу человек заберёт с собой?\n\nОставьте одну мысль, которую можно объяснить коллеге за минуту. Подкрепите её понятным примером. Так у истории появится причина двигаться дальше.`, `Три способа сделать тему понятнее:\n\n01. Начните с знакомой ситуации.\n\n02. Объясните сложное через один пример.\n\n03. Оставьте мысль, которой захочется поделиться.`, `Что вы бы рассказали о теме «${subject.toLocaleLowerCase('ru-RU')}» человеку, который слышит о ней впервые?\n\nМы в ${brand.name} предлагаем начать с вопроса аудитории. Хорошая история не требует долгого вступления: она сразу помогает увидеть что-то знакомое по-новому.`],
    engagement:[`У темы «${subject.toLocaleLowerCase('ru-RU')}» редко бывает один правильный ответ. Кто-то доверяет привычному подходу, а кто-то каждый раз пробует новое.\n\nПредлагаем сравнить опыт. Что для вас важнее: стабильный процесс или возможность быстро проверить свежую идею?`, `Небольшой выбор для вашей команды:\n\nА — сначала собрать больше данных.\nБ — запустить небольшой эксперимент.\n\nПредставьте, что завтра нужно принять решение по теме «${subject.toLocaleLowerCase('ru-RU')}». Какой вариант выберете и почему?`, `Самые полезные истории часто начинаются с фразы «У нас это работает иначе».\n\nМы в ${brand.name} собираем разные взгляды на тему «${subject.toLocaleLowerCase('ru-RU')}». Поделитесь одним наблюдением, которое изменило ваш подход.`],
    clicks:[`Разобраться в теме «${subject.toLocaleLowerCase('ru-RU')}» легче, когда есть понятный следующий шаг.\n\nНачните с конкретного вопроса: какое действие приблизит вашу команду к результату? Соберите вводные, выберите один подход и проверьте его на практике.\n\nСледующий шаг — познакомиться с ${brand.name} и посмотреть, как этот подход можно применить к вашей задаче.`, `От вопроса к решению:\n\n01. Опишите задачу одним предложением.\n\n02. Определите, что мешает двигаться дальше.\n\n03. Посмотрите на подход ${brand.name} и выберите, что стоит попробовать.`, `Нужна отправная точка для темы «${subject.toLocaleLowerCase('ru-RU')}»?\n\nНе обязательно менять всё сразу. Достаточно разобраться в одном рабочем сценарии и увидеть, где следующий шаг.\n\nНачните знакомство с ${brand.name}: оцените, насколько наш подход подходит вашей команде.`],
    registrations:[`Хорошая идея приносит пользу, когда превращается в действие. Это относится и к теме «${subject.toLocaleLowerCase('ru-RU')}».\n\nВыберите одну задачу, с которой хотите разобраться. Запишите ожидаемый результат и подготовьте первый материал.\n\nВ ${brand.name} предлагаем начать с вашего собственного рабочего пространства: собрать идеи, выбрать следующий шаг и проверить подход на практике.`, `Первый шаг в ${brand.name}:\n\n01. Создайте аккаунт.\n\n02. Сформулируйте задачу: «${subject}».\n\n03. Начните с одной идеи и доведите её до результата.\n\nНебольшой старт помогает понять, что будет полезно именно вашей команде.`, `Что обычно мешает перейти от обсуждения к первому шагу?\n\nИдея «${subject.toLocaleLowerCase('ru-RU')}» может остаться в заметках. А может стать вашей следующей рабочей задачей.\n\nНачните знакомство с ${brand.name} с регистрации и одной конкретной цели. Не обязательно настраивать весь процесс сразу.`],
    nurture:[`За темой «${subject.toLocaleLowerCase('ru-RU')}» стоит не только результат, но и способ работы.\n\nНам в ${brand.name} близок подход, в котором решения можно объяснить: какую задачу решаем, что проверяем и по каким признакам понимаем, что стало лучше.\n\nПредлагаем присмотреться к деталям. Именно они помогают понять, совпадают ли наши взгляды на работу.`, `Три вопроса, которые стоит задать перед началом:\n\n01. Что команда считает хорошим результатом?\n\n02. Как мы проверяем свои предположения?\n\n03. Что делаем с обратной связью?\n\nЧерез эти вопросы мы в ${brand.name} предлагаем посмотреть и на тему «${subject.toLocaleLowerCase('ru-RU')}».`, `Сначала — знакомство. Потом — доверие. И только затем решение.\n\nРаскрывая тему «${subject.toLocaleLowerCase('ru-RU')}», мы хотим показать логику ${brand.name}: начинаем с понятной задачи, работаем небольшими шагами и смотрим на обратную связь.\n\nКакой этап вы хотели бы разобрать подробнее?`],
    information:[`Что стоит знать о теме «${subject.toLocaleLowerCase('ru-RU')}»:\n\nНачните с контекста: кому это важно и какую задачу помогает решить. Затем отделите основную мысль от деталей.\n\nВ ${brand.name} предлагаем опираться на проверенные данные и понятные примеры. Добавьте в материал свои факты перед публикацией.`, `Краткий разбор:\n\nЧто: ${subject}.\n\nДля кого: ${brand.audience || 'ваша аудитория'}.\n\nС чего начать: сформулировать задачу и собрать необходимые данные.\n\nНа что обратить внимание: отделить подтверждённые факты от предположений.`, `Тема: ${subject}\n\nПолезный материал отвечает на три вопроса: что происходит, почему это важно и что читатель может сделать дальше.\n\nДополните этот черновик фактами вашей команды. Один конкретный пример поможет сделать объяснение убедительнее.`],
  };
  const content = bodies[goal] ?? bodies.information;
  return content.map((body,index)=>({label:['Через наблюдение','Практический подход','Начать с вопроса'][index],angle:goal==='engagement'?['Два взгляда → обсуждение','Выбор → комментарии','История → опыт аудитории'][index]:goal==='registrations'?['Задача → польза → регистрация','Три шага к началу','Вопрос → первый шаг'][index]:['Мысль → пример → действие','Польза по шагам','Вопрос → новый взгляд'][index],text:`${index===2&&revision%2 ? `Посмотрим на это иначе: ${subject.toLocaleLowerCase('ru-RU')}` : subject}\n\n${opening}\n\n${tone==='Лаконичный' ? body.split('\n\n').slice(0,2).join('\n\n') : body}\n\n${cta}`}));
}
function adaptText(text: string, platform: Platform) {
  if (platform === 'telegram') return text;
  const clean = text.replace(/\*\*([^*]+)\*\*/g, '$1').replace(/\[([^\]]+)\]\(([^)]+)\)/g, '$1 ($2)');
  if (platform === 'instagram') return clean.replace(/\n\n0([1-3])\./g, '\n\n$1.');
  if (platform === 'youtube') return clean.replace(/в комментариях\./g, 'в комментариях к видео.');
  if (platform === 'threads' && clean.length > 500) {const paragraphs=clean.split('\n\n');const last=paragraphs.at(-1)?.slice(0,170)??'';return `${clean.slice(0,Math.max(0,497-last.length)).trimEnd()}…\n\n${last}`;}
  return clean;
}
function platformBodies(text: string, selected: Platform[]) {return Object.fromEntries(selected.map(platform => [platform, adaptText(text, platform)]));}
function ideaCollection(goal: string, brand: BrandSettings, offset: number) {
  const topics: Record<string,string[]> = {reach:['Почему больше контента не всегда значит больше роста','Один миф о вашей работе, который пора пересмотреть','Что ваша аудитория замечает в первую секунду','Неочевидная привычка сильной команды','Одна идея, которую стоит сохранить','Простой способ объяснить сложный продукт'],engagement:['Данные или интуиция: что выберет ваша команда','Ваш самый полезный рабочий ритуал','Что бы вы изменили в своём первом запуске','Один вопрос, на который нет простого ответа','Продолжите фразу: хороший контент — это…','Самая полезная обратная связь от клиента'],clicks:['Что посмотреть перед началом работы','Один сценарий, который стоит разобрать подробно','От знакомства с продуктом к первому шагу','Как выбрать подход для своей задачи','Где искать ответ на главный вопрос команды','Пять деталей, которые помогают принять решение'],registrations:['От первой идеи к собственному рабочему пространству','Начните с одной задачи: ваш первый день в продукте','Как превратить интерес в первый шаг','Три причины перестать хранить идеи в заметках','Что подготовить перед началом работы','Новая привычка: доводить идеи до результата'],nurture:['Что осталось за кадром создания продукта','Как мы принимаем решения в команде','Почему для нас важны маленькие детали','Наш подход к обратной связи','Один рабочий принцип, от которого мы не отказываемся','Знакомство с людьми за продуктом'],information:['Что изменилось и почему это важно','Короткий гид по рабочему процессу','Пять ответов на частые вопросы','Что стоит знать перед следующим запуском','Как устроен путь от идеи до публикации','Словарь понятных метрик для команды']};
  const brain=getBrain(),growth=getGrowth();
  const known=brain.knowledge.filter(item=>item.verification==='verified').map(item=>`Разбор: ${item.title}`);
  const events=growth.events.filter(event=>!event.postId).map(event=>`Новость: ${event.title}`);
  const market=growth.observations.filter(item=>item.reactions!==null&&!item.postId).sort((a,b)=>(b.reactions??0)-(a.reactions??0)).map(item=>`Ваш взгляд: ${item.topic}`);
  const learned=Object.values(getLearning().performance).filter(item=>item.registrations>0&&item.topic).sort((a,b)=>b.registrations/Math.max(1,b.views)-a.registrations/Math.max(1,a.views)).slice(0,2).map(item=>`Новый ракурс: ${item.topic}`);
  const source=[...new Set([...events,...known,...market,...learned,...(topics[goal]??topics.information)])];
  return Array.from({length:6},(_,index)=>({title:offset<6?source[(offset+index)%source.length]:`${['Разбор','Практика','За кадром','Чек-лист'][Math.floor(offset/6)%4]}: ${source[(offset+index)%source.length].toLocaleLowerCase('ru-RU')}`,description:[`Показать подход ${brand.name} через понятный пример.`,`Собрать практические шаги для вашей аудитории.`,`Раскрыть одну мысль и пригласить к следующему действию.`][index%3],format:['Пост','Карусель','История'][index%3],number:String(index+1).padStart(2,'0')}));
}

export default function Controller() {
  const {brand,addPost,navigate,notify,setContentFilter,section,setSection}=useWorkspace();
  const [topic,setTopic]=useState(''),[tone,setTone]=useState(preferenceSummary().favoriteTone??brand.tone),[goal,setGoal]=useState(initialGoal);
  const [variants,setVariants]=useState<Variant[]>([]),[activeVariant,setActiveVariant]=useState(0),[text,setText]=useState('');
  const [selectedPlatforms,setSelectedPlatforms]=useState<Platform[]>(['telegram','instagram']),[previewPlatform,setPreviewPlatform]=useState<Platform>('telegram'),[rightTab,setRightTab]=useState<'channels'|'preview'>('channels');
  const [abTest,setAbTest]=useState(false),[revision,setRevision]=useState(0),[ideaOffset,setIdeaOffset]=useState(0),[pendingIdea,setPendingIdea]=useState(''),[saved,setSaved]=useState(false);
  const [generator,setGenerator]=useState<'image'|'video'|null>(null),[attachment,setAttachment]=useState<Post['media']>(),[scriptAttachment,setScriptAttachment]=useState<VideoScript>();
  const [libraryOpen,setLibraryOpen]=useState(false);
  const originalText=useRef('');
  const ideas=useMemo(()=>ideaCollection(goal,brand,ideaOffset),[goal,brand,ideaOffset]);
  const tones=Array.from(new Set([brand.tone,'Дружелюбный','Экспертный','Деловой','Лаконичный','Смелый']));
  const markChanged=()=>setSaved(false);
  function generateText(){if(!topic.trim())return;const words=topic.toLocaleLowerCase('ru-RU').split(/[^\p{L}\p{N}]+/u).filter(w=>w.length>3);const relevance=(fact:string)=>words.filter(word=>fact.toLocaleLowerCase('ru-RU').includes(word)).length;const trusted=verifiedFactsForContent().sort((a,b)=>relevance(b)-relevance(a));const next=createTextVariants(topic,tone,brand,goal,revision+1).map(v=>{const parts=applyPreferences(v.text).split('\n\n');if(trusted.length)parts.splice(Math.max(1,parts.length-1),0,trusted[0]);return {...v,text:applyBrandProtection(parts.join('\n\n'),topic).body};});originalText.current=next[0].text;recordLearning({type:'generation',label:topic,goal,tone});setVariants(next);setText(next[0].text);setActiveVariant(0);setRevision(v=>v+1);markChanged();}
  function selectPlatform(platform:Platform){const next=selectedPlatforms.includes(platform)?selectedPlatforms.filter(p=>p!==platform):[...selectedPlatforms,platform];setSelectedPlatforms(next);if(!next.includes(previewPlatform))setPreviewPlatform(next[0]??platform);markChanged();}
  function openGenerator(kind:'image'|'video') {setGenerator(kind);}
  function saveDrafts(){if(!topic.trim()||!text.trim()||!selectedPlatforms.length)return;learnEdit(originalText.current,text,goal,tone);recordLearning({type:'selection',label:topic,goal,tone,selected:activeVariant,rejected:Math.max(0,variants.length-1)});const base:Partial<Post>={platforms:selectedPlatforms,goal,media:attachment,videoScript:scriptAttachment,format:attachment?.kind==='video'?'Видео':attachment?'Изображение':'Пост'};if(abTest&&variants.length>1){const split=Math.ceil(selectedPlatforms.length/2),first=selectedPlatforms.slice(0,split),last=selectedPlatforms.slice(split);const second=last.length?last:first;const secondText=variants[(activeVariant+1)%variants.length].text;addPost(makePost(`${topic} · A`,{...base,body:text,platformBodies:platformBodies(text,first),platforms:first,abTest:true}));addPost(makePost(`${topic} · B`,{...base,body:secondText,platformBodies:platformBodies(secondText,second),platforms:second,abTest:true}));notify('Варианты A и B сохранены');}else{addPost(makePost(topic,{...base,body:text,platformBodies:platformBodies(text,selectedPlatforms)}));notify('Черновик сохранён');}setSaved(true);}
  const goDrafts=()=>{setContentFilter('draft');navigate('content');};
  const currentPreview=adaptText(text,previewPlatform);
  return <div className="controller-page controller-v3 controller-v4"><div className="page-heading"><h1 className="page-title">Контроллер</h1>{section==='ideas'&&<div className="idea-heading-actions"><Select aria-label="Цель идей" value={goal} onChange={value=>{setGoal(value);setIdeaOffset(0);}} options={goalOptions}/><button className="btn btn-primary" onClick={()=>setIdeaOffset(v=>v+3)}><RefreshCw size={15}/>Новые идеи</button></div>}</div>
    {section==='ideas'?<div className="idea-mosaic">{ideas.map((idea,index)=><button key={`${idea.title}-${index}`} className={`idea-tile idea-tile-${index}`} onClick={()=>setPendingIdea(idea.title)}><div className="idea-tile-top"><span>{idea.format}</span><ArrowUpRight size={20}/></div><div className="idea-tile-art" aria-hidden="true">{index===0?<><i/><i/><i/><span>↗</span></>:index===1?<span>?</span>:index===2?<><b>01</b><b>02</b><b>03</b></>:index===3?<span>→</span>:index===4?<><i/><i/><i/></>:<span>↗</span>}</div><div className="idea-tile-bottom"><span className="idea-tile-number">{idea.number} / {goalLabel(goal)}</span><h2>{idea.title}</h2><span className="idea-tile-action">Создать черновик<ArrowRight size={16}/></span></div></button>)}</div>
    :<div className="creation-layout"><div className="creation-main"><section className="panel creation-topic"><div className="creation-section-title"><h2>Тема публикации</h2><Sparkles size={17}/></div><textarea aria-label="Тема публикации" className="creation-topic-input" value={topic} maxLength={180} rows={2} onChange={e=>{setTopic(e.target.value);markChanged();}} placeholder="О чём расскажем?"/><div className="creation-brief-options"><div><span>Цель</span><Select aria-label="Цель публикации" value={goal} onChange={value=>{setGoal(value);markChanged();}} options={goalOptions}/></div><div><span>Тон</span><Select aria-label="Тон публикации" value={tone} onChange={value=>{setTone(value);markChanged();}} options={tones.map(value=>({value,label:value}))}/></div></div></section>
      <section className="panel creation-text"><div className="creation-section-title"><h2>Текст</h2><button className="btn btn-ghost" disabled={!topic.trim()} onClick={generateText}><WandSparkles size={15}/>{variants.length?'Перегенерировать':'Сгенерировать'}</button></div>{variants.length>0&&<div className="creation-variants" role="group" aria-label="Варианты текста">{variants.map((variant,index)=><button key={index} aria-pressed={activeVariant===index} className={activeVariant===index?'active':''} onClick={()=>{setActiveVariant(index);setText(variant.text);originalText.current=variant.text;markChanged();}}>Вариант {index+1}</button>)}</div>}<textarea aria-label="Текст публикации" value={text} onChange={e=>{setText(e.target.value);setVariants(values=>values.map((v,i)=>i===activeVariant?{...v,text:e.target.value}:v));markChanged();}} placeholder="Напишите текст или сгенерируйте первый вариант" className="creation-body"/><div className="creation-text-footer"><span>{text.length.toLocaleString('ru-RU')} символов</span><button className="icon-button" disabled={!text} aria-label="Копировать текст" onClick={()=>void navigator.clipboard.writeText(text).then(()=>notify('Текст скопирован'),()=>notify('Не удалось скопировать'))}><Copy size={14}/></button></div></section>
      <ContentHealth title={topic} body={text} media={attachment} goal={goal} onChange={value=>{setText(value);markChanged();}}/><section className="panel creation-media"><div className="creation-section-title"><h2>Креативы</h2>{attachment&&<button className="icon-button" aria-label="Удалить вложение" onClick={()=>{setAttachment(undefined);setScriptAttachment(undefined);markChanged();}}><X size={15}/></button>}</div><button className="text-button" onClick={()=>setLibraryOpen(true)}>Выбрать из медиатеки<ArrowUpRight size={15}/></button><div className="creation-media-options">{([{kind:'image',label:'Изображение',icon:Image},{kind:'video',label:'Видео',icon:Film}] as const).map(({kind,label,icon:Icon})=><button key={kind} role="checkbox" aria-checked={attachment?.kind===kind} aria-label={`Добавить ${label.toLowerCase()}`} className={attachment?.kind===kind?'selected':''} onClick={()=>{if(attachment?.kind===kind){setAttachment(undefined);setScriptAttachment(undefined);markChanged();}else openGenerator(kind);}}><span className="media-check">{attachment?.kind===kind&&<Check size={12}/>}</span><Icon size={19}/><span>{label}</span><Plus size={15}/></button>)}</div>{attachment&&<button className="creation-attached" onClick={()=>openGenerator(attachment.kind)}>{attachment.kind==='image'?<img src={attachment.url} alt="Вложенный визуал"/>:<Film size={27}/>}<span><strong>{attachment.kind==='image'?'Визуал к публикации':'Видео к публикации'}</strong><small>{attachment.format.toUpperCase()}</small></span><ArrowUpRight size={17}/></button>}</section></div>
      <aside className="creation-side"><section className="panel creation-publishing"><div className="creation-side-tabs" role="group" aria-label="Настройка публикации"><button className={rightTab==='channels'?'active':''} aria-pressed={rightTab==='channels'} onClick={()=>setRightTab('channels')}>Площадки</button><button className={rightTab==='preview'?'active':''} aria-pressed={rightTab==='preview'} onClick={()=>setRightTab('preview')}>Предпросмотр</button></div>{rightTab==='channels'?<><div className="creation-channels">{platforms.map(platform=><button className={selectedPlatforms.includes(platform)?'selected':''} key={platform} aria-pressed={selectedPlatforms.includes(platform)} onClick={()=>selectPlatform(platform)}><PlatformIcon platform={platform} size={31}/><span>{platformMeta[platform].name}</span><span className="media-check">{selectedPlatforms.includes(platform)&&<Check size={12}/>}</span></button>)}</div><div className="creation-ab"><span>A/B-тест</span><button role="switch" aria-checked={abTest} aria-label="Подготовить A/B-тест" className={`controller-switch ${abTest?'on':''}`} onClick={()=>{setAbTest(!abTest);markChanged();}}><span/></button></div></>:<div className="creation-preview"><Select aria-label="Площадка предпросмотра" value={previewPlatform} onChange={value=>setPreviewPlatform(value as Platform)} options={platforms.map(value=>({value,label:platformMeta[value].name}))}/><SocialPreview platform={previewPlatform} body={currentPreview} title={topic} visual={attachment} brandName={brand.name}/></div>}<div className="creation-save"><button className="btn btn-primary" disabled={saved||!topic.trim()||!text.trim()||!selectedPlatforms.length||(abTest&&variants.length<2)} onClick={saveDrafts}>{saved?<Check size={16}/>:<FileText size={16}/>} {saved?'Сохранено':abTest?'Сохранить A и B':'Сохранить черновик'}</button>{saved&&<button className="text-button" onClick={goDrafts}>Открыть черновики<ArrowRight size={14}/></button>}</div></section></aside></div>}
    {libraryOpen&&<AssetPicker onClose={()=>setLibraryOpen(false)} onSelect={async(asset,blob)=>{try{const url=await blobToDataURL(blob);setAttachment({kind:asset.kind==='video'?'video':'image',url,format:asset.name.split('.').at(-1)||asset.mime});setScriptAttachment(undefined);setLibraryOpen(false);markChanged();}catch{notify('Не удалось добавить материал');}}}/>}
    {pendingIdea&&<Modal title="Создать черновик?" onClose={()=>setPendingIdea('')}><div className="idea-confirm"><span className="idea-confirm-mark"><Sparkles size={23}/></span><p>Тема:</p><h3>«{pendingIdea}»</h3><div><button className="btn btn-ghost" onClick={()=>setPendingIdea('')}>Отмена</button><button className="btn btn-primary" onClick={()=>{setTopic(pendingIdea);setText('');setVariants([]);setAttachment(undefined);setScriptAttachment(undefined);setSaved(false);setPendingIdea('');setSection('create');}}>Создать<ArrowRight size={15}/></button></div></div></Modal>}
    {generator&&<CreativeGenerator kind={generator} topic={topic} postText={text} onClose={()=>setGenerator(null)} onAdd={(media,script)=>{setAttachment(media);setScriptAttachment(script);markChanged();}}/>}
  </div>;
}
