import type { Post } from './model';
import { readWorkspace, saveWorkspace } from './runtime';
export interface LearningEvent {id:string;at:string;type:'generation'|'selection'|'edit'|'performance';label:string;beforeLength?:number;afterLength?:number;goal?:string;tone?:string;selected?:number;rejected?:number}
export interface LearningState {events:LearningEvent[];performance:Record<string,{views:number;clicks:number;registrations:number;reactions:number;topic:string;format:string;length:number}>}
export function getLearning():LearningState {return readWorkspace('learning-v1',{events:[],performance:{}});}
function persist(value:LearningState){try{saveWorkspace('learning-v1',value);window.dispatchEvent(new Event('workspace-learning'));}catch{/* Keep editing available if local storage is full. */}}
export function recordLearning(event:Omit<LearningEvent,'id'|'at'>){const state=getLearning();state.events=[{...event,id:crypto.randomUUID(),at:new Date().toISOString()},...state.events].slice(0,300);persist(state);}
export function learnEdit(original:string,final:string,goal?:string,tone?:string){if(original.trim()===final.trim()||!original.trim())return;recordLearning({type:'edit',label:'Правки команды',beforeLength:original.length,afterLength:final.length,goal,tone});}
export function learnPerformance(posts:Post[]){const state=getLearning();let changed=0;const ids=new Set(posts.filter(p=>p.status==='published').map(p=>p.id));for(const id of Object.keys(state.performance)){if(!ids.has(id)){delete state.performance[id];changed++;}}for(const p of posts.filter(p=>p.status==='published')){const current={views:p.views,clicks:p.clicks,registrations:p.registrations,reactions:p.reactions,topic:p.topic,format:p.format,length:p.body.length};if(JSON.stringify(state.performance[p.id])!==JSON.stringify(current)){state.performance[p.id]=current;changed++;}}if(changed){state.events=[{id:crypto.randomUUID(),at:new Date().toISOString(),type:'performance' as const,label:`Обновлены результаты: ${changed} публикаций`},...state.events].slice(0,300);persist(state);}}
export function preferenceSummary(){const state=getLearning();const edits=state.events.filter(e=>e.type==='edit'&&e.beforeLength&&e.afterLength);const averageRatio=edits.length?edits.reduce((n,e)=>n+e.afterLength!/e.beforeLength!,0)/edits.length:1;const tones=state.events.filter(e=>e.type==='selection'&&e.tone).map(e=>e.tone!);const favoriteTone=tones.length?[...new Set(tones)].sort((a,b)=>tones.filter(t=>t===b).length-tones.filter(t=>t===a).length)[0]:null;return {edits:edits.length,averageRatio,favoriteTone,preferShort:edits.length>=2&&averageRatio<.8};}
export function applyPreferences(text:string){const prefs=preferenceSummary();if(!prefs.preferShort)return text;const parts=text.split('\n\n');return parts.length>5?[...parts.slice(0,4),parts.at(-1)].join('\n\n'):text;}
