import {useEffect,useState} from 'react';
import {Bell,Check,TrendingUp,ShieldCheck,X} from 'lucide-react';
import {useWorkspace} from './store';
import {getGrowth} from './growth-data';
import {getCurrentAccount} from './billing-data';
import {isLabrika,readWorkspace,saveWorkspace} from './runtime';
interface Notice{id:string;title:string;detail:string;postId?:string;kind:'system'|'milestone'}
export default function NotificationCenter({open,onToggle,onClose}:{open:boolean;onToggle:()=>void;onClose:()=>void}){
 const {posts,openEditor,navigate}=useWorkspace();const [dismissed,setDismissed]=useState<string[]>(()=>readWorkspace('dismissed-notices',[]));const [,refresh]=useState(0);
 useEffect(()=>{const sync=()=>{setDismissed(readWorkspace('dismissed-notices',[]));refresh(n=>n+1);};window.addEventListener('storage',sync);window.addEventListener('growth-data-change',sync);window.addEventListener('labrika-account-change',sync);return()=>{window.removeEventListener('storage',sync);window.removeEventListener('growth-data-change',sync);window.removeEventListener('labrika-account-change',sync);};},[]);
 const notices:Notice[]=posts.filter(p=>p.status==='published'&&p.views>=10000).map(p=>{const milestone=[1000000,500000,100000,50000,10000].find(v=>p.views>=v)!;return{id:`views:${p.id}:${milestone}`,kind:'milestone' as const,title:`${milestone.toLocaleString('ru-RU')} просмотров`,detail:p.title,postId:p.id};}).sort((a,b)=>(posts.find(p=>p.id===b.postId)?.views??0)-(posts.find(p=>p.id===a.postId)?.views??0));
 const growth=getGrowth();const queue=posts.filter(p=>growth.autopilot.queueIds.includes(p.id)&&p.status==='draft').length;
 if(queue)notices.unshift({id:`autopilot:${growth.autopilot.lastWeek}`,title:'План недели готов',detail:`На согласовании: ${queue}`,kind:'system'});
 const account=isLabrika?getCurrentAccount():null;const end=account?.subscription?.expiresAt;
 if(end){const days=Math.ceil((Date.parse(end)-Date.now())/86400000);if(days<=7)notices.unshift({id:`subscription:${end}:${days<=0?'expired':'soon'}`,title:days<=0?'Подписка завершилась':'Подписка скоро завершится',detail:days<=0?'Выберите тариф для следующего месяца':`До ${new Date(end).toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}`,kind:'system'});}
 const unread=notices.filter(n=>!dismissed.includes(n.id));
 const dismiss=(ids:string[])=>{const next=[...new Set([...dismissed,...ids])].slice(-500);saveWorkspace('dismissed-notices',next);setDismissed(next);};
 return <div className="notifications-wrapper"><button className={`icon-button notification-button ${open?'is-open':''} ${unread.length?'has-unread':''}`} onClick={onToggle} aria-label="Уведомления" aria-expanded={open}><Bell size={19} strokeWidth={1.6}/>{unread.length>0&&<i/>}</button>{open&&<><button className="popover-dismiss" aria-label="Закрыть уведомления" onClick={onClose}/><div className="notification-popover" role="region" aria-label="Важные уведомления"><div className="popover-heading"><strong>Уведомления</strong>{unread.length>0&&<button className="icon-button" aria-label="Отметить всё прочитанным" onClick={()=>dismiss(unread.map(n=>n.id))}><Check size={16}/></button>}</div>{unread.slice(0,8).map(n=><div className="notification-item" key={n.id}><span>{n.kind==='milestone'?<TrendingUp size={15}/>:<ShieldCheck size={15}/>}</span><div><button style={{textAlign:'left'}} onClick={()=>{dismiss([n.id]);onClose();if(n.postId){const post=posts.find(p=>p.id===n.postId);if(post)openEditor(post);}else navigate(n.id.startsWith('subscription:')?'billing':'autopilot');}}><strong>{n.title}</strong><small>{n.detail}</small></button></div><button aria-label={`Прочитано: ${n.title}`} onClick={()=>dismiss([n.id])}><X size={13}/></button></div>)}{!unread.length&&<div className="notification-empty"><Bell size={23}/>Всё спокойно. Вы ничего не пропустили.</div>}</div></>}</div>;
}
