import {useEffect,useState} from 'react';
import {Check,KeyRound,Loader2,LockKeyhole,PlugZap,Trash2} from 'lucide-react';
import {Select} from './ui';
import {edition} from './runtime';
import './provider-settings.css';
type Product='labrika'|'ygroup';
type Provider='openai'|'higgsfield';
interface ProviderState {configured:boolean;status:'disconnected'|'saved'|'verified'|'error';checkedAt:string|null;textModel?:string;imageModel?:string;videoModel?:string}
interface Settings {edition:Product;openai:ProviderState;higgsfield:ProviderState;encoder:boolean;videoModels:string[];capabilities:{text:boolean;image:boolean;video:boolean}}
const keyStorage=(product:Product)=>`${product}:provider-admin-unlock`;
const statusLabel={disconnected:'Не подключён',saved:'Ключ сохранён',verified:'Доступ проверен',error:'Проверьте доступ'};
export default function ProviderSettings({product=edition}:{product?:Product}){
 const [issuer,setIssuer]=useState(()=>sessionStorage.getItem(keyStorage(product))||'');
 const [settings,setSettings]=useState<Settings|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [openai,setOpenai]=useState({apiKey:'',textModel:'gpt-6-astra',imageModel:'gpt-image-2.5-flare'});
 const [higgsfield,setHiggsfield]=useState({keyId:'',keySecret:'',videoModel:'bytedance/seedance-2.0/image-to-video'});
 async function request(action='',method='GET',input?:unknown){const response=await fetch(`/api/ai/providers/${product}${action}`,{method,headers:{'Content-Type':'application/json','X-Approval-Key':issuer},...(input===undefined?{}:{body:JSON.stringify(input)})});let data;try{data=await response.json();}catch{throw new Error('Сервер недоступен. Обновите страницу.');}if(!response.ok)throw new Error(data.error||'Не удалось сохранить подключение');return data as Settings;}
 async function unlock(){if(!issuer.trim())return;setBusy('unlock');setError('');try{const data=await request();setSettings(data);setOpenai(v=>({...v,textModel:data.openai.textModel||v.textModel,imageModel:data.openai.imageModel||v.imageModel}));setHiggsfield(v=>({...v,videoModel:data.higgsfield.videoModel||v.videoModel}));sessionStorage.setItem(keyStorage(product),issuer);}catch(e){setError(e instanceof Error?e.message:'Не удалось открыть настройки');sessionStorage.removeItem(keyStorage(product));}finally{setBusy('');}}
 useEffect(()=>{if(issuer)void unlock();},[product]);
 async function save(provider:Provider){setBusy(`save-${provider}`);setError('');setNotice('');try{const input=provider==='openai'?openai:higgsfield;const data=await request('','PUT',{[provider]:input});setSettings(data);if(provider==='openai')setOpenai(v=>({...v,apiKey:''}));else setHiggsfield(v=>({...v,keyId:'',keySecret:''}));setNotice('Настройки сохранены');}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить');}finally{setBusy('');}}
 async function check(provider:Provider){setBusy(`check-${provider}`);setError('');setNotice('');try{setSettings(await request('/check','POST',{provider}));setNotice('Доступ проверен');}catch(e){setError(e instanceof Error?e.message:'Не удалось проверить');try{setSettings(await request());}catch{/* Preserve the form while the server is unavailable. */}}finally{setBusy('');}}
 async function remove(provider:Provider){setBusy(`remove-${provider}`);setError('');try{setSettings(await request(`/${provider}`,'DELETE'));setNotice('Подключение отключено');}catch(e){setError(e instanceof Error?e.message:'Не удалось отключить');}finally{setBusy('');}}
 return <div className="provider-settings">
  {!settings?<form className="provider-unlock" onSubmit={e=>{e.preventDefault();void unlock();}}><span className="provider-symbol"><LockKeyhole size={23}/></span><h2>Управление генерацией</h2><label>Ключ управления сервером<input type="password" autoComplete="off" value={issuer} onChange={e=>setIssuer(e.target.value)} placeholder="Ключ администратора" required/></label><p>Используйте ключ из файла .data/approval-issuer.key на этом компьютере.</p><button className="btn btn-primary" disabled={!!busy}>{busy?<Loader2 size={16} className="provider-spinner"/>:<KeyRound size={16}/>}Открыть настройки</button></form>:<>
   <div className="provider-settings-toolbar"><span><LockKeyhole size={15}/>Ключи хранятся на сервере</span><button className="btn btn-ghost" onClick={()=>{sessionStorage.removeItem(keyStorage(product));setSettings(null);setIssuer('');setOpenai(v=>({...v,apiKey:''}));setHiggsfield(v=>({...v,keyId:'',keySecret:''}));}}>Закрыть доступ</button></div>
   <div className="provider-settings-grid">
    <section className="provider-card"><div className="provider-card-heading"><h2>OpenAI API</h2><span className={`provider-state provider-state-${settings.openai.status}`}>{statusLabel[settings.openai.status]}</span></div><p>Тексты, идеи, изображения и помощник.</p><form onSubmit={e=>{e.preventDefault();void save('openai');}}><label>API Key<input type="password" autoComplete="new-password" value={openai.apiKey} onChange={e=>setOpenai(v=>({...v,apiKey:e.target.value}))} placeholder={settings.openai.configured?'Оставьте пустым, чтобы сохранить ключ':'sk-…'} required={!settings.openai.configured}/></label><label>Модель для текста<input value={openai.textModel} onChange={e=>setOpenai(v=>({...v,textModel:e.target.value}))} required spellCheck={false}/></label><label>Модель для изображений<input value={openai.imageModel} onChange={e=>setOpenai(v=>({...v,imageModel:e.target.value}))} required spellCheck={false}/></label><div className="provider-actions"><button className="btn btn-primary" disabled={!!busy}>{busy==='save-openai'?<Loader2 size={15} className="provider-spinner"/>:<Check size={15}/>}Сохранить</button><button type="button" className="btn btn-outline" onClick={()=>void check('openai')} disabled={!!busy||!settings.openai.configured}>{busy==='check-openai'?<Loader2 size={15} className="provider-spinner"/>:<PlugZap size={15}/>}Проверить</button>{settings.openai.configured&&<button type="button" className="icon-button" onClick={()=>void remove('openai')} disabled={!!busy} aria-label="Отключить OpenAI"><Trash2 size={16}/></button>}</div></form><a href="https://platform.openai.com/api-keys" target="_blank" rel="noreferrer">Получить API-ключ ↗</a></section>
    <section className="provider-card"><div className="provider-card-heading"><h2>Higgsfield</h2><span className={`provider-state provider-state-${settings.higgsfield.status}`}>{statusLabel[settings.higgsfield.status]}</span></div><p>Анимация сцен и видео со звуком.</p><form onSubmit={e=>{e.preventDefault();void save('higgsfield');}}><label>Key ID<input type="password" autoComplete="new-password" value={higgsfield.keyId} onChange={e=>setHiggsfield(v=>({...v,keyId:e.target.value}))} placeholder={settings.higgsfield.configured?'Ключ сохранён':'Key ID'} required={!settings.higgsfield.configured}/></label><label>Key Secret<input type="password" autoComplete="new-password" value={higgsfield.keySecret} onChange={e=>setHiggsfield(v=>({...v,keySecret:e.target.value}))} placeholder={settings.higgsfield.configured?'Оставьте пустым, чтобы сохранить':'Key Secret'} required={!settings.higgsfield.configured}/></label><label>Видеомодель<Select aria-label="Видеомодель" value={higgsfield.videoModel} onChange={videoModel=>setHiggsfield(v=>({...v,videoModel}))} options={settings.videoModels.map(value=>({value,label:value.startsWith('bytedance/')?'Seedance 2.0 · со звуком':'Wan 2.7'}))}/></label><div className="provider-actions"><button className="btn btn-primary" disabled={!!busy}>{busy==='save-higgsfield'?<Loader2 size={15} className="provider-spinner"/>:<Check size={15}/>}Сохранить</button><button type="button" className="btn btn-outline" onClick={()=>void check('higgsfield')} disabled={!!busy||!settings.higgsfield.configured}>{busy==='check-higgsfield'?<Loader2 size={15} className="provider-spinner"/>:<PlugZap size={15}/>}Проверить</button>{settings.higgsfield.configured&&<button type="button" className="icon-button" onClick={()=>void remove('higgsfield')} disabled={!!busy} aria-label="Отключить Higgsfield"><Trash2 size={16}/></button>}</div></form><a href="https://open.higgsfield.ai/keys" target="_blank" rel="noreferrer">Получить API-ключ ↗</a></section>
   </div>
   {!settings.encoder&&<p className="provider-error">Для сборки видео установите FFmpeg на сервере.</p>}
  </>}
  {error&&<p role="alert" className="provider-error">{error}</p>}{notice&&<p role="status" className="provider-notice"><Check size={15}/>{notice}</p>}
 </div>;
}
