import { workspaceKey, productName, isLabrika, basePath } from './runtime';
import { useState } from 'react';
import { ArrowDownToLine, ArrowUpRight, Check, Images, Database, Link2, ShieldCheck } from 'lucide-react';
import { useWorkspace } from './store';
import { platformMeta } from './model';
import AssetLibrary from './AssetLibrary';
import type { Platform } from './model';
import { Avatar, Modal, PlatformIcon, Select } from './ui';

type Configuration={account:string;clientId:string};
const readConnections=():Partial<Record<Platform,Configuration>>=>{try{return JSON.parse(localStorage.getItem(workspaceKey('ygroup-connections-v1'))??'{}');}catch{return {};}};
export default function Settings() {
  const [libraryOpen,setLibraryOpen]=useState(false);
  const {brand,setBrand,notify,section,posts,profile,navigate}=useWorkspace();
  const [draft,setDraft]=useState(brand),[connections,setConnections]=useState(readConnections),[connection,setConnection]=useState<Platform|null>(null),[config,setConfig]=useState<Configuration>({account:'',clientId:''});
  const exportWorkspace=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),brand,profile,posts,connections},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${productName.toLowerCase()}-workspace.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Копия пространства скачана');};
  return <><div className="page-heading"><h1 className="page-title">Настройки</h1>{section==='company'&&<button className="btn btn-primary" onClick={()=>{if(!draft.name.trim()){notify('Добавьте название компании');return;}setBrand(draft);notify('Настройки компании сохранены');}}><Check size={16}/>Сохранить</button>}</div>
    {section==='company'&&<div className="settings-v3-grid"><section className="panel settings-form-card"><h2>Компания</h2><label className="field">Название<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="field">Аудитория<input value={draft.audience} onChange={e=>setDraft({...draft,audience:e.target.value})}/></label><label className="field">Тон коммуникации<Select aria-label="Тон компании" value={draft.tone} onChange={tone=>setDraft({...draft,tone})} options={['Дружелюбный','Экспертный','Вдохновляющий','Деловой'].map(tone=>({value:tone,label:tone}))}/></label><label className="field">Редакционные правила<textarea rows={6} value={draft.rules} onChange={e=>setDraft({...draft,rules:e.target.value})}/></label></section><section className="panel settings-brand-note"><span className="brand-sample-mark">{draft.name.slice(0,1)||'Y'}</span><h2>{draft.name||'Компания'}</h2><span>{draft.tone} тон</span><div className="brand-rule-sample">{draft.rules}</div><button className="text-button" onClick={()=>navigate('controller')}>Открыть контроллер<ArrowUpRight size={15}/></button></section></div>}
    {section==='social'&&<><div className="social-connections-grid">{(Object.keys(platformMeta) as Platform[]).map(platform=><section className="panel social-connection" key={platform}><div><PlatformIcon platform={platform} size={42}/><span className="connection-state"><i/>Не подключено</span></div><h2>{platformMeta[platform].name}</h2><span className="connection-account">{connections[platform]?.account||'Аккаунт не выбран'}</span><button className="btn" onClick={()=>{setConfig(connections[platform]??{account:'',clientId:''});setConnection(platform);}}><Link2 size={15}/>{connections[platform]?'Параметры API':'Настроить API'}<ArrowUpRight size={14}/></button></section>)}</div><p className="settings-api-note"><ShieldCheck size={15}/>Авторизация и синхронизация станут доступны после подключения сервера.</p></>}
    {section==='workspace'&&<><button className="workspace-library-card" onClick={()=>setLibraryOpen(true)}><span><Images size={23}/></span><div><strong>Медиатека</strong><small>Материалы компании и созданные креативы</small></div><ArrowUpRight size={19}/></button><div className="settings-v3-grid"><section className="panel settings-form-card workspace-storage"><span className="storage-icon"><Database size={24}/></span><h2>Данные пространства</h2><div className="workspace-stats"><div><strong>{posts.length}</strong><span>публикаций</span></div><div><strong>{new Blob([JSON.stringify(posts)]).size>1048576?`${(new Blob([JSON.stringify(posts)]).size/1048576).toFixed(1)} МБ`:`${Math.round(new Blob([JSON.stringify(posts)]).size/1024)} КБ`}</strong><span>в этом браузере</span></div></div><div className="storage-status"><i/>Автосохранение включено</div><button className="btn btn-primary" onClick={exportWorkspace}><ArrowDownToLine size={16}/>Скачать копию</button></section><section className="panel workspace-profile"><Avatar name={profile.name} size={56}/><h2>{profile.name}</h2><span>{profile.role}</span><button className="text-button" onClick={()=>navigate('profile')}>Открыть профиль<ArrowUpRight size={15}/></button>{isLabrika&&<a className="text-button" href={`${basePath}/admin`}>Администрирование<ArrowUpRight size={15}/></a>}</section></div></>}
    {libraryOpen&&<Modal title="Медиатека" onClose={()=>setLibraryOpen(false)} wide><div className="workspace-library"><AssetLibrary/></div></Modal>}
    {connection&&<Modal title={`${platformMeta[connection].name} · API`} onClose={()=>setConnection(null)}><form className="settings-connection-form" onSubmit={e=>{e.preventDefault();const next={...connections,[connection]:config};setConnections(next);localStorage.setItem(workspaceKey('ygroup-connections-v1'),JSON.stringify(next));setConnection(null);notify('Параметры API сохранены');}}><label className="field">{connection==='telegram'?'Канал · @username или ID':'Аккаунт или ID сообщества'}<input required value={config.account} onChange={e=>setConfig({...config,account:e.target.value})} placeholder={connection==='telegram'?'@labrika':'labrika'}/></label><label className="field">ID приложения<input value={config.clientId} onChange={e=>setConfig({...config,clientId:e.target.value})} placeholder="Client ID"/></label><p>Здесь сохраняются параметры подключения. Секретные ключи и авторизация — на сервере.</p><button className="btn btn-primary" type="submit"><Check size={15}/>Сохранить параметры</button></form></Modal>}
  </>;
}
export function Profile() {
  const {profile,setProfile,notify}=useWorkspace();const [draft,setDraft]=useState(profile);
  return <><div className="page-heading"><h1 className="page-title">Профиль</h1></div><form className="panel profile-form" onSubmit={e=>{e.preventDefault();try{setProfile({...draft,name:draft.name.trim()});notify('Профиль сохранён');}catch(error){notify(error instanceof Error?error.message:'Не удалось сохранить профиль');}}}><div className="profile-form-avatar"><Avatar name={draft.name} size={68}/><span>{draft.role}</span></div><label className="field">Имя<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="field">Почта<input type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})} placeholder="name@company.ru"/></label><button className="btn btn-primary" type="submit"><Check size={16}/>Сохранить</button></form></>;
}
