import {useEffect,useState} from 'react';
import {ArrowUpRight,Check,ChevronDown,ExternalLink,Link2,LoaderCircle,RefreshCw,Send,Trash2} from 'lucide-react';
import {Modal,PlatformIcon} from './ui';
import {platformMeta,makePost} from './model';
import type {Platform,Post} from './model';
import {useWorkspace} from './store';
import {useTeamAccess} from './team-data';
import {checkConnection,connectionsChanged,deleteConnection,listConnections,saveConnection} from './social-api';
import type {SocialConfig,SocialConnection} from './social-api';
import PublishDialog from './PublishDialog';
import './social-connections.css';
const guides:Record<Platform,{intro:string;steps:string[];url:string}>={
 telegram:{intro:'Бот с правом публиковать в вашем канале',steps:['Создайте бота через @BotFather и скопируйте токен.','Добавьте бота в канал администратором с правом публиковать сообщения.','Укажите @имя канала или его числовой ID и токен бота.'],url:'https://core.telegram.org/bots/features#creating-a-new-bot'},
 vk:{intro:'Сообщество и токен пользователя с правом записи',steps:['Создайте приложение VK и получите токен пользователя с разрешениями wall, photos и groups.','Пользователь должен быть администратором или редактором сообщества.','Укажите числовой ID сообщества и токен.'],url:'https://dev.vk.com/ru/api/access-token/getting-started'},
 instagram:{intro:'Профессиональный аккаунт Instagram',steps:['Используйте Instagram API with Instagram Login в приложении Meta.','Получите токен с разрешениями instagram_business_basic и instagram_business_content_publish.','Укажите ID профессионального аккаунта. Для публикации нужен медиафайл по публичной HTTPS-ссылке.'],url:'https://www.postman.com/meta/instagram/folder/6raa77c/instagram-api-with-instagram-login'},
 threads:{intro:'Аккаунт Threads и доступ к публикациям',steps:['Создайте приложение Meta для Threads и авторизуйте аккаунт.','Получите токен с разрешениями threads_basic и threads_content_publish.','Текст можно отправить сразу. Изображения и видео должны быть доступны по публичной HTTPS-ссылке.'],url:'https://www.postman.com/meta/threads/documentation/dht3nzz/threads-api'},
 youtube:{intro:'Канал YouTube через OAuth',steps:['Включите YouTube Data API v3 в Google Cloud и настройте OAuth.','Авторизуйте канал с разрешением youtube.upload и youtube.readonly.','Вставьте access token. Для обновления доступа добавьте данные OAuth ниже. Видео непроверенного API-проекта могут оставаться приватными.'],url:'https://developers.google.com/youtube/v3/guides/authentication'},
 max:{intro:'Бот MAX в канале или групповом чате',steps:['Создайте бота на платформе MAX для партнёров и получите его токен.','Добавьте бота администратором канала с правом публикации.','Укажите числовой chat_id из MAX API и токен бота.'],url:'https://dev.max.ru/docs-api'},
 tiktok:{intro:'TikTok через Content Posting API',steps:['Создайте приложение в TikTok for Developers и включите Content Posting API / Direct Post.','Авторизуйте аккаунт с разрешениями user.info.basic и video.publish, затем вставьте access token.','До проверки приложения TikTok ограничивает публикации приватной видимостью. Видимость выбирается отдельно перед каждой отправкой.'],url:'https://developers.tiktok.com/doc/content-posting-api-get-started/'},
 dzen:{intro:'Публикация через студию Дзена',steps:['Открытого подключения для публикаций в этой версии нет.','Подготовьте материал в редакторе и перенесите его в студию Дзена.'],url:'https://dzen.ru'}
};
export default function SocialConnections(){
 const {notify,brand}=useWorkspace();const {can}=useTeamAccess();const canManage=can('manageSocial'),canPublish=can('schedulePosts');const [connections,setConnections]=useState<SocialConnection[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[platform,setPlatform]=useState<Platform|null>(null),[config,setConfig]=useState<SocialConfig>({token:'',account:''}),[editing,setEditing]=useState(false),[busy,setBusy]=useState(''),[modalError,setModalError]=useState(''),[testPost,setTestPost]=useState<Post|null>(null);
 useEffect(()=>{let active=true;const load=()=>{void listConnections().then(value=>{if(active){setConnections(value);setError('');}},e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});};load();window.addEventListener('social-connections-change',load);return()=>{active=false;window.removeEventListener('social-connections-change',load);};},[]);
 const connected=connections.find(c=>c.platform===platform);
 const open=(next:Platform)=>{if(!canManage&&next!=='dzen')return;const saved=connections.find(c=>c.platform===next);setPlatform(next);setEditing(!saved);setConfig({token:'',account:saved?.accountId||''});setModalError('');};
 async function save(){if(!canManage||!platform||busy)return;setBusy('save');setModalError('');try{await saveConnection(platform,config);connectionsChanged();setPlatform(null);setConfig({});notify('Подключение проверено и сохранено');}catch(e){setModalError(e instanceof Error?e.message:'Не удалось подключить');}finally{setBusy('');}}
 async function check(){if(!canManage||!platform||busy)return;setBusy('check');setModalError('');try{const result=await checkConnection(platform);setConnections(list=>list.map(item=>item.platform===platform?result.connection:item));connectionsChanged();notify('Подключение работает');}catch(e){setModalError(e instanceof Error?e.message:'Не удалось проверить доступ');connectionsChanged();}finally{setBusy('');}}
 async function remove(){if(!canManage||!platform||busy)return;setBusy('remove');setModalError('');try{await deleteConnection(platform);connectionsChanged();setPlatform(null);notify('Подключение удалено');}catch(e){setModalError(e instanceof Error?e.message:'Не удалось отключить');}finally{setBusy('');}}
 return <><div className="social-connections-grid social-live-grid">{(Object.keys(platformMeta) as Platform[]).map(p=>{const c=connections.find(value=>value.platform===p);return <section className="panel social-connection" key={p}><div><PlatformIcon platform={p} size={42}/><span className={`connection-state ${c?.status==='connected'?'is-connected':c?'is-error':''}`}><i/>{loading?'Проверяем…':c?.status==='connected'?'Подключено':c?'Проверьте доступ':p==='dzen'?'Вручную':'Не подключено'}</span></div><h2>{platformMeta[p].name}</h2><span className="connection-account">{c?.accountName||guides[p].intro}</span><button disabled={!canManage&&p!=='dzen'} className="btn" onClick={()=>open(p)}><Link2 size={15}/>{c?'Управлять':p==='dzen'?'Как опубликовать':'Подключить'}<ArrowUpRight size={14}/></button></section>;})}</div>{error&&<p role="alert" className="social-form-error">{error}<button onClick={()=>{setLoading(true);connectionsChanged();}}>Повторить</button></p>}
 {platform&&(canManage||platform==='dzen')&&<Modal title={platformMeta[platform].name} onClose={()=>{if(!busy){setPlatform(null);setConfig({});}}}><div className="social-connect-form">
  {platform==='dzen'?<><p>{guides.dzen.intro}</p><p className="social-help-copy">{guides.dzen.steps.join(' ')}</p><a className="btn btn-primary" href={guides.dzen.url} target="_blank" rel="noreferrer">Открыть Дзен<ExternalLink size={15}/></a></>:<>
  {connected&&!editing?<><div className="social-account-card"><PlatformIcon platform={platform} size={40}/><div><strong>{connected.accountName}</strong><span>{connected.accountHandle||connected.accountId}</span></div><span className={connected.status==='connected'?'social-account-ready':'social-account-error'}>{connected.status==='connected'?<Check size={16}/>:<RefreshCw size={16}/>}</span></div>{connected.error&&<p className="social-form-error">{connected.error}</p>}<div className="social-manage-actions"><button className="btn" disabled={!!busy} onClick={()=>void check()}>{busy==='check'?<LoaderCircle className="spin" size={15}/>:<RefreshCw size={15}/>}Проверить доступ</button><button className="btn btn-primary" disabled={!canPublish||!!busy||connected.status!=='connected'} onClick={()=>{setTestPost(makePost('Проверка подключения',{body:`${brand.name} — проверка публикации из рабочего пространства.`,platforms:[platform]}));setPlatform(null);}}><Send size={15}/>Проверить постинг</button></div><div className="social-manage-footer"><button className="text-button" onClick={()=>setEditing(true)}>Заменить ключи</button><button className="text-button" disabled={!!busy} onClick={()=>void remove()}><Trash2 size={14}/>Отключить</button></div></>:<form onSubmit={event=>{event.preventDefault();void save();}}>
   <p className="social-form-intro">{guides[platform].intro}</p>
   {!['threads','youtube','tiktok'].includes(platform)&&<label className="field">{platform==='max'?'ID канала MAX':platform==='telegram'?'Канал · @username или ID':platform==='vk'?'ID сообщества':'ID аккаунта'}<input required autoComplete="off" spellCheck={false} value={config.account||''} placeholder={platform==='max'?'-123456789':platform==='telegram'?'@channel':platform==='vk'?'12345678':'17841400000000000'} onChange={e=>setConfig(c=>({...c,account:e.target.value}))}/></label>}
   <label className="field">{['telegram','max'].includes(platform)?'Токен бота':platform==='vk'?'Токен пользователя':'Access token'}<input required={!['youtube','tiktok'].includes(platform)||!config.refreshToken} type="password" autoComplete="new-password" spellCheck={false} value={config.token||''} placeholder={platform==='telegram'?'123456789:AA…':'Вставьте токен доступа'} onChange={e=>setConfig(c=>({...c,token:e.target.value}))}/></label>
   {['youtube','tiktok'].includes(platform)&&<details className="social-guide"><summary>Обновление доступа<ChevronDown size={14}/></summary><div className="social-oauth-fields"><label className="field">{platform==='tiktok'?'Client key':'Client ID'}<input autoComplete="off" value={config.clientId||''} onChange={e=>setConfig(c=>({...c,clientId:e.target.value}))}/></label><label className="field">Client secret<input type="password" autoComplete="new-password" value={config.clientSecret||''} onChange={e=>setConfig(c=>({...c,clientSecret:e.target.value}))}/></label><label className="field">Refresh token<input type="password" autoComplete="new-password" value={config.refreshToken||''} onChange={e=>setConfig(c=>({...c,refreshToken:e.target.value}))}/></label></div></details>}
   <details className="social-guide"><summary>Как подключить<ChevronDown size={14}/></summary><ol>{guides[platform].steps.map(step=><li key={step}>{step}</li>)}</ol><a href={guides[platform].url} target="_blank" rel="noreferrer">Документация<ArrowUpRight size={13}/></a></details>
   <div className="social-local-note">Ключ хранится на локальном сервере</div><button className="btn btn-primary" type="submit" disabled={!!busy}>{busy==='save'?<LoaderCircle className="spin" size={15}/>:<Check size={15}/>}Проверить и подключить</button>
  </form>}{modalError&&<p className="social-form-error" role="alert">{modalError}</p>}
 </>}
 </div></Modal>}
 {testPost&&canPublish&&canManage&&<PublishDialog post={testPost} editable onClose={()=>setTestPost(null)}/>}
 </>;
}
