import {useEffect,useState} from 'react';
import {isLabrika,workspaceKey,personalKey} from './runtime';
export const permissionLabels={invite:'Приглашать сотрудников',manageSocial:'Подключать и менять соцсети',createPosts:'Создавать публикации',approvePosts:'Согласовывать публикации',schedulePosts:'Планировать публикации',editCompany:'Редактировать сведения о компании'};
export type TeamPermission=keyof typeof permissionLabels;
export interface TeamMember{id:string;accountId?:string;name:string;surname:string;patronymic?:string;email:string;phone:string;position:string;role:'owner'|'member';admin:boolean;permissions:TeamPermission[];status:'active'|'invited';inviteToken?:string;createdAt:string}
type Account={id:string;name:string;surname?:string;phone?:string;email:string;ownerId?:string};
function account():Account|null{try{const id=sessionStorage.getItem('labrika-current-account');return JSON.parse(localStorage.getItem('labrika-billing-v1')||'{}').accounts?.find((a:Account)=>a.id===id)||null;}catch{return null;}}
export function currentMemberId(){return isLabrika?account()?.id||'guest':sessionStorage.getItem('ygroup-current-member')||'ygroup-owner';}
export function teamOwnerId(){const a=account();return isLabrika?a?.ownerId||a?.id||'guest':'ygroup-owner';}
function teamKey(){return workspaceKey('team-v1');}
export function fullMemberName(member:Pick<TeamMember,'name'|'surname'|'patronymic'>){return [member.surname,member.name,member.patronymic].filter(Boolean).join(' ');}
export function getTeamMembers():TeamMember[]{try{const saved=JSON.parse(localStorage.getItem(teamKey())||'null');if(Array.isArray(saved)&&saved.length)return saved;}catch{}const a=account();let profile:any={};try{profile=JSON.parse(localStorage.getItem(personalKey('ygroup-profile-v1'))||'{}');}catch{}return [{id:teamOwnerId(),accountId:teamOwnerId(),name:isLabrika?a?.name||'Руководитель':profile.name||'Александр',surname:isLabrika?a?.surname||'':profile.surname||'',phone:isLabrika?a?.phone||'':profile.phone||'',email:isLabrika?a?.email||'':profile.email||'',position:'Руководитель',role:'owner',admin:true,permissions:Object.keys(permissionLabels) as TeamPermission[],status:'active',createdAt:new Date().toISOString()}];}
export function getTeamAccess(){const id=currentMemberId(),members=getTeamMembers();const member=members.find(m=>m.accountId===id||m.id===id);const isOwner=id===teamOwnerId()&&id!=='guest';const isAdmin=isOwner||!!member?.admin;return {member,isOwner,isAdmin,can:(permission:string)=>isAdmin||!!member?.permissions.includes(permission as TeamPermission)};}
export function useTeamAccess(){const [,refresh]=useState(0);useEffect(()=>{const update=()=>refresh(n=>n+1);window.addEventListener('team-change',update);window.addEventListener('storage',update);window.addEventListener('labrika-account-change',update);return()=>{window.removeEventListener('team-change',update);window.removeEventListener('storage',update);window.removeEventListener('labrika-account-change',update);};},[]);return getTeamAccess();}
function changed(){window.dispatchEvent(new Event('team-change'));window.dispatchEvent(new Event('labrika-account-change'));}
function saveTeam(members:TeamMember[]){localStorage.setItem(teamKey(),JSON.stringify(members));changed();}
export function saveTeamMember(input:TeamMember){const access=getTeamAccess(),members=getTeamMembers(),previous=members.find(m=>m.id===input.id);if(previous&&!access.isAdmin||!previous&&!access.can('invite'))throw new Error('Недостаточно прав');if(!input.name.trim()||!input.surname.trim()||!input.position.trim()||!/^\S+@\S+\.\S+$/.test(input.email)||input.phone.replace(/\D/g,'').length<7)throw new Error('Заполните ФИО, должность, телефон и почту');if(members.some(m=>m.id!==input.id&&m.email.toLowerCase()===input.email.trim().toLowerCase()))throw new Error('Эта почта уже есть в команде');
 const member={...input,name:input.name.trim(),surname:input.surname.trim(),patronymic:input.patronymic?.trim(),email:input.email.trim().toLowerCase(),phone:input.phone.trim(),position:input.position.trim()};
 if(previous){member.role=previous.role;member.accountId=previous.accountId;member.status=previous.status;member.inviteToken=previous.inviteToken;if(!access.isOwner){Object.assign(member,{name:previous.name,surname:previous.surname,patronymic:previous.patronymic,email:previous.email,phone:previous.phone});}if(previous.role==='owner')Object.assign(member,{admin:true,permissions:Object.keys(permissionLabels)});}
 else {member.role='member';member.status='invited';member.accountId=undefined;member.inviteToken=crypto.randomUUID()+crypto.randomUUID();if(!access.isAdmin){member.admin=false;member.permissions=[];}}
 saveTeam(previous?members.map(m=>m.id===member.id?member:m):[...members,member]);
 if(isLabrika&&member.accountId){const db=JSON.parse(localStorage.getItem('labrika-billing-v1')||'{}');const target=db.accounts?.find((a:Account)=>a.id===member.accountId);if(target){Object.assign(target,{name:member.name,surname:member.surname,email:member.email,phone:member.phone});localStorage.setItem('labrika-billing-v1',JSON.stringify(db));changed();}}
 return member;
}
export function removeTeamMember(id:string){const access=getTeamAccess();const member=getTeamMembers().find(m=>m.id===id);if(!access.isAdmin||member?.role==='owner'||member?.accountId===currentMemberId())throw new Error('Этого участника нельзя удалить');saveTeam(getTeamMembers().filter(m=>m.id!==id));}
export function lookupInvitation(token:string){if(!token)return null;for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i)!;if(!/^(labrika-workspace-.+-team-v1|ygroup-team-v1)$/.test(key))continue;try{const members=JSON.parse(localStorage.getItem(key)||'[]') as TeamMember[];const member=members.find(m=>m.status==='invited'&&m.inviteToken===token);const owner=members.find(m=>m.role==='owner');if(member&&owner)return{key,member,ownerId:owner.accountId||owner.id};}catch{}}return null;}
export function acceptTeamInvitation(token:string,email:string,accountId:string){const invitation=lookupInvitation(token);if(!invitation||invitation.member.email.toLowerCase()!==email.toLowerCase())throw new Error('Приглашение недействительно или адрес почты не совпадает');const members=JSON.parse(localStorage.getItem(invitation.key)!);localStorage.setItem(invitation.key,JSON.stringify(members.map((m:TeamMember)=>m.id===invitation.member.id?{...m,accountId,status:'active',inviteToken:undefined}:m)));changed();return invitation.ownerId;}
export function updateOwnIdentity(input:{name:string;surname?:string;phone?:string;email:string}){const access=getTeamAccess();if(!access.isOwner)throw new Error('Контактные данные изменяет руководитель');const members=getTeamMembers();const owner=members.find(m=>m.role==='owner')!;saveTeam(members.map(m=>m.id===owner.id?{...m,...input}:m));}
